### ISSUE TITLE
Can't get keyboard shortcut working

### ISSUE THREAD

**Issue by edrogersamfam** [ryantam626/jupyterlab_code_formatter#1]
I'm able to get the extension to work when I click "Apply Black Formatter" from the Command Palette menu. But I can't get the keyboard shortcut to work. The Command Palette also scrolls back to the top with each use of "Apply Black Formatter," which means that a keyboard shortcut would be really valuable.

Any thoughts?

### My setup:

| Software                              | Reported Version                                                                  |
|---------------------------------------|-----------------------------------------------------------------------------------|
| Linux kernel release                  | `4.4.0-1065-aws`                                                                  |
| Ubuntu                                | `Ubuntu 18.04.1 LTS`                                                              |
| Python                                | `Python 3.6.6 :: Anaconda, Inc.`                                                  |
| pip                                   | `pip 18.0 from /home/dsw/miniconda3/lib/python3.6/site-packages/pip (python 3.6)` |
| node                                  | `v8.11.4`                                                                         |
| npm                                   | `6.4.0`                                                                           |
| jupyter                               | `4.4.0`                                                                           |
| black                                 | `black, version 18.6b4`                                                           |
| JupyterLab                            | `0.34.0`                                                                          |
| @ryantam626/jupyterlab_code_formatter | `@ryantam626/jupyterlab_code_formatter v0.1.2,enabled,OK`                         |
| Browser                               | `Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)`                   |

### Excerpt from `pip freeze`:

```
$ pip freeze | grep 'jupyter'
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
jupyterlab==0.34.0
jupyterlab-code-formatter==0.1.0
jupyterlab-git==0.2.0
jupyterlab-latex==0.4.0
jupyterlab-launcher==0.13.1
```

![Screenshot of JupyterLab](https://raw.githubusercontent.com/edrogersamfam/jupyterlab_code_formatter/9d073220abd65f5924cc4ddd100d6336a246c6f0/jupyterlab-code-formatter_screenshot.png)

**Comment by ryantam626** [comment]
Fixed by 9956ff1e451b59724acd5012edbe706926ff1387, update the plugin and it should work. Please reopen if it still does work :+1:
