### ISSUE TITLE
Windows, error writing grammar tables

### ISSUE THREAD

**Issue by EWouters** [ryantam626/jupyterlab_code_formatter#10]
I get an error upon launching Jupyter Lab with this extension enabled:

```
[I 10:37:25.686 LabApp] Node v10.8.0

[I 10:37:26.075 LabApp] Build is up to date
Generating grammar tables from C:\Users\%USERNAME%\Anaconda3\lib\site-packages\blib2to3\Grammar.txt
Writing grammar tables to C:\Users\%USERNAME%\AppData\Local\black\black\Cache\18.9b0\Grammar3.7.1.final.0.pickle
Writing failed: [Errno 2] No such file or directory: 'C:\\Users\\%USERNAME%\\AppData\\Local\\black\\black\\Cache\\18.9b0\\Grammar3.7.1.final.0.pickle'
Generating grammar tables from C:\Users\%USERNAME%\Anaconda3\lib\site-packages\blib2to3\PatternGrammar.txt
Writing grammar tables to C:\Users\%USERNAME%\AppData\Local\black\black\Cache\18.9b0\PatternGrammar3.7.1.final.0.pickle
Writing failed: [Errno 2] No such file or directory: 'C:\\Users\\%USERNAME%\\AppData\\Local\\black\\black\\Cache\\18.9b0\\PatternGrammar3.7.1.final.0.pickle'
```

After manually creating the folder `C:\\Users\\%USERNAME%\\AppData\\Local\\black\\black\\Cache\\18.9b0` and relaunching Jupyter lab the error disappears (even though the folder seems to stay empty).

**Comment by ryantam626** [comment]
Hey! This seems to be Python in Windows shenanigans, this is something that this package will not aim to fix/workaround, thanks for the heads up though :+1: , shall put it in the readme

**Comment by bjtho08** [comment]
@ryantam626 I seem to experience the same issue on Ubuntu 16.04, so it appears to be OS independent.

**Comment by ryantam626** [comment]
Did you use your system's python to install jupyterlab or virtualenv/conda?

**Comment by bjtho08** [comment]
I actually use pyenv. Could that have something to do with the issue?

**Comment by ryantam626** [comment]
Hmm not that familiar with pyenv, but possibly. I think this is because the jupyterlab server is spawned with user that doesn't have privilege to create the cache needed for black. Did it work for you in the end? You could try creating the cache dir youself and chown to you user if not :thinking:

**Comment by roachsinai** [comment]
Same issue on Manjaro, using virtualenv.

```
[I 07:45:47.225 LabApp] Build is up to date
Generating grammar tables from /home/roach/.virtualenvs/nn/lib/python3.7/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/roach/.cache/black/19.3b0/Grammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/roach/.cache/black/19.3b0/tmpuxr828wb'
Generating grammar tables from /home/roach/.virtualenvs/nn/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/roach/.cache/black/19.3b0/PatternGrammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/roach/.cache/black/19.3b0/tmpc5xlgf9q'
```

And, there is no `black`  directory under `.cache`.

**Comment by ryantam626** [comment]
Interesting.. What does the directory ownership look like for `/home/roach/.cache`? And what user did you start jupyterlab with?

**Comment by roachsinai** [comment]
```
hmank ~ » whoami
roach
hmank ~ » la | grep .cache
drwxr-xr-x 53 roach roach 4.0K  7月 30 17:41 .cache
```

**Comment by ryantam626** [comment]
Can't reproduce the error myself unfortunately.. Could you try manually creating the `/home/roach/.cache/black/19.3b0` dir and see what happens?

**Comment by roachsinai** [comment]
No error after I created the directory `/home/roach/.cache/black/19.3b0`.

```
[I 19:56:30.440 LabApp] Build is up to date
Generating grammar tables from /home/roach/.virtualenvs/nn/lib/python3.7/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/roach/.cache/black/19.3b0/Grammar3.7.3.final.0.pickle
Generating grammar tables from /home/roach/.virtualenvs/nn/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/roach/.cache/black/19.3b0/PatternGrammar3.7.3.final.0.pickle
```

And then if I reboot jupyterlab it will not show infos about `black`.

**Comment by ryantam626** [comment]
> No error after I created the directory `/home/roach/.cache/black/19.3b0`.
> 
> ```
> [I 19:56:30.440 LabApp] Build is up to date
> Generating grammar tables from /home/roach/.virtualenvs/nn/lib/python3.7/site-packages/blib2to3/Grammar.txt
> Writing grammar tables to /home/roach/.cache/black/19.3b0/Grammar3.7.3.final.0.pickle
> Generating grammar tables from /home/roach/.virtualenvs/nn/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
> Writing grammar tables to /home/roach/.cache/black/19.3b0/PatternGrammar3.7.3.final.0.pickle
> ```
> 
> And then if I reboot jupyterlab it will not show infos about `black`.

Ah good. I assume it's working as expected now?

**Comment by roachsinai** [comment]
Yes, except have to mkdir by myself.

**Comment by shreyasgm** [comment]
Had the same issue, manually created `.cache/black/19.10b0`. The error disappeared but code formatting still wouldn't work with `black`. I had to move to `autopep8` instead.

**Comment by jhgoebbert** [comment]
I can confirm, that this bug is present for Linux, too ( https://github.com/ryantam626/jupyterlab_code_formatter/issues/82 ).
As we use JupyterLab in a multi-user environment with >300 user, it would be an somehow ugly workaround to mkdir ~/.cache/black/19.10b/ in everyones $HOME.

**Comment by AlJohri** [comment]
Linking root cause: https://github.com/psf/black/issues/1223

**Comment by EWouters** [comment]
Thanks for the fix @AlJohri !

**Comment by andreamoro** [comment]
Same here on a Mac OSX with a clean environment and brand new installation of the code formatter. 
The directory was not created.

**Comment by kavanase** [comment]
Same issue here as @andreamoro with new Mac OS X Catalina.

**Comment by jmbenedetto** [comment]
Same here with MacOS BigSur
