### ISSUE TITLE
update "packaging" dependency in tool.poetry.dependencies

### ISSUE THREAD

**Issue by AlJohri** [ryantam626/jupyterlab_code_formatter#101]
https://github.com/ryantam626/jupyterlab_code_formatter/blob/master/serverextension/pyproject.toml

```
ERROR: jupyterlab-code-formatter 1.0.3 has requirement packaging<20.0,>=19.2, but you'll have packaging 20.0 which is incompatible.
```

**Comment by ryantam626** [comment]
Thanks for reporting! I switched back to `setup.py` approach, effectively unpinning it along the way - closing.
