### ISSUE TITLE
Shortcut to format whole noteboo

### ISSUE THREAD

**Issue by notuntoward** [ryantam626/jupyterlab_code_formatter#103]
I know that I can format a single cell by mapping a keyboard shortcut to `jupyterlab_code_formatter:autopep8`.  

Is there also a function to format the whole notebook at once, as is done when clicking the "Format notebook" icon?

**Comment by ryantam626** [comment]
Hi! That would be `jupyterlab_code_formatter:format_all` as documented [here](https://jupyterlab-code-formatter.readthedocs.io/en/latest/how-to-use.html#other-available-commands)
