### ISSUE TITLE
404 POST issue on jupyterhub

### ISSUE THREAD

**Issue by ale-sc** [ryantam626/jupyterlab_code_formatter#104]
Hi,

first of thanks for the work you put into it.

I am trying to install the plugin on a machine with jupyterhub installed on it so that any user can have the plugin working on his/her lab. However I am running into the 404 POST issue when trying to format code in the cell using the button (see below).
![image](https://user-images.githubusercontent.com/5223203/73161740-88cfca00-40ec-11ea-946f-308bf138edcb.png)
Some more info that may help you, I did read the other issue with the 404 post error and made sure I installed it wright. I can see the format code button and the format cell menu item on the cell, however the commands are not showing up on the command palette nor I can see the formatters when using the url. Also please note that on my own machine, that has jupyterlab installed on, your plugin works great and I love it, so I am guessing it has something to do with the way jupyterhub spawns single users labs...

Thanks in advance,

Ale

**Comment by 46319943** [comment]
I have the same problem.
![image](https://user-images.githubusercontent.com/17161318/73820225-47e25e80-482c-11ea-845f-f0f7143d616e.png)
When I click the "Format notebook" button, the message appear in the console and the plugin doesn't work.
![image](https://user-images.githubusercontent.com/17161318/73820305-6f392b80-482c-11ea-9246-2c0276e0c57f.png)
ps: I have install Autopep8 and Black described in the documentation and restart the jupyterlab.

**Comment by ryantam626** [comment]
@ale-sc I will need to take some time to look at what jupyter hub is doing, have stepped away from maintaining this package these days, but I will see what I can do.

**Comment by ryantam626** [comment]
@46319943 can you post output of
`jupyter serverextension list` and `pip freeze` please?
Your issue doesn't look the same.

**Comment by 46319943** [comment]
`!jupyter serverextension list`
```
config dir: /home/jovyan/.jupyter
    jupyter_nbextensions_configurator  enabled 
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK
config dir: /opt/conda/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 1.2.5 OK
```
`!pip freeze`
```WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
alembic==1.3.3
appdirs==1.4.3
async-generator==1.10
attrs==19.3.0
autopep8==1.5
backcall==0.1.0
beautifulsoup4==4.8.2
black==19.10b0
bleach==3.1.0
blinker==1.4
bokeh==1.4.0
certifi==2019.11.28
certipy==0.1.3
cffi==1.13.2
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
conda==4.7.12
conda-package-handling==1.6.0
cryptography==2.8
cycler==0.10.0
Cython==0.29.14
cytoolz==0.10.1
dask==2.9.2
decorator==4.4.1
defusedxml==0.6.0
dill==0.3.1.1
distributed==2.10.0
entrypoints==0.3
fastcache==1.1.0
fsspec==0.6.2
gmpy2==2.1.0b1
h5py==2.10.0
HeapDict==1.0.1
idna==2.8
imageio==2.6.1
importlib-metadata==1.5.0
inflect==4.0.0
ipykernel==5.1.4
ipython==7.11.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
jaraco.itertools==5.0.0
jedi==0.16.0
Jinja2==2.11.0
joblib==0.14.1
json5==0.8.5
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.1
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyter-telemetry==0.0.4
jupyterhub==1.1.0
jupyterlab==1.2.5
jupyterlab-server==1.0.6
jupyterthemes==0.20.0
kiwisolver==1.1.0
lesscpy==0.14.0
llvmlite==0.31.0
locket==0.2.0
lxml==4.5.0
Mako==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.1
mistune==0.8.4
more-itertools==8.2.0
mpmath==1.1.0
msgpack==0.6.2
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.4
notebook==6.0.3
numba==0.48.0
numexpr==2.7.1
numpy==1.17.5
oauthlib==3.0.1
olefile==0.46
packaging==20.1
pamela==1.0.0
pandas==0.25.3
pandocfilters==1.4.2
parso==0.6.0
partd==1.1.0
pathlib2==2.3.5
pathspec==0.7.0
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==3.0.3
protobuf==3.11.2
psutil==5.6.7
ptyprocess==0.6.0
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycurl==7.43.0.4
Pygments==2.5.2
PyJWT==1.7.1
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyrsistent==0.15.7
PySocks==1.7.1
python-dateutil==2.8.1
python-editor==1.0.4
python-json-logger==0.1.11
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3
pyzmq==18.1.1
regex==2020.1.8
requests==2.22.0
rpy2==2.9.4
ruamel-yaml==0.15.80
ruamel.yaml.clib==0.2.0
scikit-image==0.16.2
scikit-learn==0.22.1
scipy==1.4.1
seaborn==0.9.0
Send2Trash==1.5.0
six==1.14.0
sortedcontainers==2.1.0
soupsieve==1.9.4
SQLAlchemy==1.3.13
statsmodels==0.11.0
sympy==1.5.1
tblib==1.6.0
terminado==0.8.3
testpath==0.4.4
toml==0.10.0
toolz==0.10.0
tornado==6.0.3
tqdm==4.42.0
traitlets==4.3.3
typed-ast==1.4.1
urllib3==1.25.7
vincent==0.4.4
wcwidth==0.1.8
webencodings==0.5.1
widgetsnbextension==3.5.1
xlrd==1.2.0
yapf==0.29.0
zict==1.0.0
zipp==2.1.0```
BTW, I launch the jupyter notebook in jupyter/datascience-notebook docker.
Thanks!

**Comment by ryantam626** [comment]
@46319943 You are missing the server extension.
You need to do this
```
pip install jupyterlab_code_formatter
jupyter serverextension enable --py jupyterlab_code_formatter
```

**Comment by 46319943** [comment]
@ryantam626 Thanks!!! I run the command and restart the jupyter lab. Then it works!!!
Sorry that I overlooked the first step in the document. I thought Extension Manager would do everything for me. Also I forgot to go through the closed issure.

**Comment by ryantam626** [comment]
@46319943 no problem :smile: it's a common issue that I forgot to put in the FAQ.

**Comment by ale-sc** [comment]
@ryantam626 
> @ale-sc I will need to take some time to look at what jupyter hub is doing, have stepped away from maintaining this package these days, but I will see what I can do.

Thanks, I think I've made some progress. If every user runs

`jupyter serverextension enable --py jupyterlab_code_formatter`

then it works! I've installed other extensions and once installed for the admin user it kind of propagated to any other user, yours not unless the above command is run for each new user. It would be nice to have this enabled by default for every user so that no initialization is necessary.

**Comment by ryantam626** [comment]
@ale-sc ah. could you give me an example of another server extension that just works out of the box for you :pray: ? i need to go poke around and see what did i do wrong

**Comment by ale-sc** [comment]
> @ale-sc ah. could you give me an example of another server extension that just works out of the box for you 🙏 ? i need to go poke around and see what did i do wrong

@ryantam626 
I am pasting here part of my Dockerfile for the extensions, all the extensions above yours work
```
RUN jupyter labextension install \
    @lckr/jupyterlab_variableinspector \
    @krassowski/jupyterlab_go_to_definition \
    @jupyterlab/hub-extension \
    @jupyterlab/toc \
    jupyterlab-drawio \
    @ryantam626/jupyterlab_code_formatter
```

**Comment by ryantam626** [comment]
ah server extension and lab extension is quite different. 

just a shot in the dark, what happens if you bake in 
` RUN jupyter serverextension enable --py jupyterlab_code_formatter --sys-prefix` into your dockerfile?

**Comment by ale-sc** [comment]
it's in already, sorry I should have pasted a bigger portion
```
RUN jupyter labextension install \
    @lckr/jupyterlab_variableinspector \
    @krassowski/jupyterlab_go_to_definition \
    @jupyterlab/hub-extension \
    @jupyterlab/toc \
    jupyterlab-drawio \
    @ryantam626/jupyterlab_code_formatter

RUN pip3 install jupyterlab_code_formatter
RUN jupyter serverextension enable --py jupyterlab_code_formatter
```
I believe that in this way the extension runs out of the box for the root user although I cannot confirm it as root is disabled on my hub. For now a possible workaround is for root to execute the last line with `runuser` at user creation...

**Comment by ryantam626** [comment]
do you mean the if you put the `--sys-prefix` flag, it breaks your docker image build?

also, out of curiosity, do you have any `USER <something>` clause in your dockerfile (or parent image)?

**Comment by ale-sc** [comment]
My bad, sorry I read your comment to quickly and I missed the `--sys-prefix` part I'll build it with this flag and let you know....

no I don't have the USER clause, not sure if it's in my parent though here is my FROM clause
```
ARG CUDA_VERSION=10.1
ARG CUDNN_VERSION=7
FROM nvidia/cuda:${CUDA_VERSION}-cudnn${CUDNN_VERSION}-devel-ubuntu18.04
```

**Comment by ale-sc** [comment]
@ryantam626 the `--sys-prefix` works great! Adding this to the Dockerfile does the trick.

``` RUN jupyter serverextension enable --py jupyterlab_code_formatter --sys-prefix ```

It might be a good idea to add it to the install instructions. I am closing the issue then.
