### ISSUE TITLE
Update or version check?

### ISSUE THREAD

**Issue by asteppke** [ryantam626/jupyterlab_code_formatter#107]
When switching PCs I upgraded Jupyter and all its extensions. Then applying the function to use black from the Jupyterlab code formatter extension corrupted my notebook file. After looking into this a bit it seems a similar case to [this](https://github.com/ryantam626/jupyterlab_code_formatter/issues/98) fixed issue. After updating both the python module and all its dependencies everything is working fine. 

The whole experience feels quite inconvenient though. Is is possible in the future that the extension checks the version of the python module and let the user know that this needs to be updated as well?

**Comment by ryantam626** [comment]
I have already added this in 1.1.0, 
edae94bbfdb4e19123628f2f1d9f8e0a9ebaa00c and a51a3dcc9a7a4d044119906f63319fe6f5f72b53

Unless you mean something entirely different?

**Comment by asteppke** [comment]
Thank you for the instant reply and the extension in general!

That is exactly what I was looking for, without it I ran into the mismatch of current labextension with outdated python backend which lead to the issue.

**Comment by ryantam626** [comment]
Actually you might be on to something on second thought, the version mismatch check is asymmetric -  (server plugin has to be >=1.1.0 for it to work, instead of either server plugin or lab plugin), that means only updating the lab plugin and having a stale server plugin (like in your case) would still be an issue.

I will reopen and pick this up later :+1:

**Comment by data-coder** [comment]
Hi, not sure if this is the right place. Anyway, here it goes:

I cannot use this extension, I'm getting this error in the browser JS console:
```
Something went wrong :(
 Error: "Invalid response: 422 Mismatched versions of server extension (1.2.0) and lab extension (1.1.0). Please ensure they are the same."
```
I tried to upgrade using:
`jupyter labextension install @ryantam626/jupyterlab_code_formatter@1.2.0      `
But got:
```
An error occured.
ValueError: 
"@ryantam626/jupyterlab_code_formatter@1.2.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension      Package
>=1.2.1 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/application
>=1.2.1 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/fileeditor
>=1.2.2 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/notebook
```
Thanks!

**Comment by asteppke** [comment]
@data-coder What does `jupyter lab --version` return for your environment?

**Comment by ryantam626** [comment]
> Hi, not sure if this is the right place. Anyway, here it goes:
> 
> I cannot use this extension, I'm getting this error in the browser JS console:
> 
> ```
> Something went wrong :(
>  Error: "Invalid response: 422 Mismatched versions of server extension (1.2.0) and lab extension (1.1.0). Please ensure they are the same."
> ```
> 
> I tried to upgrade using:
> `jupyter labextension install @ryantam626/jupyterlab_code_formatter@1.2.0 `
> But got:
> 
> ```
> An error occured.
> ValueError: 
> "@ryantam626/jupyterlab_code_formatter@1.2.0" is not compatible with the current JupyterLab
> Conflicting Dependencies:
> JupyterLab              Extension      Package
> >=1.2.1 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/application
> >=1.2.1 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/fileeditor
> >=1.2.2 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/notebook
> ```
> 
> `conda update --all ` doesn't solve the dependencies issues.
> Thanks!

Hi @data-coder 

you can do either
1. upgrade jupyterlab to 2.x.x
OR jupyterlab_code_formatter
2. `pip install jupyterlab_code_formatter==1.1.0` to downgrade the server extension

**Comment by data-coder** [comment]
Thank you! It's working now :)

Since I'm using conda, this did the trick for me:

`conda install -c conda-forge jupyterlab_code_formatter==1.1.0`

**Comment by ryantam626** [comment]
The original issue is now address in 1.2.1, please open another issue if someone is facing related issues :pray:
