### ISSUE TITLE
Ability to format active cell broken in latest version

### ISSUE THREAD

**Issue by stefanuddenberg** [ryantam626/jupyterlab_code_formatter#11]
The following shortcut worked fine on 0.1.6, but is now broken on 0.1.8:

```json
{"jupyterlab_code_formatter:black":{
    "command": "jupyterlab_code_formatter:black",
    "keys": ["F"],
    "selector": ".jp-Notebook:focus"
}}
```

Error is with line 64, checking if the widget content is not null.

**Comment by stefanuddenberg** [comment]
This is also true for the type of shortcut you gave as an example:

```json
{"jupyterlab_code_formatter:black":{
    "command": "jupyterlab_code_formatter:black",
    "keys": [
        "Ctrl K",
        "Ctrl M"
    ],
    "selector": ".jp-Notebook.jp-mod-editMode"
}}
```

Windows 10 x64
@ryantam626/jupyterlab_code_formatter v0.1.8
jupyterlab-code-formatter  0.1.1
jupyterlab 0.35.4

**Comment by ryantam626** [comment]
Ah, apologies, a fix has now been released. Let me know if it still breaks for you somehow :+1:
