### ISSUE TITLE
Make the plugin installation work without requiring restart JupyterLab

### ISSUE THREAD

**Issue by dclong** [ryantam626/jupyterlab_code_formatter#117]
Restarting JupyterLab is not an option for people that using JupyterLab via Docker. In order to try the plugin, users (using JupyterLab via Docker) has to rebuild their Docker image which is inconvenient.

**Comment by ryantam626** [comment]
This is the limitation of jupyter [(reference1,](https://github.com/jupyter/jupyter/issues/336) [reference2),](https://discourse.jupyter.org/t/reload-jupyter-serverextension/2200) I can't do anything about this (in this repo anyway).

But if you want to try the plugin though, you only need to build the docker image once no?

**Comment by ryantam626** [comment]
Until jupyter allow for hot install of plugin, can't really do much here. Will be closing until then
