### ISSUE TITLE
not working nor showing in the jupterlab 2

### ISSUE THREAD

**Issue by jajcayn** [ryantam626/jupyterlab_code_formatter#127]
Hello,

**Checklist prior to opening an issue**
- [X] I have followed fully the installation steps laid out in the documentation site.
- [X] I have restarted jupyterlab.
- [X] I have read the FAQ section in the documentation site.

**Describe the bug**
So I installed the formatter, restarted jupyter lab, but I cannot see the format button in the taskbar, nor in the context menu after right-click. As if nothing was installed.

**Diagnostic commands**
Please attach the output of the following commands (please format them properly)

- `pip freeze`
```
absl-py==0.9.0
anytree==2.8.0
appdirs==1.4.3
appnope==0.1.0
astor==0.8.1
attrs==19.3.0
backcall==0.1.0
black==19.10b0
bleach==3.1.1
cachetools==4.0.0
certifi==2019.11.28
chardet==3.0.4
click==7.1.1
cloudpickle==1.3.0
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.1.1
entrypoints==0.3
flake8==3.7.9
gast==0.2.2
google-auth==1.11.3
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
gpflow==2.0.0rc1
grpcio==1.27.2
h5py==2.10.0
idna==2.9
importlib-metadata==1.5.0
ipykernel==5.1.4
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.16.0
Jinja2==2.11.1
joblib==0.14.1
json5==0.9.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.0.0
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyterlab==2.0.1
jupyterlab-code-formatter==1.2.2
jupyterlab-server==1.0.7
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.2.0
mccabe==0.6.1
mistune==0.8.4
more-itertools==8.2.0
multipledispatch==0.6.0
multiprocess==0.70.9
nbconvert==5.6.1
nbformat==5.0.4
notebook==6.0.3
numexpr==2.7.1
numpy==1.18.1
oauthlib==3.1.0
opt-einsum==3.2.0
packaging==20.3
pandas==1.0.2
pandocfilters==1.4.2
parso==0.6.2
pathos==0.2.5
pathspec==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
pluggy==0.13.1
pox==0.2.7
ppft==1.6.6.1
prometheus-client==0.7.1
prompt-toolkit==3.0.4
protobuf==3.11.3
ptyprocess==0.6.0
py==1.8.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.5.0
pyflakes==2.1.1
Pygments==2.6.1
pygpso==0.3
pyparsing==2.4.6
pyrsistent==0.15.7
pytest==5.4.1
python-dateutil==2.8.1
python-igraph==0.8.0
pytz==2019.3
pyzmq==19.0.0
qtconsole==4.7.1
QtPy==1.9.0
regex==2020.2.20
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.0
scikit-learn==0.22.2.post1
scipy==1.4.1
Send2Trash==1.5.0
six==1.14.0
tables==3.6.1
tabulate==0.8.6
tensorboard==2.1.1
tensorflow==2.1.0
tensorflow-estimator==2.1.0
tensorflow-probability==0.9.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
texttable==1.6.2
toml==0.10.0
tornado==6.0.4
traitlets==4.3.3
typed-ast==1.4.1
urllib3==1.25.8
wcwidth==0.1.8
webencodings==0.5.1
Werkzeug==1.0.0
widgetsnbextension==3.5.1
wrapt==1.12.1
zipp==3.1.0
```
- `jupyter labextension list`
```
JupyterLab v2.0.1
Known labextensions:
   app dir: /Users/nikola/.virtualenvs/pygpso/share/jupyter/lab
        @ryantam626/jupyterlab_code_formatter v1.2.2  enabled  OK

Uninstalled core extensions:
    @ryantam626/jupyterlab_code_formatter
```
- `jupyter serverextension list`
```
config dir: /Users/nikola/.jupyter
    jupyterlab_code_formatter  enabled
    - Validating...
      jupyterlab_code_formatter  OK
config dir: /Users/nikola/.virtualenvs/pygpso/bin/../etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.0.1 OK
config dir: /usr/local/etc/jupyter
    jupyterlab_code_formatter  enabled
    - Validating...
      jupyterlab_code_formatter  OK
```

**Screenshots**
<img width="1440" alt="Screenshot 2020-03-18 at 23 06 57" src="https://user-images.githubusercontent.com/6525217/77011976-4fd60800-696d-11ea-9356-207ffc1ee170.png">

**Additional context**

Thanks for your time!

**Comment by AndeYashwanth** [comment]
I updated the extension today and I get the following message when I start juoyter lab.
![image](https://user-images.githubusercontent.com/34389995/77137632-b0139980-6a94-11ea-8ccd-79a93147d329.png)
I tried uninstalling and reinstalling the extension.
```
❯ pip freeze | grep jupy
jupyter==1.0.0
jupyter-client==6.0.0
jupyter-console==6.1.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.3
jupyter-highlight-selected-word==0.2.0
jupyter-http-over-ws==0.0.8
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyter-server==0.1.1
jupyter-server-proxy==1.2.0
jupyter-tabnine==1.0.2
jupyter-telemetry==0.0.5
jupyterlab==2.0.1
jupyterlab-code-formatter==1.2.0
jupyterlab-github==2.0.0
jupyterlab-pygments==0.1.0
jupyterlab-server==1.0.7
jupyterthemes==0.20.0
```

**Comment by ryantam626** [comment]
Hi @jajcayn, that's a bit concerning, from the diagnostic commands output you posted, it should have worked.. Is there anything weird in the terminal you launched jupyterlab? And also any weird in the console of your browser?

**Comment by ryantam626** [comment]
@AndeYashwanth different issue, follow [this](https://jupyterlab-code-formatter.readthedocs.io/en/latest/faq.html#version-mismatch-issue), you most likely are not on jupyterlab 2 yet

**Comment by jajcayn** [comment]
@ryantam626 Hey, thanks for the reply! And good catch! I just saw `enabled` and `OK` I thought that everything's good. Well, I am easily convinced :)

But you're right. That was the culprit. In any case, I reinstall `jupyterlab` and the extension, but to no avail. In the end, I googled and found this discourse - https://discourse.jupyter.org/t/extension-shows-up-as-both-installed-and-uninstalled-and-doesnt-work/2688/2 where the users recommend in such a case to manually delete `build_config.json` in `<location of python libs etc>\share\jupyter\lab\settings\build_config.json`.

That helped. So the solution is to: uninstall all extensions, manually delete `build_config.json` and then install again. Now it seems to work!

Thanks for your time:)

**Comment by ryantam626** [comment]
Ooo alrighty, good to know. The path to the solution was a bit convoluted but glad it worked out :smile:

**Comment by AndeYashwanth** [comment]
> @AndeYashwanth different issue, follow [this](https://jupyterlab-code-formatter.readthedocs.io/en/latest/faq.html#version-mismatch-issue), you most likely are not on jupyterlab 2 yet and that caused a version mismatch that reinstalling won't help

I tried reinstalling before mentioning this issue but didn't work. 
I saw the documentation and installed using 
```
jupyter labextension install @ryantam626/jupyterlab_code_formatter
pip install jupyterlab_code_formatter
jupyter serverextension enable --py jupyterlab_code_formatter
```
and changed the default formater to autopep8 and it worked.
But the keyboard shortcuts are not working.
I pasted below code in Advanced Settings Editor>Keyboard shortcuts. 
```
{
    "shortcuts": [
        {
            "command": "jupyterlab_code_formatter:black",
            "keys": [
                "Ctrl K",
                "Ctrl M"
            ],
            "selector": ".jp-Notebook.jp-mod-editMode"
        }
    ]
}
```

**Comment by ryantam626** [comment]
Is the docs not clear? Please submit a PR if so :pray: 
The need for changing the default formatter is documented [here](https://jupyterlab-code-formatter.readthedocs.io/en/latest/how-to-use.html#changing-default-formatter)

And the keyboard shortcuts is because you didn't change it to `jupyterlab_code_formatter:autopep8`

Please please please open a new issue next time, I don't like commenting on closed issue especially when it's not related to the original issue.
