### ISSUE TITLE
isort support

### ISSUE THREAD

**Issue by ostrokach** [ryantam626/jupyterlab_code_formatter#13]
It would be great if support for isort could be added at some point.

(Also, thanks for creating this plugin; it's super useful!)

**Comment by ryantam626** [comment]
Hello! Indeed. I didn't add it in the first implementation because I thought isort requires some config file to configure it, it seems like I was mistaken, will work on this when I get more bandwidth! (PR always welcomed :stuck_out_tongue: )

**Comment by ryantam626** [comment]
Isort support added now, let me know if it doesn't quite work as expected :wink:

**Comment by ostrokach** [comment]
It works great! Thank you!
