### ISSUE TITLE
"s is not iterable" on PySpark Kernel 

### ISSUE THREAD

**Issue by devstein** [ryantam626/jupyterlab_code_formatter#131]
**Checklist prior to opening an issue**
- [x] I have followed fully the installation steps laid out in the documentation site.
- [x] I have restarted jupyterlab.
- [x] I have read the FAQ section in the documentation site.

**Describe the bug**
I successfully installed `jupyterlab_code_formatter` and it works on Python notebooks; however, I would also like it to format PySpark notebooks (still Python), but I get the following error: `s is not iterable`. The workaround is to switch the kernel back to Python then format then rever it back to PySpark. Is there a way to fix this via the config? 

I'm assuming this [line of code is relevant](https://github.com/ryantam626/jupyterlab_code_formatter/blob/968c041508/labextension/src/formatter.ts#L122)

**Diagnostic commands**
Please attach the output of the following commands (please format them properly)

- `pip freeze`

- `jupyter labextension list`

- `jupyter serverextension list`

**Screenshots**

**Additional context**

Happy to provide the diagnostic command if that's helpful here! Also happy to contribute.

**Comment by ryantam626** [comment]
What's the name of the kernel you are using? That is indeed the line breaking

**Comment by devstein** [comment]
I use the [sparkmagic PySpark kernel](https://github.com/jupyter-incubator/sparkmagic/tree/master/sparkmagic/sparkmagic/kernels/pysparkkernel). Here is the metadata field of a notebook with the PySpark kernel:

```json
 "metadata": {
  "celltoolbar": "Tags",
  "kernelspec": {
   "display_name": "PySpark",
   "language": "",
   "name": "pysparkkernel"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "python",
    "version": 3
   },
   "mimetype": "text/x-python",
   "name": "pyspark",
   "pygments_lexer": "python3"
  }
 },
```

**Comment by devstein** [comment]
@ryantam626 Any thoughts? Happy to make a PR if the fix is obvious (or the fix for the kernel spec)

**Comment by ryantam626** [comment]
Hi, sorry I was AFK. I am working on a fix now.

**Comment by ryantam626** [comment]
I published a new version 1.2.3, try upgrading and see if it works?

**Comment by devstein** [comment]
@ryantam626 Thank you! I'll try it out and let you know

**Comment by devstein** [comment]
@ryantam626 Unfortunately the fix didn't work. I took a look at your changes and [I believe this is what is going wrong](https://github.com/ryantam626/jupyterlab_code_formatter/blob/6c39d2f000578e5151dc636b4a0a185fb1d08678/labextension/src/formatter.ts#L79-L96):

```js
  private getNotebookType() {
    if (this.notebookTracker.currentWidget) {
      const metadata = this.notebookTracker.currentWidget.content.model.metadata.toJSON();
     // 1. Both metadata and metadata.kernelspec are defined
      if (metadata && metadata.kernelspec) {
        // 2. It returns metadata.kernelspec.language, which is ""
        // @ts-ignore
        return metadata.kernelspec.language;
      }
     // We never get here :( 
      if (metadata && metadata.language_info) {
        // @ts-ignore
        return metadata.language_info.codemirror_mode.name;
      }
    }
    return null;
  }

  private getDefaultFormatters(config: any): Array<string> {
    const notebookType = this.getNotebookType();
    //  3  notebookType == "" so this evaluates to false 
    if (notebookType) {

   // 4 return []
```

If you like, I can make a PR to fix with the following change

```js
  private getNotebookType() {
   if !(this.notebookTracker.currentWidget)  return null;

   const metadata = this.notebookTracker.currentWidget.content.model.metadata.toJSON();

   if !(metadata)  return null;
   
  if (metadata.kernelspec && metadata.kernelspec.language) {
        // @ts-ignore
        return metadata.kernelspec.language;
      }

   if (metadata.language_info) {
        // @ts-ignore
        return metadata.language_info.codemirror_mode.name;
      }
    }
    return null;
  }


```

**Comment by ryantam626** [comment]
Yep looks sensible, did you test with a local installation of the updated plugin by the way?

**Comment by ryantam626** [comment]
Oops, it autoclosed the issue! Try 1.2.4 if you haven't and see if it work :smile: ?

**Comment by devstein** [comment]
@ryantam626 Works! Thanks for all the help on this 🥇
