### ISSUE TITLE
Jupyter 2.1.1 

### ISSUE THREAD

**Issue by JTebeka** [ryantam626/jupyterlab_code_formatter#136]
Hi, 
I follow your steps in a previous issue to install code_formatter with jupyter 2 ie : 
pip install -U jupyterlab_code_formatter
jupyter labextension install @ryantam626/jupyterlab_code_formatter@v1.2.5 (last version)

**Describe the bug**
Nothing happens. I can't see the button to format the text as in the previous version. 

- `pip freeze`
absl-py==0.9.0
appnope==0.1.0
asn1crypto==1.3.0
astor==0.8.0
astroid==2.3.3
attrs==19.3.0
autopep8==1.5.2
backcall==0.1.0
bleach==3.1.4
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
cryptography==2.8
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
et-xmlfile==1.0.1
flake8==3.7.9
future==0.18.2
gast==0.2.2
google-pasta==0.2.0
grpcio==1.16.1
h5py==2.10.0
idna==2.9
importlib-metadata==1.5.0
inflection==0.3.1
ipykernel==5.1.4
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
jdcal==1.4.1
jedi==0.15.2
Jinja2==2.11.1
joblib==0.14.1
json5==0.9.4
jsonpath-rw==1.4.0
jsonschema==3.2.0
jupyter-client==6.1.2
jupyter-core==4.6.3
jupyter-lsp==0.8.0
jupyterlab==2.1.1
jupyterlab-code-formatter==1.2.5
jupyterlab-server==1.1.0
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
lxml==4.5.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.3
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
more-itertools==8.2.0
multitasking==0.0.9
nbconvert==5.6.1
nbformat==5.0.4
nltk==3.4.5
notebook==6.0.3
numpy==1.18.1
openpyxl==3.0.3
opt-einsum==3.1.0
packaging==20.3
pandas==1.0.3
pandas-datareader==0.8.1
pandaSDMX==0.9
pandocfilters==1.4.2
parso==0.6.2
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
plotly==4.6.0
pluggy==0.13.1
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==3.0.4
protobuf==3.11.4
ptyprocess==0.6.0
pycodestyle==2.5.0
pycparser==2.20
pydocstyle==5.0.2
pyflakes==2.1.1
Pygments==2.6.1
pylint==2.4.4
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyrsistent==0.16.0
PySocks==1.7.1
python-dateutil==2.8.1
python-jsonrpc-server==0.3.4
python-language-server==0.31.10
pytz==2019.3
PyYAML==5.3.1
pyzmq==18.1.1
Quandl==3.4.8
requests==2.23.0
retrying==1.3.3
rope==0.16.0
scikit-learn==0.22.1
scipy==1.4.1
seaborn==0.10.0
Send2Trash==1.5.0
six==1.14.0
snowballstemmer==2.0.0
statsmodels==0.11.0
tensorboard==2.0.0
tensorflow==2.0.0
tensorflow-estimator==2.0.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
traitlets==4.3.3
ujson==1.35
urllib3==1.25.8
wcwidth==0.1.9
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
xlrd==1.2.0
yapf==0.29.0
yfinance==0.1.54
zipp==2.2.0

- `jupyter labextension list`
(Analysis) jacques@MBP-de-Jacques ~ % pip freeze
absl-py==0.9.0
appnope==0.1.0
asn1crypto==1.3.0
astor==0.8.0
astroid==2.3.3
attrs==19.3.0
autopep8==1.5.2
backcall==0.1.0
bleach==3.1.4
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
cryptography==2.8
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
et-xmlfile==1.0.1
flake8==3.7.9
future==0.18.2
gast==0.2.2
google-pasta==0.2.0
grpcio==1.16.1
h5py==2.10.0
idna==2.9
importlib-metadata==1.5.0
inflection==0.3.1
ipykernel==5.1.4
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
jdcal==1.4.1
jedi==0.15.2
Jinja2==2.11.1
joblib==0.14.1
json5==0.9.4
jsonpath-rw==1.4.0
jsonschema==3.2.0
jupyter-client==6.1.2
jupyter-core==4.6.3
jupyter-lsp==0.8.0
jupyterlab==2.1.1
jupyterlab-code-formatter==1.2.5
jupyterlab-server==1.1.0
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
lxml==4.5.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.3
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
more-itertools==8.2.0
multitasking==0.0.9
nbconvert==5.6.1
nbformat==5.0.4
nltk==3.4.5
notebook==6.0.3
numpy==1.18.1
openpyxl==3.0.3
opt-einsum==3.1.0
packaging==20.3
pandas==1.0.3
pandas-datareader==0.8.1
pandaSDMX==0.9
pandocfilters==1.4.2
parso==0.6.2
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
plotly==4.6.0
pluggy==0.13.1
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==3.0.4
protobuf==3.11.4
ptyprocess==0.6.0
pycodestyle==2.5.0
pycparser==2.20
pydocstyle==5.0.2
pyflakes==2.1.1
Pygments==2.6.1
pylint==2.4.4
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyrsistent==0.16.0
PySocks==1.7.1
python-dateutil==2.8.1
python-jsonrpc-server==0.3.4
python-language-server==0.31.10
pytz==2019.3
PyYAML==5.3.1
pyzmq==18.1.1
Quandl==3.4.8
requests==2.23.0
retrying==1.3.3
rope==0.16.0
scikit-learn==0.22.1
scipy==1.4.1
seaborn==0.10.0
Send2Trash==1.5.0
six==1.14.0
snowballstemmer==2.0.0
statsmodels==0.11.0
tensorboard==2.0.0
tensorflow==2.0.0
tensorflow-estimator==2.0.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
traitlets==4.3.3
ujson==1.35
urllib3==1.25.8
wcwidth==0.1.9
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
xlrd==1.2.0
yapf==0.29.0
yfinance==0.1.54
zipp==2.2.0
(Analysis) jacques@MBP-de-Jacques ~ % jupyter labextension list
JupyterLab v2.1.1
Known labextensions:
   app dir: /Users/jacques/opt/anaconda3/envs/Analysis/share/jupyter/lab
        @aquirdturtle/collapsible_headings v2.2.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/shortcutui v0.5.0-beta.2  enabled  OK
        @jupyterlab/toc v3.0.0  enabled  OK
        @krassowski/jupyterlab-lsp v1.0.0  enabled  OK
        @lckr/jupyterlab_variableinspector v0.5.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.2.5  enabled  OK
        jupyterlab-chart-editor v4.6.0  enabled  OK
        jupyterlab-logout v0.5.0  enabled  OK
        jupyterlab-plotly v4.6.0  enabled  OK
        jupyterlab-python-file v0.4.0  enabled  OK
        jupyterlab-spreadsheet v0.3.1  enabled  OK
        jupyterlab-system-monitor v0.6.0  enabled  OK
        jupyterlab-theme-toggle v0.5.0  enabled  OK
        jupyterlab-topbar-extension v0.5.0  enabled  OK
        jupyterlab-topbar-text v0.5.0  enabled  OK
        jupyterlab_filetree v0.2.2  enabled  OK
        plotlywidget v4.6.0  enabled  OK

**Uninstalled core extensions:
    @ryantam626/jupyterlab_code_formatter** _(I don't know why and it may be my problem)_

- `jupyter serverextension list`
config dir: /Users/jacques/opt/anaconda3/envs/Analysis/etc/jupyter
    jupyter_lsp  enabled 
    - Validating...
      jupyter_lsp 0.8.0 OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.1.1 OK

Thanks for your help.

**Comment by ryantam626** [comment]
That's weird :thinking: 

Try 
```
pip install jupyterlab_code_formatter
jupyter serverextension enable --py jupyterlab_code_formatter
```
?
the first line will probably does nothing for you, but it's fine.

**Comment by JTebeka** [comment]
It does not change. No buttons appear. 
I just see that in my previous list jupyterlab_code_formatter 1.2.5 was installed 
I have : 
Known labextensions:
   app dir: /Users/jacques/opt/anaconda3/envs/Analysis/share/jupyter/lab
        @aquirdturtle/collapsible_headings v2.2.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/shortcutui v0.5.0-beta.2  enabled  OK
        @jupyterlab/toc v3.0.0  enabled  OK
        @krassowski/jupyterlab-lsp v1.0.0  enabled  OK
        @lckr/jupyterlab_variableinspector v0.5.0  enabled  OK
        **@ryantam626/jupyterlab_code_formatter v1.2.5  enabled  OK**
        jupyterlab-chart-editor v4.6.0  enabled  OK
        jupyterlab-logout v0.5.0  enabled  OK
        jupyterlab-plotly v4.6.0  enabled  OK
        jupyterlab-python-file v0.4.0  enabled  OK
        jupyterlab-spreadsheet v0.3.1  enabled  OK
        jupyterlab-system-monitor v0.6.0  enabled  OK
        jupyterlab-theme-toggle v0.5.0  enabled  OK
        jupyterlab-topbar-extension v0.5.0  enabled  OK
        jupyterlab-topbar-text v0.5.0  enabled  OK
        jupyterlab_filetree v0.2.2  enabled  OK
        plotlywidget v4.6.0  enabled  OK

Uninstalled core extensions:
    @ryantam626/jupyterlab_code_formatter

**Comment by ryantam626** [comment]
```
Uninstalled core extensions:
@ryantam626/jupyterlab_code_formatter
```
from `jupyter labextension list`'s output
is one of the issue

also another issue is that it's completely missing from `jupyter serverextension list` which my suggestion above should fix

**Comment by ryantam626** [comment]
can you try reinstalling the plugin? this is very weird

**Comment by JTebeka** [comment]
What should I do to reinstall it ? Maybe delete it before no ?

**Comment by JTebeka** [comment]
and it is now in servextension list after the previous code : 

config dir: /Users/jacques/.jupyter
    jupyterlab_code_formatter  enabled 
    - Validating...
      jupyterlab_code_formatter  OK
config dir: /Users/jacques/opt/anaconda3/envs/Analysis/etc/jupyter
    jupyter_lsp  enabled 
    - Validating...
      jupyter_lsp 0.8.0 OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.1.1 OK

**Comment by JTebeka** [comment]
Here is my bar and I don't see the usual button to use code_formatter 


<img width="1642" alt="Capture d’écran 2020-04-27 à 12 33 31" src="https://user-images.githubusercontent.com/49912455/80362697-5bc5bb80-8883-11ea-92e2-bf038f48dce4.png">

**Comment by ryantam626** [comment]
Try 
```
jupyter labextension uninstall @ryantam626/jupyterlab_code_formatter
jupyter labextension install @ryantam626/jupyterlab_code_formatter
```
to reinstall the lab extension :thinking:

**Comment by JTebeka** [comment]
sorry ! No change. I do not see the button

**Comment by ryantam626** [comment]
hmm maybe try something like this https://github.com/jupyterlab/jupyterlab/issues/8122#issuecomment-617209892
seems really relevant here
