### ISSUE TITLE
Uninstalling Jupyterlab_code_formatter

### ISSUE THREAD

**Issue by cSharma19** [ryantam626/jupyterlab_code_formatter#137]
Hello - I ran into some installation issues while trying the code formatter. So I tried to uninstall everything, inluding Juputer lab, and then tried to re-install. I keep getting this error however - seems like it still tries to keep uploading this program. 

JupyterLab does load, but I also keep getting errors like "ModuleNotFoundError: No module named 'numpy' when I try to import it. All of this was working before. Quite new to Python.....would appreciate any advice on how to proceed.

I used Anaconda Navigator for installation, and for removal. Upon launch, here's the error from Anaconda Navigotor:

[I 19:03:02.129 LabApp] The port 8888 is already in use, trying another port.
[I 19:03:02.130 LabApp] The port 8889 is already in use, trying another port.
[I 19:03:02.961 LabApp] JupyterLab extension loaded from C:\Users\XXX\Anaconda3\envs\veUdem\lib\site-packages\jupyterlab
[I 19:03:02.962 LabApp] JupyterLab application directory is C:\Users\XXX\Anaconda3\envs\veUdem\share\jupyter\lab
[W 19:03:03.542 LabApp] Error loading server extension jupyterlab_code_formatter
Traceback (most recent call last):
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\site-packages\notebook\notebookapp.py", line 1670, in init_server_extensions
mod = importlib.import_module(modulename)
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\importlib\__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1006, in _gcd_import
File "", line 983, in _find_and_load
File "", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'jupyterlab_code_formatter'
[I 19:03:03.547 LabApp] Serving notebooks from local directory: C:\Users\XXX
[I 19:03:03.547 LabApp] The Jupyter Notebook is running at:
[I 19:03:03.547 LabApp] http://localhost:8890/?token=e54b2749c82e0a66e3d6d11b75531a4363c3d470ee788196
[I 19:03:03.547 LabApp] or http://127.0.0.1:8890/?token=e54b2749c82e0a66e3d6d11b75531a4363c3d470ee788196
[I 19:03:03.547 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:03:03.694 LabApp] 

To access the notebook, open this file in a browser:
file:///C:/Users/XXX/AppData/Roaming/jupyter/runtime/nbserver-15408-open.html
Or copy and paste one of these URLs:
http://localhost:8890/?token=e54b2749c82e0a66e3d6d11b75531a4363c3d470ee788196
or http://127.0.0.1:8890/?token=e54b2749c82e0a66e3d6d11b75531a4363c3d470ee788196
[I 19:03:07.448 LabApp] Build is up to date
[W 19:03:07.614 LabApp] 404 GET /jupyterlab_code_formatter/formatters?1588204986499 (::1) 56.97ms referer=http://localhost:8890/lab
[I 19:03:09.383 LabApp] Kernel started: 7b7b7882-5844-496f-b5c8-685c2268da4c
[I 19:03:09.423 LabApp] Kernel started: 4b0c77d8-e534-4e1b-a976-996e3fce6c54
[I 19:03:09.468 LabApp] Kernel started: 93fea25b-a76b-419f-bc8c-6233edd682fa
Traceback (most recent call last):
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\site-packages\ipykernel_launcher.py", line 15, in 
from ipykernel import kernelapp as app
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\site-packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\site-packages\ipykernel\connect.py", line 18, in 
import jupyter_client
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\site-packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\site-packages\jupyter_client\connect.py", line 21, in 
import zmq
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\site-packages\zmq\__init__.py", line 47, in 
from zmq import backend
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\site-packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\site-packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\XXX\Anaconda3\envs\veUdem\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.

**Comment by ryantam626** [comment]
i see you are using windows, do you have access to a command line prompt?
you need to find out how you can access it and use the following commands
`jupyterlab labextension uninstall @ryantam626/jupyterlab_code_formatter`
`pip uninstall jupyterlab_code_formatter`

**Comment by cSharma19** [comment]
@ryantam626  - thanks! I'll try this and get back. If I get it to work, I'll try installed the code formatter again....

**Comment by ryantam626** [comment]
> Not quite sure what is going on:
> 
> 1. I fired up the Anaconda command prompt and confirmed that JupyterLab code formatter is not present in the package list in my environment.
> 2. Just in case some vesitge of it was left during my last attempt at un-installing, I used the commands you provided. Looks like they're confirming that no such package exists. Screenshot below:
>    ![Annotation 2020-04-30 092148](https://user-images.githubusercontent.com/39869009/80730701-8441f580-8acf-11ea-9949-6221cfda241f.jpg)
> 3. I then fired up Anaconda navigator to laucn JupyterLab, and I still get the same error message - for some reason, it's still looking for Jupyterlab_code_formatter - error in attached file.
>    [AnacondaError.txt](https://github.com/ryantam626/jupyterlab_code_formatter/files/4559360/AnacondaError.txt)
> 
> It seems like the code_formatter hasn't been removed entirely...not sure why Anaconda Navigator still looks for it while running. Would appreciate some advice. thanks!

sorry i meant
`jupyter labextension uninstall @ryantam626/jupyterlab_code_formatter`

**Comment by cSharma19** [comment]
I'm afraid, it's the same error when starting JupyterLab. Error message attached. Also screenshots from both virtual and base environment showing jupyterlab_code_formatter isn't present. Do I need to delete any specific folders perhaps?
Thanks!
[AnacondaError.txt](https://github.com/ryantam626/jupyterlab_code_formatter/files/4560538/AnacondaError.txt)
![baseEnv](https://user-images.githubusercontent.com/39869009/80747135-8fede600-8ae8-11ea-839e-0e36cc0e6eaa.jpg)
![virtualEnv](https://user-images.githubusercontent.com/39869009/80747136-90867c80-8ae8-11ea-9fe9-fbc7b8e52a03.jpg)

**Comment by cSharma19** [comment]
Interesting - JupyterLab opens fine when I use Anaconda Prompt, but not with the Navigator. Likely the issue is with the navigator...I'll follow up with Anaconda. Closing this issue for the meantime, unless you have any other comments (will wait till end of day). Thanks!

**Comment by ryantam626** [comment]
I looked at your original post a little bit closer, it's not a lab extension issue.

The `ModuleNotFoundError: No module named 'jupyterlab_code_formatter'` error is happening when the notebook server trying to activate the server extension, try `jupyter serverextension disable jupyterlab_code_formatter` (or something to that effect) to get rid of that error message.

**Comment by cSharma19** [comment]
Thanks for getting back....I'll try those suggestions and let you know how it goes:)

**Comment by cSharma19** [comment]
Hi - I'm afraid I'm not able to dig further into it...beyond my capabilities (new to Python etc.). In any case, the Anaconda Command prompt is working fine for now, and my fear is that I'll mess something else up if I try anything else. I guess we leave the issue open for now.....?

**Comment by ryantam626** [comment]
I would prefer to close this to clean up my repo's issue list to be honest, if you encounter another issue feel free to open another one :smile:

**Comment by cSharma19** [comment]
Agreed..and thanks for all your help!
