### ISSUE TITLE
Black formatter fails to deal properly with semicolons

### ISSUE THREAD

**Issue by pv** [ryantam626/jupyterlab_code_formatter#139]
**Describe the bug**

The conversion functions in `respect_semicolon_and_magic` with Black converter (and black version 19.10b0) change the cell contents
```
something;
```
to
```
something
;
```
because Black seems to produce a trailing newline. However, semicolon on an empty line is not valid Python syntax (although IPython tolerates it), and `black` chokes on it when the formatting is done a second time.

This code
https://github.com/ryantam626/jupyterlab_code_formatter/blob/4d03863b73ae92e4e1ed40cfd097b71c3b90502d/serverextension/jupyterlab_code_formatter/formatters.py#L43-L44
probably should read `code = code.rstrip() + ";"`.

**Comment by ryantam626** [comment]
ah thanks for reporting this! will get it fixed this long weekend :)

**Comment by ryantam626** [comment]
That should be fixed now in the version 1.3.1 now :smile: thanks for reporting this again!
