### ISSUE TITLE
error: Cannot parse: 1:10: isinstance?

### ISSUE THREAD

**Issue by michaelaye** [ryantam626/jupyterlab_code_formatter#148]
**Checklist prior to opening an issue**
- [x] I have followed fully the installation steps laid out in the documentation site.
- [x] I have restarted jupyterlab.
- [x] I have read the FAQ section in the documentation site.

**Describe the bug**

Notebook throws error when trying to format:

> Cannot parse: 1:10: isinstance?

**Diagnostic commands**
Please attach the output of the following commands (please format them properly)

- `pip freeze | grep jupyter`
```bash
$ pip freeze|grep jupyter                                                                    (py37)
jupyter-client==6.1.3
jupyter-contrib-core==0.3.3
jupyter-core==4.6.3
jupyter-nbextensions-configurator==0.4.1
jupyterlab==2.1.4
jupyterlab-code-formatter @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_code_formatter_1588958755647/work
jupyterlab-git @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab-git_1591094216199/work
jupyterlab-github==2.0.0
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1590229434073/work
```

- `jupyter labextension list`
$ jupyter labextension list                                                                  (py37)
JupyterLab v2.1.4
Known labextensions:
   app dir: /Users/klay6683/miniconda3/envs/py37/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/geojson-extension v2.0.1  enabled  OK
        @jupyterlab/git v0.20.0  enabled  OK
        @jupyterlab/github v2.0.0  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @pyviz/jupyterlab_pyviz v1.0.4  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.3.1  enabled  OK
        jupyter-matplotlib v0.7.2  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK

- `jupyter serverextension list`
$ jupyter serverextension list                                                               (py37)
config dir: /Users/klay6683/.jupyter
    jupyterlab_code_formatter  enabled
    - Validating...
      jupyterlab_code_formatter  OK
config dir: /Users/klay6683/miniconda3/envs/py37/etc/jupyter
    ipyparallel.nbextension  enabled
    - Validating...
      ipyparallel.nbextension  OK
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.1.4 OK
    jupyterlab_git disabled
    - Validating...
      jupyterlab_git 0.20.0 OK
    jupyterlab_github  enabled
    - Validating...
      jupyterlab_github 2.0.0 OK
    nbdime  enabled
    - Validating...
      nbdime 2.0.0 OK
    jupyter_nbextensions_configurator  enabled
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK

**Screenshots**
<img width="661" alt="Screenshot 2020-06-02 16 52 05" src="https://user-images.githubusercontent.com/69774/83577448-682bdc80-a4f1-11ea-8bfe-9a40c726afce.png">

**Comment by ryantam626** [comment]
Could you copy and paste content of the cell where you defined `find_best_header` please :pray: ?
I need that for reproducing the error

**Comment by ryantam626** [comment]
I am pretty sure it's due to invalid Python in the cell, re-open this issue if it's not :)

**Comment by michaelaye** [comment]
sorry for the lack of reply. you are seeing everything, and the function works. What does the 1:10 in the error mean? I cannot deduce what it points to...

**Comment by ryantam626** [comment]
It means there is a syntax error in your code, line 1 column 10.
Actually I see the issue now, you need to comment out the `isinstance?` cell

**Comment by michaelaye** [comment]
ah, all lines of code together, makes sense now, thanks. Ok, so it needs to be Python legal, not IPython legal, understood.

**Comment by ryantam626** [comment]
Yep that's exactly it! :+1:

**Comment by michaelaye** [comment]
doh, it actually says so in the error! I though instance referred to some instance of an object in your code but it actually cites the broken line! DOH!

**Comment by michaelaye** [comment]
great extension btw, i love it!

**Comment by ryantam626** [comment]
heh, thanks for the kind words :smile:
