### ISSUE TITLE
'jupyterlab_code_formatter:black' is not registered

### ISSUE THREAD

**Issue by ratulray** [ryantam626/jupyterlab_code_formatter#149]
**Checklist prior to opening an issue**
- [x] I have followed fully the installation steps laid out in the documentation site.
- [x] I have restarted jupyterlab.
- [x] I have read the FAQ section in the documentation site.

**Describe the bug**
When I try to use cell format, I see the following error in console:
`index.es6.js:514 Cannot execute key binding 'Ctrl Shift F': command 'jupyterlab_code_formatter:black' is not registered.`
(Ctrl Shift F is the shortcut I assigned to it)
**Diagnostic commands**
Please attach the output of the following commands (please format them properly)

- `pip freeze`
https://justpaste.it/59qrg
- `jupyter labextension list`
```
JupyterLab v2.1.4
Known labextensions:
   app dir: /mnt1/miniconda/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.3.1  enabled  OK
        jupyterlab-plotly v4.8.1  enabled  OK
        plotlywidget v4.8.1  enabled  OK

Uninstalled core extensions:
    @jupyter-widgets/jupyterlab-manager
    @ryantam626/jupyterlab_code_formatter
```
- `jupyter serverextension list`
```
config dir: /home/hadoop/.jupyter
    jupyterlab_code_formatter  enabled 
    - Validating...
      jupyterlab_code_formatter  OK
config dir: /mnt1/miniconda/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.1.4 OK
```
**Screenshots**

**Additional context**
I had to uninstall and reinstall `jupyterlab_code_formatter` after upgrading to JupyterLab v2.1.4 because there was a version conflict.

**Comment by ryantam626** [comment]
Issue is most likely this 
```
Uninstalled core extensions:
    @jupyter-widgets/jupyterlab-manager
    @ryantam626/jupyterlab_code_formatter
```
Try following this https://github.com/jupyterlab/jupyterlab/issues/8122#issuecomment-617209892 ?

**Comment by ratulray** [comment]
Yes, above step followed by a `jupyter lab build` fixed it. Thanks.
