### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by aced125** [ryantam626/jupyterlab_code_formatter#150]
After creating a new env, installing jupyterlab, following the instructions on the docs, I get this:

```
Jupyterlab Code Formatter ErrorFormatter not found!
```

when I try to format a cell!

**Comment by ryantam626** [comment]
did you install black and isort?

**Comment by nelsyeung** [comment]
I think it's really just the documentation in https://jupyterlab-code-formatter.readthedocs.io/en/latest/installation.html could do with some updating?

Currently, the main commands don't include installing `isort`, so it can be confusing as the default basically requires `pip install isort black`.

In addition, people could be struggling to find the right settings, as https://jupyterlab-code-formatter.readthedocs.io/en/latest/how-to-use.html#changing-default-formatter doesn't really tell you where to set the options. It could be confusing for beginners or people who haven't used Jupyter Lab in some time.

When I just click on "Advanced Settings Editor" and land on a random setting (e.g., "CodeMirror"), then pasting in the suggested method to change default formatter, you'll get a silent error on the bottom right corner saying `preferences is not a valid property`, which will then lead to the reported error.

Maybe it's best to say something like:
> Go to "Settings" > "Advanced Settings Editor" > "Jupyterlab Code Formatter", in the "User Preferences" panel, enter, for example:
```
{
    "preferences": {
        "default_formatter": {
            "python": "autopep8",
            "R": "styler"
        }
    }
}
```

**Comment by ryantam626** [comment]
Right, thanks @nelsyeung! These are excellent suggestion! I couldn't quite figure out how to make the documentation better for some time, your insight has helped a lot :+1:
