### ISSUE TITLE
Error: Formatter not found!

### ISSUE THREAD

**Issue by ddobrinskiy** [ryantam626/jupyterlab_code_formatter#154]
Hey, probably there is some common mistake on my side, but I've tried several solutions from FAQ/other issues, all to no avail.

I'm running Ubuntu 18.04

**Checklist prior to opening an issue**
- [x] I have followed fully the installation steps laid out in the documentation site.
- [x] I have restarted jupyterlab.
- [x] I have read the FAQ section in the documentation site.

**Describe the bug**
When trying to format a cell, I get `Error: Formatter not found!`

**Diagnostic commands**
Please attach the output of the following commands (please format them properly)

```
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

❯ pip freeze | grep 'jupyterlab\|black'
black==19.10b0
jupyterlab==2.1.4
jupyterlab-code-formatter==1.3.1
jupyterlab-server==1.1.5

❯ jupyter labextension list
JupyterLab v2.1.4
Known labextensions:
   app dir: /home/david/miniconda3/share/jupyter/lab
        @axlair/jupyterlab_vim v0.12.4  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @kiteco/jupyterlab-kite v0.2.1-a.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.3.1  enabled  OK
        jupyterlab-execute-time v1.0.0  enabled  OK

❯ jupyter serverextension list
config dir: /home/david/.jupyter
    jupyterlab_code_formatter  enabled
    - Validating...
      jupyterlab_code_formatter  OK
config dir: /home/david/miniconda3/etc/jupyter
    jupyter_kite  enabled
    - Validating...
      jupyter_kite 0.2.1a0 OK
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.1.4 OK
    jupyterlab_code_formatter  enabled
    - Validating...
      jupyterlab_code_formatter  OK
```

**Screenshots**
Attaching a screenshot from chromium console if that helps
![image](https://user-images.githubusercontent.com/29500178/85876501-7c0beb00-b7de-11ea-958a-3abf30bde873.png)

**Additional context**
None as of yet

**Comment by ryantam626** [comment]
Hi! I believe it's because of my poor documentation agian... The default formatters are isort + black, maybe you don't have isort installed? You can install isort or alternatively change the formatters to use to just black (see https://jupyterlab-code-formatter.readthedocs.io/en/latest/how-to-use.html#chaining-default-formatters)

**Comment by ddobrinskiy** [comment]
Ohhhh, yeah, that was it. Works like a charm now, thanks!
