### ISSUE TITLE
Latest version mismatch in PyPI and conda-forge

### ISSUE THREAD

**Issue by DangoMelon** [ryantam626/jupyterlab_code_formatter#157]
Just found out that a new release of the code formatter extension was issued a couple of days ago. The latest version of the package (1.3.2) is available in PyPI but not in conda-forge. Logically, trying to upgrade using conda-forge will issue a version mismatch when launching JupyterLab.

![image](https://user-images.githubusercontent.com/23618263/87123624-c19fcd80-c24c-11ea-9aec-c592966131eb.png)

The issue is easily resolved by using `pip` instead of `conda`.

**Comment by ryantam626** [comment]
Hmm I don't personally manage the publishing the conda-forge packages, nor do I know how right now.
It was pretty weird that conda-forge didn't pick up my changes over at https://github.com/conda-forge/jupyterlab_code_formatter-feedstock maybe I did something wrong..

**Comment by ryantam626** [comment]
1.3.4 seems to be realease now after a manual kick, closing this :+1:
