### ISSUE TITLE
Not working after update to 1.3.4

### ISSUE THREAD

**Issue by mkrusenbaum** [ryantam626/jupyterlab_code_formatter#158]
Hey,

i just updated to v1.3.4 (both) and with that updated isort to 5.0.9. I don't get any error messages but I can't get the extension to work.

It's showing up in the 'Advanced Settings Editor' but not in the command-palette.

Reinstalled black, isort, as well as the jupyter and server extension multiple times in any order but nothing seems to work.

Any ideas?

PS: The extension is still showing up in the "advanced settings editor" even after uninstalling the extension and running jupyter lab clean && jupyter lab build isn't that weird?

**Comment by ryantam626** [comment]
Hello!
Can you post output of
`pip freeze`
`jupyter labextension list`
`jupyter serverextension list`
please?

**Comment by mkrusenbaum** [comment]
Hi,

sure! I'm using conda so i'm including a `conda list --export` 
The `labextension list` shows something that might be of interest?

Thanks for your help!

`pip freeze`
appdirs==1.4.3
appnope==0.1.0
attrs==19.3.0
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
black==19.10b0
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1588608214987/work
brotlipy==0.7.0
Cartopy==0.17.0
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==7.1.2
cmocean==2.0
colorspacious==1.1.2
cryptography==2.9.2
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
gsw==3.3.1
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1593328102638/work
importlib-metadata @ file:///Users/runner/miniforge3/conda-bld/importlib-metadata_1593211382425/work
ipykernel @ file:///Users/runner/miniforge3/conda-bld/ipykernel_1594210146077/work/dist/ipykernel-5.3.2-py3-none-any.whl
ipython @ file:///Users/runner/miniforge3/conda-bld/ipython_1593235464339/work
ipython-genutils==0.2.0
isort @ file:///Users/runner/miniforge3/conda-bld/isort_1594465563184/work
jedi @ file:///Users/runner/miniforge3/conda-bld/jedi_1592619347183/work
Jinja2==2.11.2
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1591810480056/work
jsonschema==3.2.0
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1594732094290/work
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.3
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator @ file:///Users/runner/miniforge3/conda-bld/jupyter_nbextensions_configurator_1594127118794/work
jupyterlab==2.1.5
jupyterlab-code-formatter @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_code_formatter_1594711437728/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1593951277307/work
kiwisolver==1.2.0
lxml @ file:///Users/runner/miniforge3/conda-bld/lxml_1594322709119/work
MarkupSafe==1.1.1
matplotlib @ file:///Users/runner/miniforge3/conda-bld/matplotlib-base_1594091691585/work
mistune==0.8.4
mypy-extensions==0.4.3
nbconvert==5.6.1
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1594060262917/work
notebook @ file:///Users/runner/miniforge3/conda-bld/notebook_1594078855275/work
numpy @ file:///Users/runner/miniforge3/conda-bld/numpy_1591485228204/work
olefile==0.46
OWSLib @ file:///home/conda/feedstock_root/build_artifacts/owslib_1591376955812/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1589925210001/work
pandas @ file:///Users/runner/miniforge3/conda-bld/pandas_1592422011735/work
pandocfilters==1.4.2
parso==0.7.0
pathspec==0.8.0
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow @ file:///Users/runner/miniforge3/conda-bld/pillow_1594212124634/work
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1590412252446/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1592500439797/work
ptyprocess==0.6.0
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
pyepsg==0.4.0
Pygments==2.6.1
pykdtree==1.3.1
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyproj @ file:///Users/runner/miniforge3/conda-bld/pyproj_1588596078513/work
pyrsistent==0.16.0
pyshp==2.1.0
PySocks==1.7.1
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
pyzmq==19.0.1
regex @ file:///Users/runner/miniforge3/conda-bld/regex_1591646146133/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1592425495151/work
scipy @ file:///Users/runner/miniforge3/conda-bld/scipy_1593253488446/work
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-base_1591878760859/work
Send2Trash==1.5.0
Shapely==1.7.0
six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
statsmodels @ file:///Users/runner/miniforge3/conda-bld/statsmodels_1591963266538/work
terminado==0.8.3
testpath==0.4.4
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1589469402899/work
tornado==6.0.4
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1588470653596/work
urllib3==1.25.9
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1592931742287/work
webencodings==0.5.1
xarray @ file:///home/conda/feedstock_root/build_artifacts/xarray_1594532077462/work
zipp==3.1.0


`conda list --export`
# platform: osx-64
appdirs=1.4.3=py_1
appnope=0.1.0=py38h32f6830_1001
attrs=19.3.0=py_0
backcall=0.2.0=pyh9f0ad1d_0
black=19.10b0=py38_0
bleach=3.1.5=pyh9f0ad1d_0
brotlipy=0.7.0=py38h64e0658_1000
ca-certificates=2020.6.20=hecda079_0
cartopy=0.17.0=py38h9bcff04_1015
certifi=2020.6.20=py38h32f6830_0
cffi=1.14.0=py38h356ff06_0
chardet=3.0.4=py38h32f6830_1006
click=7.1.2=pyh9f0ad1d_0
cmocean=2.0=py_3
colorspacious=1.1.2=pyh24bf2e0_0
cryptography=2.9.2=py38hb761dab_0
cycler=0.10.0=py_2
decorator=4.4.2=py_0
defusedxml=0.6.0=py_0
entrypoints=0.3=py38h32f6830_1001
freetype=2.10.2=h8da9a1a_0
geos=3.8.1=h4a8c4bd_0
gsw=3.3.1=py38h65ad66c_2
icu=67.1=h4a8c4bd_0
idna=2.10=pyh9f0ad1d_0
importlib-metadata=1.7.0=py38h32f6830_0
importlib_metadata=1.7.0=0
ipykernel=5.3.2=py38h23f93f0_0
ipython=7.16.1=py38h23f93f0_0
ipython_genutils=0.2.0=py_1
isort=5.0.9=py38h32f6830_0
jedi=0.17.1=py38h32f6830_0
jinja2=2.11.2=pyh9f0ad1d_0
jpeg=9d=h0b31af3_0
json5=0.9.4=pyh9f0ad1d_0
jsonschema=3.2.0=py38h32f6830_1
jupyter_client=6.1.6=py_0
jupyter_contrib_core=0.3.3=py_2
jupyter_contrib_nbextensions=0.5.1=py38_0
jupyter_core=4.6.3=py38h32f6830_1
jupyter_highlight_selected_word=0.2.0=py38_1000
jupyter_latex_envs=1.4.4=py38_1000
jupyter_nbextensions_configurator=0.4.1=py38h32f6830_1
jupyterlab=2.1.5=py_0
jupyterlab_code_formatter=1.3.4=py_0
jupyterlab_server=1.2.0=py_0
kiwisolver=1.2.0=py38ha0d09dd_0
krb5=1.17.1=h14dd6a4_1
lcms2=2.11=h174193d_0
libblas=3.8.0=17_openblas
libcblas=3.8.0=17_openblas
libcurl=7.71.1=he6690cf_1
libcxx=10.0.0=h1af66ff_2
libedit=3.1.20191231=hed1e85f_1
libffi=3.2.1=h4a8c4bd_1007
libgfortran=4.0.0=2
libiconv=1.15=h0b31af3_1006
liblapack=3.8.0=17_openblas
libopenblas=0.3.10=h3d69b6c_0
libpng=1.6.37=hbbe82c9_1
libsodium=1.0.17=h01d97ff_0
libssh2=1.9.0=h39bdce6_3
libtiff=4.1.0=h2ae36a8_6
libuv=1.38.0=h0b31af3_0
libwebp-base=1.1.0=h0b31af3_3
libxml2=2.9.10=hc06c4ae_1
libxslt=1.1.33=h29b7fa6_1
llvm-openmp=10.0.0=h28b9765_0
lxml=4.5.2=py38hc829089_0
lz4-c=1.9.2=h4a8c4bd_1
markupsafe=1.1.1=py38h64e0658_1
matplotlib=3.2.2=1
matplotlib-base=3.2.2=py38h1300a51_1
mistune=0.8.4=py38h64e0658_1001
mypy_extensions=0.4.3=py38h32f6830_1
nbconvert=5.6.1=py38h32f6830_1
nbformat=5.0.7=py_0
ncurses=6.1=h0a44026_1002
nodejs=14.5.0=h2c41780_0
notebook=6.0.3=py38h32f6830_1
numpy=1.18.5=py38h1f821a2_0
olefile=0.46=py_0
openssl=1.1.1g=h0b31af3_0
owslib=0.20.0=py_0
packaging=20.4=pyh9f0ad1d_0
pandas=1.0.5=py38h5fc983b_0
pandoc=2.10=0
pandocfilters=1.4.2=py_1
parso=0.7.0=pyh9f0ad1d_0
pathspec=0.8.0=pyh9f0ad1d_0
patsy=0.5.1=py_0
pexpect=4.8.0=py38h32f6830_1
pickleshare=0.7.5=py38h32f6830_1001
pillow=7.2.0=py38h83dc5e5_1
pip=20.1.1=py_1
proj=7.0.0=hbce2d5c_4
prometheus_client=0.8.0=pyh9f0ad1d_0
prompt-toolkit=3.0.5=py_1
ptyprocess=0.6.0=py_1001
pycparser=2.20=pyh9f0ad1d_2
pyepsg=0.4.0=py_0
pygments=2.6.1=py_0
pykdtree=1.3.1=py38h65ad66c_1003
pyopenssl=19.1.0=py_1
pyparsing=2.4.7=pyh9f0ad1d_0
pyproj=2.6.1.post1=py38h7d7e87d_0
pyrsistent=0.16.0=py38h64e0658_0
pyshp=2.1.0=py_0
pysocks=1.7.1=py38h32f6830_1
python=3.8.3=cpython_hd5f0129_0
python-dateutil=2.8.1=py_0
python_abi=3.8=1_cp38
pytz=2020.1=pyh9f0ad1d_0
pyyaml=5.3.1=py38h64e0658_0
pyzmq=19.0.1=py38h1fcdcd6_0
readline=8.0=hed1e85f_1
regex=2020.6.8=py38h64e0658_0
requests=2.24.0=pyh9f0ad1d_0
scipy=1.5.0=py38h38b60c6_0
seaborn=0.10.1=1
seaborn-base=0.10.1=py_1
send2trash=1.5.0=py_0
setuptools=49.2.0=py38h32f6830_0
shapely=1.7.0=py38h5b1fbde_3
six=1.15.0=pyh9f0ad1d_0
sqlite=3.32.3=h93121df_1
statsmodels=0.11.1=py38h64e0658_2
terminado=0.8.3=py38h32f6830_1
testpath=0.4.4=py_0
tk=8.6.10=hbbe82c9_0
toml=0.10.1=pyh9f0ad1d_0
tornado=6.0.4=py38h64e0658_1
traitlets=4.3.3=py38h32f6830_1
typed-ast=1.4.1=py38h0b31af3_0
typing_extensions=3.7.4.2=py_0
urllib3=1.25.9=py_0
wcwidth=0.2.5=pyh9f0ad1d_0
webencodings=0.5.1=py_1
wheel=0.34.2=py_1
xarray=0.16.0=py_0
xz=5.2.5=h0b31af3_1
yaml=0.2.5=h0b31af3_0
zeromq=4.3.2=h6de7cb9_2
zipp=3.1.0=py_0
zlib=1.2.11=h0b31af3_1006
zstd=1.4.4=h4b3e974_3

`jupyter labextension list`
JupyterLab v2.1.5
Known labextensions:
   app dir: env/share/jupyter/lab
        @ryantam626/jupyterlab_code_formatter v1.3.4  enabled  OK

Uninstalled core extensions:
    @ryantam626/jupyterlab_code_formatter


`jupyter serverextension list`
config dir: //////
    jupyterlab_code_formatter  enabled 
    - Validating...
      jupyterlab_code_formatter  OK
config dir: ///////
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.1.5 OK
    jupyter_nbextensions_configurator  enabled 
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK

**Comment by ryantam626** [comment]
```
jupyter labextension list
JupyterLab v2.1.5
Known labextensions:
app dir: env/share/jupyter/lab
@ryantam626/jupyterlab_code_formatter v1.3.4 enabled OK

Uninstalled core extensions:
@ryantam626/jupyterlab_code_formatter
```
that's the issue, try this? https://github.com/jupyterlab/jupyterlab/issues/8122#issuecomment-617209892

I really need to add this to the FAQ :sweat_smile:

**Comment by mkrusenbaum** [comment]
Oh man.
Thanks, that solved it right away.
I'm embarassed for not finding this solution :D thanks!

**Comment by ryantam626** [comment]
Nono don't be embarassed :smile: , this is quite hidden tbh, one wouldn't really expect this to happen when upgrading a package :sweat_smile: 
Glad it worked out now!
