### ISSUE TITLE
Jupyter 2.2

### ISSUE THREAD

**Issue by Jacques2101** [ryantam626/jupyterlab_code_formatter#159]
Hi, 

I have just update jupyterlab to 2.2 version and I can't see anymore the button for code_formatter as previously. 
I reload jupyterlab also. All others extensions seem to work correctly. 
I have no error message. Nothing happens that's all. 
As I previously had something similar, I then follow your previous recommandations : 
- désinstallation/ reinstall the extension 
- delete the file as in  jupyterlab/jupyterlab#8122 (comment)

Previously, it worked but nothing now.  

Thanks for your help. 

- `pip freeze`
appnope==0.1.0
astroid @ file:///opt/concourse/worker/volumes/live/b22b518b-f584-4586-5ee9-55bfa4fca96e/volume/astroid_1592495912194/work
astropy==4.0.1.post1
attrs==19.3.0
autopep8 @ file:///tmp/build/80754af9/autopep8_1592412889138/work
backcall==0.2.0
beautifulsoup4==4.9.1
bleach==3.1.5
brotlipy==0.7.0
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==7.1.2
confuse @ file:///home/conda/feedstock_root/build_artifacts/confuse_1593279073800/work
cryptography==2.9.2
cvxpy==1.0.31
cycler==0.10.0
DBnomics==1.2.0
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.1.1
ecos==2.0.7.post1
entrypoints==0.3
et-xmlfile==1.0.1
ffn==0.3.4
flake8==3.8.3
future==0.18.2
hmmlearn==0.2.3
hmmviz==0.0.7
html5lib @ file:///tmp/build/80754af9/html5lib_1593446221756/work
htmlmin==0.1.12
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
ImageHash @ file:///home/conda/feedstock_root/build_artifacts/imagehash_1588182723834/work
importlib-metadata @ file:///opt/concourse/worker/volumes/live/84197498-cbc0-4436-7ce0-03c4490b7a28/volume/importlib-metadata_1593446431408/work
inflection @ file:///home/conda/feedstock_root/build_artifacts/inflection_1594127810808/work
ipykernel @ file:///Users/runner/miniforge3/conda-bld/ipykernel_1594210160185/work/dist/ipykernel-5.3.2-py3-none-any.whl
ipython @ file:///opt/concourse/worker/volumes/live/7ea70a71-5624-4799-50b3-3b90e07922f3/volume/ipython_1593447385860/work
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
jdcal==1.4.1
jedi @ file:///opt/concourse/worker/volumes/live/114a62c0-dd60-4a40-6382-85abb31b5f6e/volume/jedi_1592841953086/work
Jinja2==2.11.2
joblib @ file:///tmp/build/80754af9/joblib_1594236160679/work
json5==0.9.5
jsonschema==3.2.0
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1594732094290/work
jupyter-core==4.6.3
jupyter-kite==0.2.1a0
jupyter-lsp==0.8.0
jupyterlab==2.2.0
jupyterlab-code-formatter @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_code_formatter_1594711437728/work
jupyterlab-server @ file:///tmp/build/80754af9/jupyterlab_server_1594164409481/work
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
llvmlite==0.33.0+1.g022ab0f
lxml @ file:///Users/runner/miniforge3/conda-bld/lxml_1594322707743/work
MarkupSafe==1.1.1
matplotlib @ file:///opt/concourse/worker/volumes/live/34dd81d3-0a70-4e5e-5ad6-be36ca7e59f7/volume/matplotlib-base_1592846084794/work
mccabe==0.6.1
missingno==0.4.2
mistune==0.8.4
more-itertools==8.4.0
multiprocess==0.70.9
multitasking==0.0.9
nbconvert==5.6.1
nbformat==5.0.7
networkx @ file:///tmp/build/80754af9/networkx_1594377231366/work
nltk @ file:///tmp/build/80754af9/nltk_1592496090529/work
notebook==6.0.3
numba==0.50.1
numpy @ file:///Users/runner/miniforge3/conda-bld/numpy_1591485226984/work
olefile==0.46
openpyxl @ file:///tmp/build/80754af9/openpyxl_1594167385094/work
osqp==0.6.1
packaging==20.4
pandas @ file:///opt/concourse/worker/volumes/live/38d1301c-8fa9-4d2f-662e-34dddf33b183/volume/pandas_1592841668171/work
pandas-datareader==0.8.1
pandas-profiling @ file:///home/conda/feedstock_root/build_artifacts/pandas-profiling_1589366436905/work
pandaSDMX @ file:///home/conda/feedstock_root/build_artifacts/pandasdmx_1590694245737/work
pandocfilters==1.4.2
parso==0.7.0
patsy==0.5.1
pexpect==4.8.0
phik @ file:///home/conda/feedstock_root/build_artifacts/phik_1590331950347/work
pickleshare==0.7.5
Pillow @ file:///opt/concourse/worker/volumes/live/05b3bc99-cf9f-44f2-42cf-267ed3a55922/volume/pillow_1594307311725/work
plotly @ file:///tmp/build/80754af9/plotly_1593522991827/work
pluggy==0.13.1
prometheus-client==0.8.0
prompt-toolkit==3.0.5
ptyprocess==0.6.0
pycodestyle==2.6.0
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pydantic @ file:///Users/runner/miniforge3/conda-bld/pydantic_1594475038828/work
pydocstyle @ file:///tmp/build/80754af9/pydocstyle_1592848020240/work
pyflakes==2.2.0
Pygments==2.6.1
pylint @ file:///opt/concourse/worker/volumes/live/42ede439-2571-4cb2-513c-394625d2381b/volume/pylint_1592496039330/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1594392929924/work
pyparsing==2.4.7
pyportfolioopt==1.2.3
pyrsistent==0.16.0
PySocks==1.7.1
python-dateutil==2.8.1
python-jsonrpc-server @ file:///tmp/build/80754af9/python-jsonrpc-server_1594397536060/work
python-language-server @ file:///opt/concourse/worker/volumes/live/b528bc67-8964-47eb-5268-7d9c1a3b621a/volume/python-language-server_1594161912847/work
pytz==2020.1
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.1
Quandl==3.5.0
QuantStats==0.0.25
regex==2020.5.14
requests @ file:///tmp/build/80754af9/requests_1592841827918/work
requests-cache==0.4.13
retrying==1.3.3
rope==0.17.0
scikit-learn==0.23.1
scipy @ file:///Users/runner/miniforge3/conda-bld/scipy_1593253483509/work
scs==2.1.2
seaborn==0.10.1
Send2Trash==1.5.0
six==1.15.0
snowballstemmer==2.0.0
soupsieve==2.0.1
statsmodels==0.11.1
tabulate==0.8.7
tangled-up-in-unicode @ file:///home/conda/feedstock_root/build_artifacts/tangled-up-in-unicode_1589363771888/work
terminado==0.8.3
testpath==0.4.4
threadpoolctl==2.1.0
toml @ file:///tmp/build/80754af9/toml_1592853716807/work
tornado==6.0.4
tqdm @ file:///tmp/build/80754af9/tqdm_1593446365756/work
traitlets==4.3.3
typed-ast==1.4.1
ujson==1.35
urllib3==1.25.9
visions @ file:///home/conda/feedstock_root/build_artifacts/visions_1589284473785/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
widgetsnbextension==3.5.1
wrapt==1.11.2
xlrd==1.2.0
XlsxWriter==1.2.9
yapf @ file:///tmp/build/80754af9/yapf_1593528177422/work
yfinance==0.1.54
zipp==3.1.0

- `jupyter labextension list`
   app dir: /Users/jacques/opt/anaconda3/envs/Data/share/jupyter/lab
        @aquirdturtle/collapsible_headings v2.2.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/debugger v0.2.0  enabled  OK
        @jupyterlab/shortcutui v0.5.0-beta.2  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @karosc/jupyterlab_dracula v2.0.3  enabled  OK
        @krassowski/jupyterlab-lsp v1.0.0  enabled  OK
        @lckr/jupyterlab_variableinspector v0.5.1  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.3.4  enabled  OK
        @telamonian/theme-darcula v2.0.0  enabled  OK
        jupyterlab-chart-editor v4.8.2  enabled  OK
        jupyterlab-dash v0.2.0  enabled  OK
        jupyterlab-execute-time v1.0.0  enabled  OK
        jupyterlab-logout v0.5.0  enabled  OK
        jupyterlab-plotly v4.8.2  enabled  OK
        jupyterlab-python-file v0.4.0  enabled  OK
        jupyterlab-spreadsheet v0.3.2  enabled  OK
        jupyterlab-system-monitor v0.6.0  enabled  OK
        jupyterlab-theme-solarized-dark v1.0.1  enabled  OK
        jupyterlab-theme-toggle v0.5.0  enabled  OK
        jupyterlab-topbar-extension v0.5.0  enabled  OK
        jupyterlab-topbar-text v0.5.1  enabled  OK
        jupyterlab_filetree v0.2.2  enabled  OK
        plotlywidget v4.8.2  enabled  OK
        run-tag-cells-jlab v0.1.3  enabled  OK

Uninstalled core extensions:
    @kiteco/jupyterlab-kite

- `jupyter serverextension list`
config dir: /Users/jacques/.jupyter
    jupyterlab_code_formatter  enabled 
    - Validating...
      jupyterlab_code_formatter  OK
    jupyter_kite disabled
    - Validating...
      jupyter_kite 0.2.1a0 OK
config dir: /Users/jacques/opt/anaconda3/envs/Data/etc/jupyter
    jupyter_kite  enabled 
    - Validating...
      jupyter_kite 0.2.1a0 OK
    jupyter_lsp  enabled 
    - Validating...
      jupyter_lsp 0.8.0 OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.2.0 OK

**Screenshots**
<img width="1588" alt="Capture d’écran 2020-07-15 à 18 11 06" src="https://user-images.githubusercontent.com/49912455/87568869-9db60f00-c6c6-11ea-9b45-fb525b36b056.png">

**Comment by jmarkow** [comment]
Same problem here.  

Output of  `pip freeze`

```
asn1crypto==1.3.0
attrs==19.3.0
backcall==0.1.0
bleach==3.1.5
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
colorama==0.4.3
conda==4.8.3
conda-package-handling==1.6.0
cryptography==2.8
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
gitdb==4.0.5
GitPython==3.1.3
idna==2.8
importlib-metadata==1.6.1
ipykernel==5.3.0
ipython==7.15.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==5.1.0
jedi==0.17.0
Jinja2==2.11.2
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.3
jupyter-conda==3.3.1
jupyter-core==4.6.3
jupyterlab==2.2.0
jupyterlab-code-formatter==1.3.4
jupyterlab-server==1.2.0
MarkupSafe==1.1.1
mistune==0.8.4
nb-conda-kernels==2.2.3
nbconvert==5.6.1
nbdime==2.0.0
nbformat==5.0.6
notebook==6.0.3
packaging==20.4
pandocfilters==1.4.2
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.8.0
prompt-toolkit==3.0.5
psutil==5.7.0
ptyprocess==0.6.0
pycosat==0.6.3
pycparser==2.19
Pygments==2.6.1
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyrsistent==0.16.0
PySocks==1.7.1
python-dateutil==2.8.1
pyzmq==19.0.1
requests==2.22.0
-e git+https://github.com/dattalab/reinforcement-analysis.git@1ddd5aa1d550fda8b164bf1a0e2397cef18bb6b8#egg=rl_analysis
ruamel-yaml==0.15.87
Send2Trash==1.5.0
six==1.14.0
smmap==3.0.4
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
tqdm==4.42.1
traitlets==4.3.3
urllib3==1.25.8
wcwidth==0.2.4
webencodings==0.5.1
widgetsnbextension==3.5.1
zipp==3.1.0
```

`jupyter labextension list`

```
JupyterLab v2.2.0
Known labextensions:
   app dir: /home/markowitzmeister_gmail_com/miniconda3/share/jupyter/lab
        @axlair/jupyterlab_vim v0.12.4  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.3.4  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK
```

`jupyter serverextension list`

```
config dir: /home/markowitzmeister_gmail_com/.jupyter
    jupyterlab_code_formatter  enabled
    - Validating...
      jupyterlab_code_formatter  OK
config dir: /home/markowitzmeister_gmail_com/miniconda3/etc/jupyter
    jupyter_conda  enabled
    - Validating...
      jupyter_conda 3.3.1 OK
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.2.0 OK
    nbdime  enabled
    - Validating...
      nbdime 2.0.0 OK
```

**Comment by Jacques2101** [comment]
I did what you previously recommended but this time it did not work. 
I downgraded Jupiter lab to previous version. 
Any idea to help me ? 
I will try again tomorrow

**Comment by cfenglv** [comment]
Same here. 
`Python = 3.8.3`
Output of `pip freeze`
```
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.12
anaconda-project==0.8.3
appdirs==1.4.3
applaunchservices==0.2.1
appnope==0.1.0
appscript @ file:///Users/runner/miniforge3/conda-bld/appscript_1594155689986/work
argh==0.26.2
asn1crypto @ file:///usr/local/miniconda/conda-bld/asn1crypto_1588618073851/work
astroid @ file:///Users/runner/miniforge3/conda-bld/astroid_1591645088120/work
astropy==4.0.1.post1
atomicwrites @ file:///home/conda/feedstock_root/build_artifacts/atomicwrites_1588182545583/work
attrs==19.3.0
autopep8 @ file:///home/conda/feedstock_root/build_artifacts/autopep8_1591017828430/work
Babel==2.8.0
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4 @ file:///Users/runner/miniforge3/conda-bld/beautifulsoup4_1589760920330/work
bitarray @ file:///Users/runner/miniforge3/conda-bld/bitarray_1594867924059/work
bkcharts==0.2
black==19.10b0
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1588608214987/work
bokeh @ file:///Users/runner/miniforge3/conda-bld/bokeh_1592869582615/work
boto==2.49.0
Bottleneck==1.3.2
brotlipy==0.7.0
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==7.1.2
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1593623337153/work
clyent==1.2.2
colorama==0.4.3
conda==4.8.3
conda-build==3.18.11
conda-package-handling==1.6.0
conda-verify==3.1.1
contextlib2==0.6.0.post1
cryptography==2.9.2
cycler==0.10.0
Cython @ file:///Users/runner/miniforge3/conda-bld/cython_1594253485594/work
cytoolz==0.10.1
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1593753420471/work
decorator==4.4.2
defusedxml==0.6.0
diff-match-patch @ file:///home/conda/feedstock_root/build_artifacts/diff-match-patch_1594679019945/work
distributed @ file:///Users/runner/miniforge3/conda-bld/distributed_1593754207100/work
docutils==0.16
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1589994591731/work
flake8 @ file:///home/conda/feedstock_root/build_artifacts/flake8_1594584774608/work
Flask==1.1.2
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1589989738418/work
future==0.18.2
gevent @ file:///Users/runner/miniforge3/conda-bld/gevent_1592657482386/work
glob2==0.7
gmpy2==2.1.0b1
greenlet @ file:///Users/runner/miniforge3/conda-bld/greenlet_1591368820148/work
h5py==2.10.0
HeapDict==1.0.1
html5lib @ file:///home/conda/feedstock_root/build_artifacts/html5lib_1592930327044/work
hypothesis @ file:///home/conda/feedstock_root/build_artifacts/hypothesis_1594812467655/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1593328102638/work
imagecodecs @ file:///Users/runner/miniforge3/conda-bld/imagecodecs_1593295488291/work
imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1594044661732/work
imagesize==1.2.0
importlib-metadata @ file:///Users/runner/miniforge3/conda-bld/importlib-metadata_1593211382425/work
intervaltree==3.0.2
ipykernel @ file:///Users/runner/miniforge3/conda-bld/ipykernel_1594210146077/work/dist/ipykernel-5.3.2-py3-none-any.whl
ipython @ file:///Users/runner/miniforge3/conda-bld/ipython_1593235464339/work
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi @ file:///Users/runner/miniforge3/conda-bld/jedi_1592619347183/work
Jinja2==2.11.2
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1593624380152/work
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1591810480056/work
jsonschema==3.2.0
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1594732094290/work
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyterlab==2.2.0
jupyterlab-code-formatter==1.3.4
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1593951277307/work
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
keyring @ file:///Users/runner/miniforge3/conda-bld/keyring_1588433943567/work
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
libarchive-c==2.9
lief==0.9.0
llvmlite==0.32.1
locket==0.2.0
lxml @ file:///Users/runner/miniforge3/conda-bld/lxml_1594322709119/work
MarkupSafe==1.1.1
matplotlib @ file:///Users/runner/miniforge3/conda-bld/matplotlib-base_1594091691585/work
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.1.0
mkl-random==1.1.0
mkl-service==2.3.0
mock @ file:///usr/local/miniconda/conda-bld/mock_1588618894844/work
more-itertools @ file:///home/conda/feedstock_root/build_artifacts/more-itertools_1592197792446/work
mpmath==1.1.0
msgpack==1.0.0
multipledispatch==0.6.0
mypy-extensions==0.4.3
navigator-updater==0.2.1
nbconvert==5.6.1
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1594060262917/work
networkx==2.4
nltk==3.4.4
nose==1.3.7
notebook @ file:///Users/runner/miniforge3/conda-bld/notebook_1594078855275/work
numba @ file:///Users/runner/miniforge3/conda-bld/numba_1590133716547/work
numexpr==2.7.1
numpy==1.19.0
numpydoc @ file:///home/conda/feedstock_root/build_artifacts/numpydoc_1593656006205/work
olefile==0.46
openpyxl @ file:///home/conda/feedstock_root/build_artifacts/openpyxl_1593690790606/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1589925210001/work
pandas @ file:///Users/runner/miniforge3/conda-bld/pandas_1592422011735/work
pandocfilters==1.4.2
parso==0.7.0
partd==1.1.0
path==13.1.0
pathlib2==2.3.5
pathspec==0.8.0
pathtools==0.1.2
patsy==0.5.1
pep8==1.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow @ file:///Users/runner/miniforge3/conda-bld/pillow_1594212124634/work
pkginfo==1.5.0.1
pluggy @ file:///Users/runner/miniforge3/conda-bld/pluggy_1592827481065/work
ply==3.11
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1590412252446/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1592500439797/work
psutil @ file:///Users/runner/miniforge3/conda-bld/psutil_1594826961980/work
ptyprocess==0.6.0
py @ file:///home/conda/feedstock_root/build_artifacts/py_1593088446458/work
pycodestyle @ file:///home/conda/feedstock_root/build_artifacts/pycodestyle_1589305246696/work
pycosat==0.6.3
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
pycurl==7.43.0.5
pydocstyle==5.0.2
pyflakes==2.2.0
Pygments==2.6.1
pylint @ file:///Users/runner/miniforge3/conda-bld/pylint_1592404315620/work
pyodbc==4.0.30
pyOpenSSL==19.1.0
pyparsing==2.4.7
PyQt5==5.12.3
PyQt5-sip==4.19.18
PyQtChart==5.12
PyQtWebEngine==5.12.1
pyrsistent==0.16.0
PySocks==1.7.1
pytest==5.4.3
pytest-arraydiff==0.3
pytest-astropy==0.7.0
pytest-astropy-header==0.1.2
pytest-doctestplus @ file:///home/conda/feedstock_root/build_artifacts/pytest-doctestplus_1591908454504/work
pytest-openfiles @ file:///home/conda/feedstock_root/build_artifacts/pytest-openfiles_1591909410901/work
pytest-remotedata==0.3.1
python-dateutil==2.8.1
python-jsonrpc-server @ file:///home/conda/feedstock_root/build_artifacts/python-jsonrpc-server_1588783985962/work
python-language-server @ file:///Users/runner/miniforge3/conda-bld/python-language-server_1593716049571/work
pytz==2020.1
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.1
QDarkStyle==2.8.1
QtAwesome @ file:///home/conda/feedstock_root/build_artifacts/qtawesome_1588715536397/work
qtconsole @ file:///home/conda/feedstock_root/build_artifacts/qtconsole_1592845750760/work
QtPy==1.9.0
regex @ file:///Users/runner/miniforge3/conda-bld/regex_1594799393427/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1592425495151/work
rope @ file:///home/conda/feedstock_root/build_artifacts/rope_1588950285934/work
Rtree==0.9.4
ruamel-yaml==0.15.80
scikit-image==0.17.2
scikit-learn @ file:///Users/runner/miniforge3/conda-bld/scikit-learn_1589920874237/work
scipy @ file:///opt/concourse/worker/volumes/live/4516624d-f3c2-4062-5777-50823951b448/volume/scipy_1593102189059/work
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-base_1591878760859/work
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
sip==4.19.23
six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
snowballstemmer==2.0.0
sortedcollections @ file:///home/conda/feedstock_root/build_artifacts/sortedcollections_1591583091437/work
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1591999956871/work
soupsieve @ file:///Users/runner/miniforge3/conda-bld/soupsieve_1589778516085/work
Sphinx @ file:///home/conda/feedstock_root/build_artifacts/sphinx_1593947940626/work
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sphinxcontrib-websupport @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-websupport_1593344032344/work
spyder @ file:///Users/runner/miniforge3/conda-bld/spyder_1594414179427/work
spyder-kernels @ file:///Users/runner/miniforge3/conda-bld/spyder-kernels_1594391924835/work
SQLAlchemy @ file:///Users/runner/miniforge3/conda-bld/sqlalchemy_1593116371673/work
statsmodels @ file:///Users/runner/miniforge3/conda-bld/statsmodels_1591963266538/work
sympy @ file:///Users/runner/miniforge3/conda-bld/sympy_1593716803428/work
tables==3.6.1
tblib==1.6.0
terminado==0.8.3
testpath==0.4.4
threadpoolctl @ file:///tmp/tmp79xdzxkt/threadpoolctl-2.1.0-py3-none-any.whl
tifffile @ file:///home/conda/feedstock_root/build_artifacts/tifffile_1593913740982/work
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1589469402899/work
toolz==0.10.0
tornado==6.0.4
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1593390011681/work
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1588470653596/work
ujson==1.35
unicodecsv==0.14.1
urllib3==1.25.9
watchdog @ file:///Users/runner/miniforge3/conda-bld/watchdog_1593120513999/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1592931742287/work
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension @ file:///Users/runner/miniforge3/conda-bld/widgetsnbextension_1594164367905/work
wrapt==1.11.2
wurlitzer==2.0.0
xlrd==1.2.0
XlsxWriter @ file:///home/conda/feedstock_root/build_artifacts/xlsxwriter_1590799523302/work
xlwings==0.19.5
xlwt==1.3.0
xmltodict==0.12.0
yapf==0.29.0
zict==2.0.0
zipp==3.1.0
zope.event @ file:///home/conda/feedstock_root/build_artifacts/zope.event_1591372894284/work
zope.interface==5.1.0
```

`jupyter labextension list`
```
JupyterLab v2.2.0
Known labextensions:
   app dir: /Users/cfenglv/opt/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.3.4  enabled  OK
        @ryantam626/jupyterlab_sublime v0.3.2  enabled  OK
```

`jupyter serverextension list`
```
config dir: /Users/cfenglv/.jupyter
    jupyterlab_code_formatter  enabled
    - Validating...
      jupyterlab_code_formatter  OK
config dir: /Users/cfenglv/opt/anaconda3/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.2.0 OK
```

Previously I update my python from 3.6 to 3.8 and find out all of my extension of Jupyter lab stop working. I completely delete my anaconda and reinstall it and everything else works properly except this one. I tried reinstall/delete build_json file. None of them work. 
The extension appears on advanced setting but nothing else appear.

**Comment by ryantam626** [comment]
Pretty sure it's an jupyterlab 2.2 issue as other people on #160 suggested. Will look this weekend

**Comment by ryantam626** [comment]
@Jacques2101 @jmarkow  @cfenglv 
the issue with JL 2.2.0 should be fixed with the latest release of the plugin, 1.3.5 (might need to wait a while for the conda forge bot to detect my changes and release though, alternatively just use pip)

**Comment by cfenglv** [comment]
@ryantam626 Thank you :D It's working fine after update to 1.3.5

**Comment by ryantam626** [comment]
Nice! Thanks for trying it out so quickly and confirming :pray:

**Comment by Jacques2101** [comment]
It's working fine. 
Thanks 👍🙏
