### ISSUE TITLE
Misleading 404 when isort or black are not installed

### ISSUE THREAD

**Issue by hhuuggoo** [ryantam626/jupyterlab_code_formatter#169]
This isn't really a bug - but I was setting up jupyterlab_code_formatter for a customer of ours and it took me a while to troubleshoot this, so I'm posting here:  Feel free to close/comment/etc.

At Saturn we deploy a jupyterhub like thing (via docker and kubernetes).  I setup jupyterlab_code_formatter in the container, but after loading a notebook, right clicking on a cell and clicking "format cell" resulted in a 404 on the server.  This is exact same 404 as is documented here:

https://jupyterlab-code-formatter.readthedocs.io/en/latest/faq.html#post-on-jupyterhub

But for a totally different reason.  The default jupyterlab_code_formatter includes `isort` and `black`.  In our case, `black` was installed but not `isort`.  The fix on our side is to either change the config to exclude `isort` or to install `isort.  We opted to include `isort`.

FWIW: The following would have helped me  
-  Addition to the FAQ documenting a lack of `black` or `isort` as another cause of the 404
-  Recommendation to install `isort` and `black` in order to use the library with default settings in the installation instructions
-  Server logs for the 404 that indicate what the cause is (I assumed it meant  - as it usually does - that there is no handler configured for the url pattern, caused by failing to register the server side application, however in this case it was caused by this line:https://github.com/ryantam626/jupyterlab_code_formatter/blob/master/serverextension/jupyterlab_code_formatter/handlers.py#L93).   I consider the message on that line to be clear enough - not sure why that wasn't visible in my logs or on the client.  in JupyterLab all I get is "Not Found"

**Comment by ryantam626** [comment]
Hey! Thanks for the feedback, I did include the a note in [here](https://jupyterlab-code-formatter.readthedocs.io/en/latest/installation.html#installation-step-1-installing-the-plugin-itself) - but agreed that it's a little confusing in your context..

I think I will just add to the FAQ as well.
