### ISSUE TITLE
Documentation about black cache cut-and-pastes wrong

### ISSUE THREAD

**Issue by hhuuggoo** [ryantam626/jupyterlab_code_formatter#170]
This line:
```
python -c “import black; black.CACHE_DIR.mkdir(parents=True, exist_ok=True)”
```
From https://jupyterlab-code-formatter.readthedocs.io/en/latest/faq.html#error-when-writing-grammar-tables

Cut and pastes in a way that cannot be executed because that code snippet is not embedded as code.  

It should be

```
python -c "import black; black.CACHE_DIR.mkdir(parents=True, exist_ok=True)"
```
Whatever double quotes come out of cut and pasting from the website are not valid python double quotes.

**Comment by ryantam626** [comment]
Hi! Thanks for reporting this, should be fixed now!
