### ISSUE TITLE
Error when formatting "!"

### ISSUE THREAD

**Issue by mlucool** [ryantam626/jupyterlab_code_formatter#173]
**Checklist prior to opening an issue**
- [ X ] I have followed fully the installation steps laid out in the documentation site.
- [ X ] I have restarted jupyterlab.
- [ X ] I have read the FAQ section in the documentation site.

**Describe the bug**
It tries to format the magic `!`, which leads to an error. It does not error with `%`.

Example:
```
!pwd
```

**Diagnostic commands**
Version: 1.3.5

**Screenshots**
![image](https://user-images.githubusercontent.com/1813603/96795756-84131a80-13cd-11eb-9637-fc3984c6a3e3.png)

**Additional context**
Proposal: we should not even try to format any line of code that starts with `!` in python. I.e.

```
print(   'hello world')
!pwd
print(       3  )
```
This would format the first and third lines, but not the second. This is consistent with what seems to happen today for `%`.

This formats as expected (the `%time` line is not touched):
```
print(   '1')
%time print(   3)
print(2)
```

**Comment by ryantam626** [comment]
Apologies for getting back to you late, I have fixed it now :+1:

**Comment by terasakisatoshi** [comment]
@ryantam626 

How about this case?

```
if True: # <-- python
    !pwd
```

causes an error:

```
Jupyterlab Code Formatter Error
Cannot parse: 2:4: !pwd
```

Also, the following case with space before `!`

```
 !pwd
```

causes `Cannot parse: 1:0: !pwd`
