### ISSUE TITLE
Formatter selection

### ISSUE THREAD

**Issue by flow2k** [ryantam626/jupyterlab_code_formatter#174]
I followed the User Guide's instructions to select the formatter, but it's not clear to me that this is read and actually taking effect.
```
    "preferences": {
        "default_formatter": {
            "python": "yapf"
        }
    }
```

How can I know for sure which formatter is being used? It seems `black` is still being used, but I can't confirm either way.

**Comment by flow2k** [comment]
Found that one way is to look in the Command Palette. I was still using the shortcut keys, which were assigned to the black formatter. Now, I have changed the shortcut to point to the desired YAPF formatter:

![image](https://user-images.githubusercontent.com/30223632/99182631-dd2f4f00-26ea-11eb-804e-cb74e3af8cd7.png)

If anyone has comments, let me know; otherwise, I'll close this in a few days.

**Comment by ryantam626** [comment]
Default formatters are only used by the following commands
`jupyterlab_code_formatter:format` and `jupyterlab_code_formatter:format_all`.

One would be interested in this under 2 different conditions,
1. Desire to format all cells at once easily
2. Desire to chain invokation of different formatters one after the other.

Doesn't look like you want to achieve any of those, so what you are using right now should suffice. I will update the docs to make it a bit more clear now.

**Comment by flow2k** [comment]
Thanks @ryantam626.
