### ISSUE TITLE
Support JupyterLab 3.0

### ISSUE THREAD

**Issue by dialvarezs** [ryantam626/jupyterlab_code_formatter#179]
JupyterLab 3.0 is out already with the new way to publish extensions. Maybe it could need a big rework?

https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html#v3-0

**Comment by ryantam626** [comment]
Yes, I will need to rework the entire extension, but I have other priorities at this very moment, perhaps in the new year.

**Comment by dialvarezs** [comment]
No worries, take your time. Have a nice holiday!
