### ISSUE TITLE
Weird `is jupyterlab_code_formatter importable?` warning

### ISSUE THREAD

**Issue by ryantam626** [ryantam626/jupyterlab_code_formatter#182]
![image](https://user-images.githubusercontent.com/8895126/103441124-afbf4600-4c43-11eb-9d52-f25966a3a1c1.png)

On a fresh venv
```
pip install jupyterlab
pip install black isort jupyterlab_code_formatter
<path to the correct jupyter> serverextension enable --py jupyterlab_code_formatter
```
yielded this.

Same happens in a fresh python3.6 docker image (just in case my python setup on my box is mesed up, as demonstrated by the need of using full path...)

The plugin still works, so it's not the end of the world..

**Comment by ryantam626** [comment]
@ianhi any ideas regarding this? Not really sure what's going on with this

Again huge thanks for laying the groundwork for JL 3 :pray:

**Comment by ianhi** [comment]
Oh that is weird. I saw that at some point when converting for jlab3 but at that point there were actually import errors so once I fixed them I didn't check anymore. 

This feels a little like a bug in the jlab3 serverextension command maybe?

**Comment by ryantam626** [comment]
Yeah super weird :thinking: I tested the same with `import jupyterlab_code_formatter` in that venv (/within docker), and obvserved the same result with no error.

Just gonna update the docs to say this might happen and it's safe to continue. Thanks again!

**Comment by ianhi** [comment]
I think that this is fixed by https://github.com/ryantam626/jupyterlab_code_formatter/pull/186

**Comment by ryantam626** [comment]
Yep, closing :+1:
