### ISSUE TITLE
Upload wheel to pypi?

### ISSUE THREAD

**Issue by ianhi** [ryantam626/jupyterlab_code_formatter#183]
**Describe the bug**

I just noticed that you only upload the sdist to pypi:
https://github.com/ryantam626/jupyterlab_code_formatter/blob/46d3acdb53845a2133119c22dc5f497a28a8f7c3/bin/publish.sh#L13-L14

Would you consider uploading a wheel as well?

**Comment by ryantam626** [comment]
Sure thing :+1:
