### ISSUE TITLE
jupyterlab ready ? 

### ISSUE THREAD

**Issue by Jacques2101** [ryantam626/jupyterlab_code_formatter#187]
Hi I have a simple question: is code_formatter ready for Jupyterlab 3 ? 
thx.

**Comment by ianhi** [comment]
Yup. `pip install --upgrade jupyterlab_code_formatter` should get you a version that works.

**Comment by ryantam626** [comment]
@ianhi is correct, feel free to open another issue if you see something wrong :+1:
