### ISSUE TITLE
Ignore cells of different languages

### ISSUE THREAD

**Issue by willprice** [ryantam626/jupyterlab_code_formatter#196]
**Describe the bug**
Running the formatter on a notebook containing a cell with a different language fails with a syntax error e.g.

```
%%html
<b>Hi</b>
````

Can the plugin check the first line of a notebook cell that it is going to format and skip those with `%%` prefixes as it will inevitably fail.

**Comment by ryantam626** [comment]
Hi! 1.4.4 should have this handled hopefully, mind having a go with that version?

**Comment by willprice** [comment]
Awesome! Thanks Ryan, I'll check it out later today or tomorrow and report back!

**Comment by willprice** [comment]
Sorry for such a late response, can confirm this is now working great. Thanks!
