### ISSUE TITLE
Feature request: Ignore (or optionally ignore) doc string requests

### ISSUE THREAD

**Issue by michaelaye** [ryantam626/jupyterlab_code_formatter#197]
Hi!
First, thanks again for your awesome package, i enjoy it so much that I recently went to auto-format when saving, but I met an issue with that.
Sometimes, when looking at a docstring (`obj?`) or at its code (`obj??`) I leave it open for longer to study elements of it.
With Jupyter auto-saving every 2 mins (which I think is a reasonable frequency), I would then get the "Not parseable" error messages, like this:
![image](https://user-images.githubusercontent.com/69774/109681463-b9c5ce00-7b3a-11eb-802e-0d37ebedcfbc.png)

How about ignoring any cell that has an object with a ? or ?? at the end? Those cells would interrupt the notebook compilation flow in any case, so it's legit to assume that this cell is okay for not being in a runnable state at the moment?

**Comment by ryantam626** [comment]
:+1: Will fix it this weekend

**Comment by ryantam626** [comment]
Sorry for the delay, something came up last weekend. Have published a new version which should fix the issue :D
