### ISSUE TITLE
code_formatter settings 

### ISSUE THREAD

**Issue by Jacques2101** [ryantam626/jupyterlab_code_formatter#198]
**Describe the bug**
Hi, I have code like that: 
```
# Importation de mes librairies
import sys
sys.path.append(
    "/Users/jacques/Library/Mobile Documents/com~apple~CloudDocs/Projets/MyFunction"
)
from MyFunction import export_data, read_data
```
but when I reformat these lines with code_formatter, it changes the code to: 
```
# Importation de mes librairies
from MyFunction import export_data, read_data
import sys
sys.path.append(
    "/Users/jacques/Library/Mobile Documents/com~apple~CloudDocs/Projets/MyFunction"
)
```
wich produces an error 

The settings are: 
```
{
    // Jupyterlab Code Formatter
    // @ryantam626/jupyterlab_code_formatter:settings
    // Jupyterlab Code Formatter settings.
    // **********************************************

    // Autopep8 Config
    // Config to be passed into autopep8's fix_code function call as the options dictionary.
    "autopep8": {},

    // Black Config
    // Config to be passed into black's format_str function call.
    "black": {
        "line_length": 88,
        "string_normalization": true
    },

    // Auto format config
    // Auto format code when save the notebook.
    "formatOnSave": false,

    // FormatR Config
    // Config to be passed into formatR's tidy_source function call.
    "formatR": {
        "indent": 2,
        "arrow": true,
        "wrap": true,
        "width_cutoff": 150
    },

    // Isort Config
    // Config to be passed into isort's SortImports function call.
    "isort": {
        "multi_line_output": 3,
        "include_trailing_comma": true,
        "force_grid_wrap": 0,
        "use_parentheses": true,
        "line_length": 88
    },

    // Code Formatter Preferences
    // Preferences for this plugin
    "preferences": {
        "default_formatter": {
            "python": [
                "isort",
                "black"
            ],
            "r": "formatR"
        }
    },

    // Styler Config
    // Config to be passed into styler's style_text function call.
    "styler": {},

    // YAPF Config
    // Config to be passed into yapf's FormatCode function call.
    "yapf": {
        "style_config": "google"
    }
}
```

and I had on the user preferences (left):
```
{
  "preferences": {
    "default_formatter": {
        "python": "autopep8"
    }
}, 
    "black": {
    "line_length": 120
},
    "isort": {
      "line_length": 120
    }
}
```

**Diagnostic commands**
Please attach the output of the following commands (please format them properly)

- `pip freeze`
anyio @ file:///Users/runner/miniforge3/conda-bld/anyio_1612745561342/work/dist
appdirs==1.4.4
appnope @ file:///opt/concourse/worker/volumes/live/5f13e5b3-5355-4541-5fc3-f08850c73cf9/volume/appnope_1606859448618/work
argon2-cffi @ file:///opt/concourse/worker/volumes/live/d733ceb5-7f19-407b-7da7-a386540ab855/volume/argon2-cffi_1613037492998/work
async-generator @ file:///home/ktietz/src/ci/async_generator_1611927993394/work
attrs @ file:///tmp/build/80754af9/attrs_1604765588209/work
autopep8 @ file:///tmp/build/80754af9/autopep8_1613246362269/work
Babel @ file:///tmp/build/80754af9/babel_1607110387436/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
black==19.10b0
bleach @ file:///tmp/build/80754af9/bleach_1612211392645/work
brotlipy==0.7.0
certifi==2020.12.5
cffi @ file:///opt/concourse/worker/volumes/live/0ef369cc-6ba0-47e7-75da-208c6400381d/volume/cffi_1613246948181/work
chardet @ file:///opt/concourse/worker/volumes/live/c798b2ee-88b1-4341-6830-161a92c2399e/volume/chardet_1607706832595/work
click==7.1.2
cryptography @ file:///Users/runner/miniforge3/conda-bld/cryptography_1612993961228/work
cycler==0.10.0
debugpy @ file:///Users/runner/miniforge3/conda-bld/debugpy_1610140307191/work
decorator @ file:///home/ktietz/src/ci/decorator_1611930055503/work
defusedxml @ file:///home/ktietz/src/ci_mi/defusedxml_1612808095953/work
entrypoints==0.3
gitdb==4.0.5
GitPython==3.1.13
idna @ file:///home/linux1/recipes/ci/idna_1610986105248/work
importlib-metadata @ file:///Users/runner/miniforge3/conda-bld/importlib-metadata_1610355190026/work
ipykernel @ file:///Users/runner/miniforge3/conda-bld/ipykernel_1607737244191/work/dist/ipykernel-5.4.2-py3-none-any.whl
ipympl @ file:///tmp/build/80754af9/ipympl_1613576981827/work
ipython @ file:///Users/runner/miniforge3/conda-bld/ipython_1612487013094/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1610481889018/work
isort @ file:///tmp/build/80754af9/isort_1612243941122/work
jedi @ file:///opt/concourse/worker/volumes/live/904d39c2-2f20-46c0-487d-9a3d2725434d/volume/jedi_1611333757211/work
Jinja2 @ file:///tmp/build/80754af9/jinja2_1612213139570/work
jlab-enhanced-cell-toolbar @ file:///home/conda/feedstock_root/build_artifacts/jlab-enhanced-cell-toolbar_1612726587989/work
json5==0.9.5
jsonschema @ file:///tmp/build/80754af9/jsonschema_1602607155483/work
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1610375432619/work
jupyter-core @ file:///opt/concourse/worker/volumes/live/c8df8dce-dbb3-46e7-649c-adf4ed2dd00a/volume/jupyter_core_1612213293829/work
jupyter-kite==2.0.2
jupyter-resource-usage==0.5.1
jupyter-server @ file:///Users/runner/miniforge3/conda-bld/jupyter_server_1613709410509/work
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1613618627584/work
jupyterlab-autoversion==0.3.0
jupyterlab-cell-flash==0.3.1
jupyterlab-code-formatter @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_code_formatter_1613228721743/work
jupyterlab-code-snippets==2.0.1
jupyterlab-execute-time @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_execute_time_1612635935592/work
jupyterlab-executor==2021.1.2
jupyterlab-kite==2.0.2
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-python-file @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab-python-file_1608159738510/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1613760084674/work
jupyterlab-system-monitor==0.8.0
jupyterlab-topbar==0.6.1
jupyterlab-widgets @ file:///tmp/build/80754af9/jupyterlab_widgets_1609884341231/work
kiwisolver @ file:///opt/concourse/worker/volumes/live/0b2f3e77-eaa3-4995-7dd0-c994762fcbde/volume/kiwisolver_1612282417472/work
MarkupSafe @ file:///opt/concourse/worker/volumes/live/cb778296-98db-45ad-411e-6f726e102dc3/volume/markupsafe_1594371638608/work
matplotlib @ file:///opt/concourse/worker/volumes/live/41e8cd50-031f-4dda-5787-dd3c4f4e0f08/volume/matplotlib-suite_1613407855571/work
mistune @ file:///opt/concourse/worker/volumes/live/95802d64-d39c-491b-74ce-b9326880ca54/volume/mistune_1594373201816/work
mypy-extensions==0.4.3
nbclassic @ file:///home/conda/feedstock_root/build_artifacts/nbclassic_1610352513187/work
nbclient @ file:///tmp/build/80754af9/nbclient_1614364831625/work
nbconvert @ file:///opt/concourse/worker/volumes/live/2b9c1d93-d0fd-432f-7d93-66c93d81b614/volume/nbconvert_1601914875037/work
nbformat @ file:///tmp/build/80754af9/nbformat_1610738111109/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1613680548246/work
nltk==3.5
notebook @ file:///opt/concourse/worker/volumes/live/3dabb203-f14a-45e7-71a3-bc9a024a5a67/volume/notebook_1611341008226/work
numpy @ file:///Users/runner/miniforge3/conda-bld/numpy_1612953032265/work
olefile==0.46
packaging @ file:///tmp/build/80754af9/packaging_1611952188834/work
pandocfilters @ file:///opt/concourse/worker/volumes/live/c330e404-216d-466b-5327-8ce8fe854d3a/volume/pandocfilters_1605120442288/work
parso @ file:///tmp/build/80754af9/parso_1607623074025/work
pathspec @ file:///home/conda/feedstock_root/build_artifacts/pathspec_1605120834673/work
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow @ file:///opt/concourse/worker/volumes/live/3fb18867-d509-48fe-7811-21829c4a0332/volume/pillow_1614711415908/work
prometheus-client @ file:///tmp/build/80754af9/prometheus_client_1606344362066/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1613068548426/work
psutil==5.8.0
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pycodestyle @ file:///home/ktietz/src/ci_mi/pycodestyle_1612807597675/work
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
Pygments @ file:///tmp/build/80754af9/pygments_1613849567472/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing @ file:///home/linux1/recipes/ci/pyparsing_1610983426697/work
pyrsistent @ file:///opt/concourse/worker/volumes/live/ff11f3f0-615b-4508-471d-4d9f19fa6657/volume/pyrsistent_1600141727281/work
PySocks @ file:///opt/concourse/worker/volumes/live/85a5b906-0e08-41d9-6f59-084cee4e9492/volume/pysocks_1594394636991/work
python-dateutil @ file:///home/ktietz/src/ci/python-dateutil_1611928101742/work
pytz @ file:///tmp/build/80754af9/pytz_1612215392582/work
pyzmq @ file:///Users/runner/miniforge3/conda-bld/pyzmq_1613478800885/work
regex==2020.7.14
requests @ file:///tmp/build/80754af9/requests_1608241421344/work
Send2Trash @ file:///tmp/build/80754af9/send2trash_1607525499227/work
six @ file:///opt/concourse/worker/volumes/live/5b31cb27-1e37-4ca5-6e9f-86246eb206d2/volume/six_1605205320872/work
smmap==3.0.5
sniffio @ file:///opt/concourse/worker/volumes/live/1faeb672-6d3f-4f1f-7861-294fcf282962/volume/sniffio_1614030462215/work
terminado==0.9.2
testpath @ file:///home/ktietz/src/ci/testpath_1611930608132/work
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
tornado @ file:///opt/concourse/worker/volumes/live/05341796-4198-4ded-4a9a-332fde3cdfd1/volume/tornado_1606942323372/work
tqdm==4.48.0
traitlets @ file:///home/ktietz/src/ci/traitlets_1611929699868/work
typed-ast @ file:///opt/concourse/worker/volumes/live/b635b0af-0037-435d-5a8b-38d096f36bbf/volume/typed-ast_1610484559102/work
typing-extensions @ file:///home/ktietz/src/ci_mi/typing_extensions_1612808209620/work
urllib3 @ file:///tmp/build/80754af9/urllib3_1611694770489/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
widgetsnbextension==3.5.1
zipp @ file:///tmp/build/80754af9/zipp_1604001098328/work

- `jupyter labextension list`
JupyterLab v3.0.8
/Users/jacques/opt/anaconda3/envs/jlb/share/jupyter/labextensions
        jupyterlab-code-snippets v2.0.1 enabled OK (python, code_snippet)
        jupyterlab-system-monitor v0.8.0 enabled OK (python, jupyterlab-system-monitor)
        jupyterlab-topbar-extension v0.6.1 enabled OK (python, jupyterlab-topbar)
        jupyter-matplotlib v0.8.3 enabled OK
        jupyterlab-python-file v0.5.2 enabled OK (python, jupyterlab-python-file)
        jupyterlab-execute-time v2.0.1 enabled OK (python, jupyterlab_execute_time)
        jupyterlab-cell-flash v0.3.1 enabled OK
        @jupyter-server/resource-usage v0.5.0 enabled OK (python, jupyter-resource-usage)
        @gavincyi/jupyterlab-executor v2021.1.2 enabled OK (python, jupyterlab_executor)
        @jlab-enhanced/cell-toolbar v3.1.0 enabled OK (python, jlab-enhanced-cell-toolbar)
        @ryantam626/jupyterlab_code_formatter v1.4.4 enabled OK (python, jupyterlab-code-formatter)
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
        @kiteco/jupyterlab-kite v2.0.2 enabled OK (python, jupyterlab_kite)

Other labextensions (built into JupyterLab)
   app dir: /Users/jacques/opt/anaconda3/envs/jlb/share/jupyter/lab
        jupyterlab-plotly v4.14.3 enabled OK
        jupyterlab-theme-toggle v0.6.1 enabled OK
        jupyterlab-topbar v0.6.0 enabled OK
        jupyterlab-topbar-text v0.6.1 enabled OK
        jupyterlab_autoversion v0.3.0 enabled OK
        plotlywidget v4.14.3 enabled OK

Uninstalled core extensions:
    jupyterlab-topbar-text
    jupyterlab_autoversion

- `jupyter serverextension list`
config dir: /Users/jacques/.jupyter
    jupyterlab_code_formatter  enabled 
    - Validating...
      jupyterlab_code_formatter 1.4.4 OK
    jupyterlab_autoversion.extension  enabled 
    - Validating...
      jupyterlab_autoversion.extension  OK
config dir: /Users/jacques/opt/anaconda3/envs/jlb/etc/jupyter
    jupyter_resource_usage  enabled 
    - Validating...
      jupyter_resource_usage  OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 3.0.8 OK
    jupyterlab_autoversion  enabled 
    - Validating...
      jupyterlab_autoversion 0.3.0 OK
    jupyterlab_code_formatter  enabled 
    - Validating...
      jupyterlab_code_formatter 1.4.4 OK

**Comment by ryantam626** [comment]
I don't think it's a bug in this plugin? It's about what formatter you are using and its configuration.

In this case, you can either split it into 2 cells or just add `# noqa` at the correct lines to prevent autopep8 from formatting it.

**Comment by Jacques2101** [comment]
I tried to split the code in an other cell but same result   

What do you mean with # noqa ??? 

Moreover how is it possible to increase the size of one line ? 

thx.

**Comment by ryantam626** [comment]
I can't reproduce what you are seeing when splitting it into two cells like so
![Selection_299](https://user-images.githubusercontent.com/8895126/109834952-a26e0a00-7c3a-11eb-9778-2ab45f1d5c2e.png)

By `# noqa `, I mean this
![Selection_300](https://user-images.githubusercontent.com/8895126/109835132-d5b09900-7c3a-11eb-8478-9089c7124439.png)
it's a pretty common comment that some formatter respects, in this case the formatter that you are using - `autopep8`.

**Comment by Jacques2101** [comment]
`# nova`  works fine. Thx. 

and my last question: how is it possible to increase the size of one line ?

**Comment by ryantam626** [comment]
```
{
  "preferences": {
    "default_formatter": {
        "python": "autopep8"
    }
}, 
    "black": {
    "line_length": 120
},
    "isort": {
      "line_length": 120
    },
    "autopep8": {
      "max_line_length": 120
    }
}
```

**Comment by Jacques2101** [comment]
thx.
