### ISSUE TITLE
Unable to disable formatting for R when using with Python

### ISSUE THREAD

**Issue by jayqi** [ryantam626/jupyterlab_code_formatter#199]
**Checklist prior to opening an issue**
- [X] I have followed fully the installation steps laid out in the documentation site.
- [X] I have restarted jupyterlab.
- [X] I have read the FAQ section in the documentation site.

**Describe the bug**

Unable to disable formatting for R when using for just Python with `"formatOnSave": true`.

I have a project with both Python and R notebooks, and I want to try using this extension for just formatting my Python notebooks, with automatic formatting on save. Unfortunately, I haven't figured out how to configure the default formatter for R in order for it to do nothing and not error. This is really annoying as it will open an error alert every time I save an R notebook.

If I have `"r"` set to a real formatter like `"styler"`, I get the error `Formatter styler not found!`. I don't want to install additional dependencies like `styler` in my environment if I'm not planning to use them.

I've also tried all of the following:

- leave the key `"r"` out of `preferences.default_formatter`
- set `preferences.default_formatter.r` to `null`
- set `preferences.default_formatter.r` to an empty array `[]`

In each of those cases, I get the error: `Unable to find default formatters to use, please file an issue on GitHub.`

Here is my full user settings for one iteration of what I've tried. 

```
{
    "black": {
        "line_length": 80,
        "string_normalization": true
    },
    "preferences": {
        "default_formatter": {
            "python": [
                "black"
            ],
            "r": []
        }
    },
    "formatOnSave": true
}
```

```
jupyterlab                3.0.9              pyhd8ed1ab_0    conda-forge
jupyterlab_code_formatter 1.4.4              pyhd8ed1ab_0    conda-forge
```

**Comment by ryantam626** [comment]
Hi! Will fix this shortly.

**Comment by ryantam626** [comment]
1.4.6 is now released. You should be able to use `skip` or `noop` to skip applying any formatters in any language.

**Comment by jayqi** [comment]
Just tried it with `jupyterlab_code_formatter 1.4.7` from conda-forge and worked as advertised. Thanks!
