### ISSUE TITLE
"This extension does not yet support the current version of JupyterLab."

### ISSUE THREAD

**Issue by KevinMMendez** [ryantam626/jupyterlab_code_formatter#2]
I've just updated to Version 0.35.0 of JupyterLab on MacOS.

ValueError: This extension does not yet support the current version of JupyterLab. 
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=0.17.0 <0.19.0 @jupyterlab/application
>=0.19.1 <0.20.0        >=0.17.0 <0.19.0 @jupyterlab/notebook

**Comment by ryantam626** [comment]
Hi! Thanks for flagging! Have published a new version to allow for this, could you please check if it works for you too?

**Comment by ryantam626** [comment]
Closing this for now, please reopen if it does work :+1:
