### ISSUE TITLE
format option is not in commad pallet and not shown at all

### ISSUE THREAD

**Issue by metya** [ryantam626/jupyterlab_code_formatter#20]
Regarding this [issue](https://github.com/ryantam626/jupyterlab_code_formatter/issues/6), I have the same problem, but my `jupyter serverextension list` is ok and I have installed `jupyter_lab_formatter`

So what may it be a problem?

```
λ jupyter serverextension list
config dir: C:\Users\metya\.jupyter
    jupyter_tensorboard enabled
    - Validating...
      jupyter_tensorboard 0.1.8 ok
    nbresuse enabled
    - Validating...
      nbresuse  ok
    jupyterlab_git enabled
    - Validating...
      jupyterlab_git  ok
    jupyterlab_code_formatter enabled
    - Validating...
      jupyterlab_code_formatter  ok
config dir: C:\ProgramData\Anaconda3\etc\jupyter
    jupyterlab enabled
    - Validating...
      jupyterlab 0.35.4 ok
    jupyterlab_github enabled
    - Validating...
      jupyterlab_github 0.7.0 ok
    nbresuse enabled
    - Validating...
      nbresuse  ok
    nbextensions disabled
    - Validating...
Error loading server extension nbextensions
      X is nbextensions importable?
```

```
λ jupyter labextension list
JupyterLab v0.35.4
Known labextensions:
   app dir: C:\ProgramData\Anaconda3\share\jupyter\lab
        @deathbeds/jupyterlab_graphviz v0.1.1 enabled  ok
        @ijmbarr/jupyterlab_spellchecker v0.1.4 enabled  ok
        @jupyter-widgets/jupyterlab-manager v0.38.1 enabled  ok
        @jupyterlab/celltags v0.1.4 enabled  ok
        @jupyterlab/geojson-extension v0.18.1 enabled  ok
        @jupyterlab/git v0.4.2 enabled  ok
        @jupyterlab/github v0.10.0 enabled  ok
        @jupyterlab/google-drive v0.16.0 enabled  ok
        @jupyterlab/katex-extension v0.20.0 enabled  ok
        @jupyterlab/latex v0.6.1 enabled  ok
        @jupyterlab/plotly-extension v0.18.1 enabled  ok
        @jupyterlab/statusbar v0.5.0 enabled  ok
        @jupyterlab/toc v0.6.0 enabled  ok
        @krassowski/jupyterlab_go_to_definition v0.1.6 enabled  ok
        @lckr/jupyterlab_variableinspector v0.1.0 enabled  ok
        @mflevine/jupyterlab_html v0.1.4 enabled  ok
        @ryantam626/jupyterlab_code_formatter v0.2.0 enabled  ok
        jupyter-gmaps v0.8.2 enabled  ok
        jupyterlab-chart-editor v1.0.0 enabled  ok
        jupyterlab-jupytext v0.1.0-dev enabled  ok
        jupyterlab_bokeh v0.6.3 enabled  ok
        jupyterlab_nbmetadata v0.1.0 enabled  ok
        jupyterlab_tensorboard v0.1.5 enabled  ok

```

**Comment by ryantam626** [comment]
hmm did you install one of the formatter?

Can check via `pip freeze`

**Comment by ryantam626** [comment]
Hmm that's weird, is there anything interesting in your broswer console or the terminal that launched jupyter lab?

**Comment by metya** [comment]
not at all. 
it is windows 10 with conda installation on regular chrome browser. 

my work terminal is cmder, but inside it is regular cmd with some useful srcipts like ls and other well known tools.

**Comment by metya** [comment]
Ok! 

In terminal I didn't notice any of unusual activity, but in chrome browser I found that

```
Hello! JupyterLab extension jupyterlab_code_formatter is activated!
index.js:16 Uncaught (in promise) Error: <!DOCTYPE HTML>
<html>

<head>
    <meta charset="utf-8">

    <title>Jupyter Notebook</title>
    <link id="favicon" rel="shortcut icon" type="image/x-icon" href="/static/base/images/favicon.ico?v=97c6417ed01bdc0ae3ef32ae4894fd03">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=3c2a865c832a1322285c55c6ed99abb2" type="text/css" />
    <link rel="stylesheet" href="/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    

    <link rel="stylesheet" href="/static/style/style.min.css?v=56cad67b8b1ff3ed9b48850e9efcffb3" type="text/css"/>
    
<style type="text/css">
/* disable initial hide */
div#header, div#site {
    display: block;
}
</style>

    <link rel="stylesheet" href="/custom/custom.css" type="text/css" />
    <script src="/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe" type="text/javascript" charset="utf-8"></script>
    <script src="/static/components/preact/index.js?v=00a2fac73c670ce39ac53d26640eb542" type="text/javascript"></script>
    <script src="/static/components/proptypes/index.js?v=c40890eb04df9811fcc4d47e53a29604" type="text/javascript"></script>
    <script src="/static/components/preact-compat/index.js?v=aea8f6660e54b18ace8d84a9b9654c1c" type="text/javascript"></script>
    <script src="/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f" type="text/javascript" charset="utf-8"></script>
    <script>
      require.config({
          
          urlArgs: "v=20190415164540",
          
          baseUrl: '/static/',
          paths: {
            'auth/js/main': 'auth/js/main.min',
            custom : '/custom',
            nbextensions : '/nbextensions',
            kernelspecs : '/kernelspecs',
            underscore : 'components/underscore/underscore-min',
            backbone : 'components/backbone/backbone-min',
            jed: 'components/jed/jed',
            jquery: 'components/jquery/jquery.min',
            json: 'components/requirejs-plugins/src/json',
            text: 'components/requirejs-text/text',
            bootstrap: 'components/bootstrap/dist/js/bootstrap.min',
            bootstraptour: 'components/bootstrap-tour/build/js/bootstrap-tour.min',
            'jquery-ui': 'components/jquery-ui/jquery-ui.min',
            moment: 'components/moment/min/moment-with-locales',
            codemirror: 'components/codemirror',
            termjs: 'components/xterm.js/xterm',
            typeahead: 'components/jquery-typeahead/dist/jquery.typeahead.min',
          },
          map: { // for backward compatibility
              "*": {
                  "jqueryui": "jquery-ui",
              }
          },
          shim: {
            typeahead: {
              deps: ["jquery"],
              exports: "typeahead"
            },
            underscore: {
              exports: '_'
            },
            backbone: {
              deps: ["underscore", "jquery"],
              exports: "Backbone"
            },
            bootstrap: {
              deps: ["jquery"],
              exports: "bootstrap"
            },
            bootstraptour: {
              deps: ["bootstrap"],
              exports: "Tour"
            },
            "jquery-ui": {
              deps: ["jquery"],
              exports: "$"
            }
          },
          waitSeconds: 30,
      });

      require.config({
          map: {
              '*':{
                'contents': 'services/contents',
              }
          }
      });

      // error-catching custom.js shim.
      define("custom", function (require, exports, module) {
          try {
              var custom = require('custom/custom');
              console.debug('loaded custom.js');
              return custom;
          } catch (e) {
              console.error("error loading custom.js", e);
              return {};
          }
      })

    document.nbjs_translations = {"domain": "nbjs", "locale_data": {"nbjs": {"": {"domain": "nbjs"}}}};
    document.documentElement.lang = navigator.language.toLowerCase();
    </script>

    
    

</head>

<body class=""
 
  
 
dir="ltr">

<noscript>
    <div id='noscript'>
      Jupyter Notebook requires JavaScript.<br>
      Please enable it to proceed. 
  </div>
</noscript>

<div id="header">
  <div id="header-container" class="container">
  <div id="ipython_notebook" class="nav navbar-brand"><a href="/lab" title='dashboard'>
      <img src='/static/base/images/logo.png?v=641991992878ee24c6f3826e81054a0f' alt='Jupyter Notebook'/>
  </a></div>

  
  
  
  
  
  


  
  
  </div>
  <div class="header-bar"></div>

  
  
</div>

<div id="site">


<div class="error">
    
    <h1>404 : Not Found</h1>
    
    
<p>You are requesting a page that does not exist!</p>

</div>


</div>







<script type='text/javascript'>
require(['jquery'], function($) {
  // scroll long tracebacks to the bottom
  var tb = $(".traceback")[0];
  tb.scrollTop = tb.scrollHeight;
});
</script>


<script type='text/javascript'>
  function _remove_token_from_url() {
    if (window.location.search.length <= 1) {
      return;
    }
    var search_parameters = window.location.search.slice(1).split('&');
    for (var i = 0; i < search_parameters.length; i++) {
      if (search_parameters[i].split('=')[0] === 'token') {
        // remote token from search parameters
        search_parameters.splice(i, 1);
        var new_search = '';
        if (search_parameters.length) {
          new_search = '?' + search_parameters.join('&');
        }
        var new_url = window.location.origin + 
                      window.location.pathname + 
                      new_search + 
                      window.location.hash;
        window.history.replaceState({}, "", new_url);
        return;
      }
    }
  }
  _remove_token_from_url();
</script>
</body>

</html>
    at index.js:16
```

**Comment by ryantam626** [comment]
Interesting! Could you hop over to the network tab and see if you can find a `formatters` call, the url should be something like `http://localhost:8888/jupyterlab_code_formatter/formatters?1555497673978`

**Comment by metya** [comment]
Yes. If I refresh page and see the console log, I see seems call.

In network tab I see that call too.

<details><summary>Pics</summary>

![изображение](https://user-images.githubusercontent.com/968934/56283173-9bf34980-6119-11e9-9b49-50281d5d13d9.png)

![изображение](https://user-images.githubusercontent.com/968934/56283187-a9103880-6119-11e9-80d4-880d8947bbd7.png)

![изображение](https://user-images.githubusercontent.com/968934/56283237-ca712480-6119-11e9-9b49-68e213c974a7.png)
</details>

**Comment by ryantam626** [comment]
Okay excellent, we have narrowed down the issue! It would seem that the server extension is not working properly. 

What's the python version you are using? (the python that you use to launch jupyter lab, not the kernel within jupyter lab)

**Comment by metya** [comment]
I'm using python 3.7.3 now. Jupyter lab version v0.34.5

**Comment by metya** [comment]
Maybe I need reinstall all over, and the extension and the server extension?

**Comment by ryantam626** [comment]
Yeah that's what I was gonna suggest too :disappointed: 

No issue with python3.7.3 I can think of..

And I thought there might be something wrong with Windows in conjunction with the underlying server (Torando) that jupyter lab uses, but it has hit the server itself (since the header says Torando), so I am out of ideas atm..

**Comment by metya** [comment]
Ok, I will do reinstall and come back here.

**Comment by metya** [comment]
I reinstalled lab extension and python server and nothing changes. 

Maybe problem in tornado which version v6.0.2?

**Comment by ryantam626** [comment]
It's possible.. I will try to replicate this over the weekends

**Comment by sho-87** [comment]
I'm getting the exact same error. Python 3.6.6, Jupyterlab 0.35, Black 18.9, Windows 10

**Comment by ryantam626** [comment]
Hey, sorry for the delay. Unfortunately I can't reproduce this on my Windows 10 machine, I installed miniconda from scratch and a minimal jupyterlab, and it worked as expected.

NodeJS v10.13.0
Python3.7.3
with
Tornado v6.0.2
Black 19.3b0
Juypterlab 0.35.5

All I know is that the server extension is not working as intended, but yeah.. can't really debug this with my machine :(

**Comment by TimDumol** [comment]
FWIW, I experienced the same issue, only to find out that while I had installed the labextension and the serverextension, I forgot to actually install the package (`pip install jupyterlab_code_formatter`). Doing that and then restarting the server fixed my problem.

**Comment by sho-87** [comment]
oh wow I should learn to read instructions better - I'm so used to just installing lab extensions. after installing the package the formatter works fine

just wondering what the package is for? is there no way to roll everything into a single lab extension?

**Comment by ryantam626** [comment]
> oh wow I should learn to read instructions better - I'm so used to just installing lab extensions. after installing the package the formatter works fine
> 
> just wondering what the package is for? is there no way to roll everything into a single lab extension?

The package provides server extension, which is used for actually running the code for formatting and for determining the existence of formatters.

There is a way to roll everything into a single lab extension, making the running kernel run the `format_str` (or other equivalent formatting functions) would be one way, but I don't really like my notebook to have skipping exec count so I didn't go for that :see_no_evil:

**Comment by haakenlid** [comment]
I had the same problem, with a 404 response from `http://localhost:8888/jupyterlab_code_formatter/formatters?...`

What happened was that I had run the `jupter serverextension enable` command as the root user (in a docker build), but was running jupyterlab as non-root.

    jupyter serverextension enable --py jupyterlab_code_formatter

When I run both jupyter serverextension and jupyter lab with the same user, the extension works.

**Comment by ryantam626** [comment]
Haven't heard back in a while, gonna assume it's solved. Please re-open if it hasn't :+1:

**Comment by persas** [comment]
I've the same problem... I've installed it on a python 3 virtualenv and it is not showing anything... However when I call the url you provide I've get the correct output:

![image](https://user-images.githubusercontent.com/23346350/60332529-5237a280-9997-11e9-91c6-9fbf93bf326a.png)

Any solution over here??

**Comment by emigre459** [comment]
FWIW, I also didn't notice that I needed to do `conda install jupyterlab_code_formatter` in addition to the typical labextension install approach. +1 for rolling it all into a single lab extension, since we clearly are all quite bad at reading a full four lines of instructions...

**Comment by ryantam626** [comment]
@persas hey sorry missed your comment, if you are seeing that in the url, that means you have installed the server extension correctly. Could you confirm that you have installed the labextension correctly too?
`jupyter labextension list` in the correct virtualenv should tell you that.

**Comment by ryantam626** [comment]
> FWIW, I also didn't notice that I needed to do `conda install jupyterlab_code_formatter` in addition to the typical labextension install approach. +1 for rolling it all into a single lab extension, since we clearly are all quite bad at reading a full four lines of instructions...

Heh it happens to us all :smile: 

If I am understanding the conda recipe correctly, `conda install jupyterlab_code_formatter` actually runs both the server extension install and lab extension install for you, c.f. [here](https://github.com/conda-forge/jupyterlab_code_formatter-feedstock/blob/master/recipe/build.sh)

**Comment by persas** [comment]
I have installed everything... Now I'm trying with a Conda environment.

When I check the `jupyter labextension list` I got the following:

<img width="515" alt="image" src="https://user-images.githubusercontent.com/23346350/60398571-316b7a80-9b5a-11e9-8281-28f0a37f2dad.png">

When I'm going to the settings panel it seems to be installed: 
<img width="203" alt="image" src="https://user-images.githubusercontent.com/23346350/60398576-4d6f1c00-9b5a-11e9-907d-f103406c5c80.png">

But when I'm going to use it it does not appear in the pallette:
<img width="239" alt="image" src="https://user-images.githubusercontent.com/23346350/60398595-7099cb80-9b5a-11e9-80ab-977ec4012cc4.png">

Note that I've already installed the black and autopep8

**Comment by Gkchandora** [comment]
I also have the same issue as given by Mr. Peras. 
Any solution over here.

**Comment by ryantam626** [comment]
Unfortunately I am unable to reproduce this error...

I have a few guesses what could be wrong:
1. Somehow you have installed the server extension and lab extension on different jupyterlab installation (unlikely)
2. Some sort of network issue

Is there anything in your web browser console log?

**Comment by Gkchandora** [comment]
@ryantam626 The issue is solved now (by reinstallation of extension) and the problem is no more. Thanks for being active and for your time.
