### ISSUE TITLE
Question: if I use 'black', must it be in my venv?

### ISSUE THREAD

**Issue by dycw** [ryantam626/jupyterlab_code_formatter#200]
Is it possible to use a system-wide `black` that I've installed?

Concretely, I use [`pipx`](https://github.com/pipxproject/pipx) to install `black` (and other things), and it chooses to make `black` available as `~/.local/bin/black`. Of course, this is already in my `$PATH`.

**Comment by ryantam626** [comment]
Unfortunately yes, `black` must be importable inside the venv through whatever means for this to work (i.e. installed within venv or venv with `system-site-packages`)

**Comment by dycw** [comment]
Thanks for confirming!
