### ISSUE TITLE
Comments containing '?' are continuously shifted to the right if occurring in function body 

### ISSUE THREAD

**Issue by lemontheme** [ryantam626/jupyterlab_code_formatter#204]
**Checklist prior to opening an issue**
- [x] I have followed fully the installation steps laid out in the documentation site.
- [x] I have restarted jupyterlab.
- [x] I have read the FAQ section in the documentation site.

**Describe the bug**

Python comments occurring in the body of a function definition are indented further with each formatting run using Black. This happens only when the comment contains a question mark `?`. I'll include a couple of screenshots below.

I've reinstalled the plugin in a clean conda environment. No other extensions are enabled. I've tested using both Python 3.8.8 and Python 3.9.2. Same result. The problem doesn't seem to be due to Black, which manages to format the same piece of code correctly when it's passed in as a Python module. 

**Diagnostic commands**

- `pip freeze`

```
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1612459636436/work
pandocfilters==1.4.2
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1607618318316/work
pathspec @ file:///home/conda/feedstock_root/build_artifacts/pathspec_1605120834673/work
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1602535608087/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1605543085815/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1616432837031/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1615243893546/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1608055815057/work
pyparsing==2.4.7
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1610146801554/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1610291451001/work
python-dateutil==2.8.1
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1612179539967/work
pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1614611691549/work
regex @ file:///home/conda/feedstock_root/build_artifacts/regex_1616104404007/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1608156231189/work
Send2Trash==1.5.0
six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1610318319523/work
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1617048651963/work
testpath==0.4.4
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1610094708661/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1602771532708/work
typed-ast @ file:///home/conda/feedstock_root/build_artifacts/typed-ast_1609539256914/work
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1602702424206/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1615828766818/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
webencodings==0.5.1
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1614945704755/work
```

- `jupyter labextension list`

```
JupyterLab v3.0.12
/home/adriaan/miniforge3/envs/jupyter/share/jupyter/labextensions
        @ryantam626/jupyterlab_code_formatter v1.4.5 enabled OK (python, jupyterlab-code-formatter)
```

- `jupyter serverextension list`

```
config dir: /home/{me}/miniforge3/envs/jupyter/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 3.0.12 OK
    jupyterlab_code_formatter  enabled
    - Validating...
      jupyterlab_code_formatter 1.4.5 OK
```

**Screenshots**

Before formatting:

<img width="870" alt="Screen Shot 2021-03-30 at 19 55 37" src="https://user-images.githubusercontent.com/15968876/113035930-f4e80b00-9193-11eb-8733-34bcc9e512ce.png">

After:

<img width="862" alt="Screen Shot 2021-03-30 at 19 55 45" src="https://user-images.githubusercontent.com/15968876/113035954-faddec00-9193-11eb-8c0c-e3ce96d0376b.png">

Additional runs shift the comment further and further to the right.

**Comment by y1zhou** [comment]
I ran into a similar issue, and I don't think it's limited to comments with `?`. Consider the following example:

```python
def test_func():
    x = "?"
    return x
```

On formatting the cell, the `x = "?"` line would be indented to the right. Formatting multiple times would also continuously shift it further.

**Comment by ryantam626** [comment]
Yep, that's exactly it @y1zhou, will fix it

**Comment by y1zhou** [comment]
@ryantam626 Thanks! Feels like changing the first regex to `(^\s*(?!#)(.*)\?\??)$` should do the trick, but I'm not sure if there's any other edge cases.

**Comment by ryantam626** [comment]
Would break with 
```
def f():
    # test?
    print('hi")
```
I think?

Gonna go with `(^\s*[^#]*\?\??)` in the meantime

**Comment by ryantam626** [comment]
1.4.6 is now released and should have the issue fixed.

**Comment by y1zhou** [comment]
> Gonna go with `(^\s*[^#]*\?\??)` in the meantime

This would still break with the `x = "?"` case, right? Feels like the regex should test if the question mark is at the end, i.e. `(^\s*[^#]*\?\??)$`

**Comment by ryantam626** [comment]
Doh, you are absolutely right @y1zhou

**Comment by ryantam626** [comment]
1.4.8 is now released with `(^(?!\s*#)(.*)\?\??)$` which hopefully does the job correctly..

**Comment by y1zhou** [comment]
> 1.4.8 is now released with `(^(?!\s*#)(.*)\?\??)$` which hopefully does the job correctly..

Works great for me. Thanks for the quick fix!

**Comment by lemontheme** [comment]
Just took the new release out for a spin. Can confirm: it works just as you'd expect now. Really great to see stuff like this get patched so quickly. Thanks!

The conversation here has given me a bit more insight into how the extension works. Next issue I encounter, I'll try to PR a fix myself.

**Comment by jcoleman42** [comment]
I know this issue is closed, but I'm still seeing this problem in version 1.4.10, however a bit more restricted.  When a comment ends with a question mark, problems occur.  

As an example, this code causes the extra indenting, 
```python
def f(x, y):
    z = x + y # a comment that ends with ?
    return z
``` 

And this code, which is valid python, gives an error message
```python
def f(x, y):
    z = x + y # a comment that ends with ?
```
![image](https://user-images.githubusercontent.com/52928199/152884277-8bbe823e-8f88-4524-a871-c0f8206e36ed.png)
