### ISSUE TITLE
Cannot find server plugin version

### ISSUE THREAD

**Issue by diogomrks** [ryantam626/jupyterlab_code_formatter#214]
I just installed the package and I'm getting this error
![image](https://user-images.githubusercontent.com/49679212/121820651-f0f46100-cc8b-11eb-8cc4-3325243c556d.png)

And when I tried to enable the extension manually 
![image](https://user-images.githubusercontent.com/49679212/121820703-344ecf80-cc8c-11eb-9628-dc73a37fc656.png)

This is my pip list

Package                   Version  Location  
------------------------- -------- ----------
anyio                     2.2.0    
appdirs                   1.4.4    
argon2-cffi               20.1.0   
astroid                   2.5.6    
async-generator           1.10     
attrs                     19.1.0   
autopep8                  1.5.7    
Babel                     2.9.1    
backcall                  0.2.0    
black                     21.6b0   
bleach                    3.1.0    
cdsw                      1.0.0    
cffi                      1.14.5   
cfgv                      3.2.0    
click                     8.0.1    
colorama                  0.4.4    
contextvars               2.4      
coverage                  4.5.4    
cycler                    0.10.0   
Cython                    0.25.2   
dataclasses               0.8      
de-utils                  0.0.1    /home/cdsw
debugpy                   1.3.0    
decorator                 4.4.0    
defusedxml                0.6.0    
distlib                   0.3.1    
entrypoints               0.3      
filelock                  3.0.12   
flake8                    3.9.2    
Flask                     0.12     
futures                   2.1.4    
gitdb                     4.0.7    
GitPython                 3.1.17   
identify                  2.2.4    
idna                      3.1      
immutables                0.15     
importlib-metadata        4.0.1    
importlib-resources       5.1.3    
ipykernel                 5.1.1    
ipython                   7.16.1   
ipython-genutils          0.2.0    
ipywidgets                7.4.2    
isort                     5.8.0    
itsdangerous              1.1.0    
jedi                      0.17.2   
Jinja2                    2.10.1   
json5                     0.9.5    
jsonschema                3.0.1    
jupyter                   1.0.0    
jupyter-client            6.2.0    
jupyter-console           6.0.0    
jupyter-core              4.7.1    
jupyter-lsp               1.3.0    
jupyter-server            1.7.0    
jupyter-server-mathjax    0.2.2    
jupyterlab                3.0.16   
jupyterlab-code-formatter 1.4.10   
jupyterlab-git            0.30.1   
jupyterlab-lsp            3.7.0    
jupyterlab-python-file    0.5.2    
jupyterlab-server         2.5.1    
kudu-python               1.2.0    
lazy-object-proxy         1.6.0    
MarkupSafe                1.1.1    
matplotlib                2.0.0    
mccabe                    0.6.1    
mistune                   0.8.4    
more-itertools            8.7.0    
mypy-extensions           0.4.3    
nbclassic                 0.2.8    
nbconvert                 5.5.0    
nbdime                    3.0.0    
nbformat                  4.4.0    
nest-asyncio              1.5.1    
nodeenv                   1.6.0    
notebook                  5.7.8    
numpy                     1.13.3   
packaging                 20.9     
pandas                    0.20.1   
pandas-datareader         0.2.1    
pandocfilters             1.4.2    
parso                     0.7.1    
pathspec                  0.8.1    
pexpect                   4.7.0    
pickleshare               0.7.5    
pip                       19.1.1   
pluggy                    0.13.1   
pre-commit                2.12.1   
prometheus-client         0.7.1    
prompt-toolkit            3.0.18   
ptyprocess                0.6.0    
py                        1.10.0   
py4j                      0.10.7   
pycodestyle               2.7.0    
pycparser                 2.20     
pydocstyle                6.0.0    
pyflakes                  2.3.1    
Pygments                  2.4.2    
pylint                    2.8.3    
pyls-black                0.4.7    
pyparsing                 2.4.0    
pyrsistent                0.15.2   
pytest                    5.4.3    
python-dateutil           2.8.0    
python-jsonrpc-server     0.4.0    
python-lsp-jsonrpc        1.0.0    
python-lsp-server         1.0.1    
pytz                      2019.1   
PyYAML                    5.4.1    
pyzmq                     18.0.2   
qtconsole                 4.5.1    
regex                     2021.4.4 
requests                  2.13.0   
requests-file             1.4.3    
rope                      0.19.0   
scipy                     1.3.0    
seaborn                   0.8      
Send2Trash                1.5.0    
setuptools                57.0.0   
simplegeneric             0.8.1    
simplejson                3.10.0   
six                       1.12.0   
smmap                     4.0.0    
sniffio                   1.2.0    
snowballstemmer           2.1.0    
terminado                 0.9.5    
testpath                  0.4.2    
toml                      0.10.2   
tornado                   6.1      
traitlets                 4.3.2    
typed-ast                 1.4.3    
typing-extensions         3.10.0.0 
ujson                     4.0.2    
virtualenv                20.4.6   
wcwidth                   0.1.7    
webencodings              0.5.1    
websocket-client          0.59.0   
Werkzeug                  0.15.4   
wheel                     0.33.4   
widgetsnbextension        3.4.2    
wrapt                     1.12.1   
xeus-python               0.9.1    
yapf                      0.31.0   
zipp                      3.4.1

**Comment by Adam-Lv** [comment]
I met this problem recently, too.

**Comment by luoqi2023** [comment]
same here

**Comment by perrysou** [comment]
try this: https://github.com/ryantam626/jupyterlab_code_formatter/issues/193#issuecomment-1488742233

**Comment by ryantam626** [comment]
Duplicated at #193 - there should be some useful insight there.
Closing here.
