### ISSUE TITLE
add support to exclude %%sparksql magic or make it possible to add magics to the exclusion list

### ISSUE THREAD

**Issue by cccs-jc** [ryantam626/jupyterlab_code_formatter#219]
The code formatter is able to skip cells that have magic specified in the list INCOMPATIBLE_MAGIC_LANGUAGES. It would be nice to be able to add to this list via the configuration.

**Comment by ryantam626** [comment]
Sorry for the late reply, was extremely burnt out and just switched off.

This should be now fixed in 1.4.11 - thanks for flagging :pray:
