### ISSUE TITLE
Unable to find server plugin version, this should be impossible,open a GitHub issue if you cannot figure this issue out yourself.

### ISSUE THREAD

**Issue by GF-Huang** [ryantam626/jupyterlab_code_formatter#220]
![image](https://user-images.githubusercontent.com/4510984/124337643-3abed000-dbd6-11eb-9f02-bdd65cb9d69b.png)

**Comment by GF-Huang** [comment]
<code>jupyter server extension enable --py jupyterlab_code_formatter **--user**</code>

Works for me.

**Comment by mrkgoh** [comment]
> `jupyter server extension enable --py jupyterlab_code_formatter **--user**`
> 
> Works for me.

This worked for me. Thanks!

**Comment by mrkgoh** [comment]
> `jupyter server extension enable --py jupyterlab_code_formatter **--user**`
> 
> Works for me.

This worked for me. Thanks!

**Comment by ryantam626** [comment]
Sorry for the lack of reply, was extremely burnt out and just switched off.

Looks like everything is sorted, so I am going to close this and improve on the documentation at a later date.
