### ISSUE TITLE
Add command line interface?

### ISSUE THREAD

**Issue by maximz** [ryantam626/jupyterlab_code_formatter#221]
Love this tool — thanks for making it.

Would you consider adding command line support to your roadmap?

I'd like to run this code formatter from the command line, so I can format notebooks automatically as a [pre-commit hook](https://pre-commit.com/). On every commit, I run other linters from the command line, but they don't work on Jupyter notebooks. 

I'm picturing a command line interface that:
- accepts a notebook file name
- loads the notebook JSON and extracts code cells
- replaces code cells with formatted code, with your [careful handling of ipython magic commands](https://github.com/ryantam626/jupyterlab_code_formatter/blob/ac5fbd1e2d0b3f031763743e53558dba74d7380a/jupyterlab_code_formatter/formatters.py#L115)
- saves the formatted notebook to disk

Thanks!

**Comment by mathbunnyru** [comment]
This would be a super nice feature to have!

**Comment by MarcoGorelli** [comment]
Just FYI, [nbQA](https://github.com/nbQA-dev/nbQA) will do this - to be clear, it's not intended as a replacement for the excellent `jupyterlab_code_formatter`, but rather as a complement (the former runs from the command-line / as a pre-commit hook, the latter from within JupyterLab)

---

disclaimer: I'm the author of nbQA

**Comment by MarcoGorelli** [comment]
As of version 21.8b0, `black` itself now does this :partying_face:

**Comment by maximz** [comment]
@MarcoGorelli thanks for your hard work on this with nbQA and black. Looking forward to trying it out.
