### ISSUE TITLE
Turn off parse error warnings?

### ISSUE THREAD

**Issue by mseflek** [ryantam626/jupyterlab_code_formatter#226]
Hi, I may have missed this so apologies if I this is in the docs, but is there a way to turn off the code formatter errors, in particular the parse errors? I have format  on save turned on, and sometimes I have stray draft cells that I've written junk code in, and each time it auto saves it complains about formatting errors.

E.g. (I just made this up to trigger the error):
![image](https://user-images.githubusercontent.com/6554152/130690000-fbbb9a5a-8c01-4f68-a3b2-bb5f47601a10.png)

Thanks!

**Comment by ryantam626** [comment]
Sorry for the late reply, was extremely burnt out and just switched off.

Thanks for the suggestion! I will have a think how to do this cleanly and try to do it in the coming days.

**Comment by ryantam626** [comment]
This is now supported in 1.4.11 :tada: 
Example config to enable this:
```json
{
       "formatOnSave": true,
           "suppressFormatterErrors": true,
               "preferences": {
        "default_formatter": {
            "python": [
                "black"
            ],
            "r": "noop"
        }
    },
}
```

Thanks again for the suggestion :pray:

**Comment by mseflek** [comment]
Awesome! Thanks a ton!
