### ISSUE TITLE
Confusing error messages

### ISSUE THREAD

**Issue by astrojuanlu** [ryantam626/jupyterlab_code_formatter#237]
If one does `pip install jupyterlab_code_formatter` and no code formatter is installed, the following error is shown:

![Screenshot 2022-02-23 at 15-55-07 JupyterLab · Orchest](https://user-images.githubusercontent.com/316517/155345818-a74b81da-3f2c-4d9b-b6f1-d774e054e160.png)

> Formatter isort not found!

But I don't care about isort, I wanted to install black 😃

Still, I followed the obvious next step and ran `pip install isort`. Now clicking the button gives me

> Formatter black not found!

Seems we're converging: I `pip install black`, and now everything works. But the documentation has this in all caps:

https://github.com/ryantam626/jupyterlab_code_formatter/blob/ac5fbd1e2d0b3f031763743e53558dba74d7380a/docs/installation.rst?plain=1#L54-L56

In my opinion,

1. The error message could be improved ("Install a supported code formatter", or even give a specific suggestion like `pip install black`).
2. To use `jupyterlab_code_formatter` with black, only `pip install black` should be needed.
3. The documentation could be toned down a bit, to remove the yelling 🙃 and made more clear

Happy to send pull requests for these if the maintainers agree.

**Comment by astrojuanlu** [comment]
Now I get why: the default config is `["isort", "black"]`:

https://github.com/ryantam626/jupyterlab_code_formatter/blob/ac5fbd1e2d0b3f031763743e53558dba74d7380a/schema/settings.json#L242

Still, not very intuitive.

**Comment by ryantam626** [comment]
Sorry for the late reply, was extremely burnt out and just switched off.

Yes the documentation has obviously failed in conveying my point, and leaves much to be desired. I have revamped it today, have a look [here](https://ryantam626.github.io/jupyterlab_code_formatter/installation.html).

And also a reply on your first two points in the original post: there is always going to be other reasons why the plugin fail, even giving detailed reason for one case will lead to people commenting "oh but that's not what's wrong, misleading!" - there is just no pleasing everyone :)

**Comment by astrojuanlu** [comment]
Much more clear now, thanks a lot! Also, cool logo 😎 Closing
