### ISSUE TITLE
Jupyter lab cells with ?func and ??func in them cause a parse error

### ISSUE THREAD

**Issue by jkitchin** [ryantam626/jupyterlab_code_formatter#268]
**Describe the bug**

You can use `?print` for example to get the docstring for the help function. This causes  jupyterlab_code_formatter to pop up a window about a parse error like this:

<img width="643" alt="image" src="https://user-images.githubusercontent.com/1610070/175810140-a7be6133-fcc9-49b9-b440-8b18ef603d35.png">

The same thing happens with ??func.

**Diagnostic commands**
Please attach the output of the following commands (please format them properly)

- `pip freeze`

jupyterlab-code-formatter==1.4.11

- `jupyter labextension list`

@ryantam626/jupyterlab_code_formatter v1.4.11 enabled OK (python, jupyterlab-code-formatter)

- `jupyter serverextension list`

```
    jupyterlab_code_formatter  enabled 
    - Validating...
      jupyterlab_code_formatter 1.4.11 OK
```

**Comment by ryantam626** [comment]
Should be fixed in 1.5.1
