### ISSUE TITLE
Can't import jupyterlab_code_formatter since JupyterLab no longer install notebook package

### ISSUE THREAD

**Issue by KanchiShimono** [ryantam626/jupyterlab_code_formatter#269]
**Checklist prior to opening an issue**
- [x] I have followed fully the installation steps laid out in the documentation site.
- [x] I have restarted jupyterlab.
- [x] I have read the FAQ section in the documentation site.

**Describe the bug**

Previously notebook package is indirectly installed when install JupyterLab (`jupyterlab` -> `nbclassic` -> `notebook`).
However notebook package has be removed since v0.4.0 (See [nbclassis's setup.py](https://github.com/jupyter/nbclassic/blob/859bf813e9564d1848a051f8d4d04325df7e6a0a/setup.py#L110-L129)).

So import error become to be occurred here.
https://github.com/ryantam626/jupyterlab_code_formatter/blob/7c04d8cebe029655909aa3e02884bb9ed1b8c3f6/jupyterlab_code_formatter/handlers.py#L8

```sh
$ python -c "import jupyterlab_code_formatter"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/jupyterlab_code_formatter/__init__.py", line 4, in <module>
    from .handlers import setup_handlers
  File "/usr/local/lib/python3.9/site-packages/jupyterlab_code_formatter/handlers.py", line 8, in <module>
    from notebook.notebookapp import NotebookWebApplication
ModuleNotFoundError: No module named 'notebook'
```

**Diagnostic commands**

- `pip freeze | grep -E "jupyterlab|nbclassic|notebook"`

Ensure notebook is not installed. (Following list is extracted only important parts)

```text
jupyterlab==3.4.3
jupyterlab-code-formatter==1.4.11
nbclassic==0.4.0
```

- `jupyter labextension list`

```text
JupyterLab v3.4.3
/usr/local/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        @ryantam626/jupyterlab_code_formatter v1.4.11 enabled OK (python, jupyterlab-code-formatter)
```

- `jupyter serverextension list`

```text
config dir: /usr/local/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 3.4.3 OK
    jupyterlab_code_formatter  enabled
    - Validating...
Error loading server extension jupyterlab_code_formatter
      X is jupyterlab_code_formatter importable?
```

**Comment by drillan** [comment]
I had the same problem.

```bash
$ python -c "import jupyterlab_code_formatter"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/driller/venv/lib/python3.10/site-packages/jupyterlab_code_formatter/__init__.py", line 4, in <module>
    from .handlers import setup_handlers
  File "/home/driller/venv/lib/python3.10/site-packages/jupyterlab_code_formatter/handlers.py", line 8, in <module>
    from notebook.notebookapp import NotebookWebApplication
ModuleNotFoundError: No module named 'notebook'
```

I installed the [notebook](https://github.com/jupyter/notebook) package and it worked fine.

```bash
pip install notebook
```

**Comment by amitbha** [comment]
Is this extension dead?
