### ISSUE TITLE
Compatibility with black 19.3b0 

### ISSUE THREAD

**Issue by jiafengkevinchen** [ryantam626/jupyterlab_code_formatter#27]
The following error gets thrown when one use the latest version of black. Looks like `format_str` API changed in black.
```
[E 12:05:57.351 LabApp] Uncaught exception POST /jupyterlab_code_formatter/format?1558454757345 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/jupyterlab_code_formatter/format?1558454757345', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/anaconda3/envs/py36/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/anaconda3/envs/py36/lib/python3.6/site-packages/jupyterlab_code_formatter/handlers.py", line 66, in post
        data["code"], **(data["options"] or {})
      File "/anaconda3/envs/py36/lib/python3.6/site-packages/jupyterlab_code_formatter/formatters.py", line 36, in format_code
        return format_str(code, **options)[:-1]
    TypeError: format_str() got an unexpected keyword argument 'line_length'
```
The following install statement fixes the error
`pip install black==18.9b`

**Comment by ryantam626** [comment]
Oh they changed it again... Will fix over the weekends :+1:

**Comment by ryantam626** [comment]
Actually this should be already fixed, could you check if you have the latest jupyter server plugin?

`pip freeze | grep code_formatter` should show that it's 0.2.1

You can re-open this if it's still not working

**Comment by shreyasgm** [comment]
This error seems to be back. I'm currently on black v19.10b0. Formatting works using autopep8, but not using black.

`format_str() got an unexpected keyword argument 'line_length'`

**Comment by ajdajd** [comment]
same issue for `v19.10b0`. downgrading to `19.3b0` works.
