### ISSUE TITLE
Compatibility with jupyterlab-1.0.0alpha

### ISSUE THREAD

**Issue by denisshepelin** [ryantam626/jupyterlab_code_formatter#28]
I'm trying to install latest version of jupyterlab_code_formatter (0.2.1)
Installation fails after executing
`jupyter labextension install @ryantam626/jupyterlab_code_formatter`.

There is a dependencies conflict:
```
Conflicting Dependencies:
JupyterLab              Extension              Package
>=1.0.0-alpha.6 <2.0.0  >=0.17.0 <0.20.0       @jupyterlab/application
>=1.0.0-alpha.7 <2.0.0  >=0.17.0 <0.20.0       @jupyterlab/notebook
>=1.0.0-alpha.6 <2.0.0  >=0.17.0 <0.20.0       @jupyterlab/fileeditor
```

My jupyterlab version is 
`>jupyter lab --version
1.0.0a3`

**Comment by ryantam626** [comment]
Currently there is no support for `>=1.0.0` because it's still in alpha at the moment, there are breaking changes with the `1.0.0` release, and I don't really want to maintain two versions at the same time. Sorry :worried:

**Comment by ryantam626** [comment]
Will properly support `>=1.0.0` when it gets out of the alpha status though

**Comment by ryantam626** [comment]
If you really want to use the alpha version with this plugin, you can fork it and revert 44f0e36ab6a1d6c3d958930402d34b4f68b6f923 and install locally as well

**Comment by denisshepelin** [comment]
Fair enough!

Will try to use this solution:
> If you really want to use the alpha version with this plugin, you can fork it and revert 44f0e36 and install locally as well
