### ISSUE TITLE
Issue: Bug report

### ISSUE THREAD

**Issue by Chenjy0212** [ryantam626/jupyterlab_code_formatter#285]
**Checklist prior to opening an issue**
- [ ] I have followed fully the installation steps laid out in the documentation site.
- [ ] I have restarted jupyterlab.
- [ ] I have read the FAQ section in the documentation site.

**Describe the bug**

**Diagnostic commands**
Please attach the output of the following commands (please format them properly)

- `pip freeze`

- `jupyter labextension list`

- `jupyter serverextension list`

**Screenshots**

**Additional context**

**Comment by ryantam626** [comment]
Doesn't seem to include any info here :thinking:
