### ISSUE TITLE
Jupyterlab Code Formatter Error

### ISSUE THREAD

**Issue by dsingh14usf** [ryantam626/jupyterlab_code_formatter#289]
Jupyterlab Code Formatter Error - despite disabling the plugin in settings, getting the below error on jupyter lab startup;
`Unable to find server plugin version. You may need to restart your JupyterLab server, If that does not fix the issue please open an issue at: https://github.com/ryantam626/jupyterlab_code_formatter/issues/new/choose`

**Comment by LeHyperion** [comment]
I am having the same issue. @dsingh14usf Did you manage to resolve the issue?

**Comment by dsingh14usf** [comment]
I just disabled the plugin for now.

**Comment by bipin-lekhak** [comment]
+1 same issue

**Comment by RaphaelBonatti** [comment]
For me, it seems to work with a previous version (1.5.3), but not with 1.6.0.
