### ISSUE TITLE
Is there a way to ignore cells that contain hive/presto/spark magics when applying code formatter?

### ISSUE THREAD

**Issue by hanakawamomo** [ryantam626/jupyterlab_code_formatter#290]
Hi there, 

Thanks for making this great tool. I need some help configuring how to ignore cells that contain hive/presto/spark magics. Currently, applying formatter on those cells gives me `Jupyterlab Code Formatter Error`

jupyterlab: 3.3.4
jupyterlab_code_formatter: 1.5.3
sparkmagic: 0.15.0

<img width="1071" alt="Screen Shot 2022-11-07 at 2 23 35 PM" src="https://user-images.githubusercontent.com/104341894/200428233-8f363615-8a78-44c5-a3b8-48ac8c68e6e9.png">

**Comment by ryantam626** [comment]
Hi, sorry for being MIA, I was dealing with too much and just had to disconnect.

And yes! There is a way, could you give me a list of magic commands that you would like ignored? (the bit that comes after `%%`)

There is an existing list in https://github.com/ryantam626/jupyterlab_code_formatter/blob/ace5fb442965eebd1b950df1f3dda284ec8dc8d0/jupyterlab_code_formatter/formatters.py#L24 but it is obviously not exhaustive yet!
