### ISSUE TITLE
`_jupyter_server_extension_points` function was not found

### ISSUE THREAD

**Issue by jamesmyatt** [ryantam626/jupyterlab_code_formatter#301]
I get the following message when starting Jupyterlab. Seems OK for now, but presumably needs to be updated.

> A `_jupyter_server_extension_points` function was not found in jupyterlab_code_formatter. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.

I have jupyter_server 2.5.0 installed.

**Comment by ryantam626** [comment]
Thanks for the report, I will keep an eye out in my current big refactor of the plugin :+1:
