### ISSUE TITLE
Metadata.toJson is not a function : Unable to format notebook

### ISSUE THREAD

**Issue by aflip** [ryantam626/jupyterlab_code_formatter#314]
On clicking the code format button, a pop up appears with the following message:

```
Jupyterlab Code Formatter Error
this.notebookTracker.currentWidget.content.model.metadata.toJSON is not a function
```

verion: 2.0.0--rc.1 is what shows up on jupyter but pip says the version installed is 2.0.0. I have uninstalled and installed via pip multiple times

![image](https://github.com/ryantam626/jupyterlab_code_formatter/assets/59506464/ac9048c8-f454-4dd2-bc8a-3e2f0d06710f)

jupytelab version 4.0.0
jupyter                   1.0.0         
jupyter-lsp               2.1.0
jupyter_server            2.5.0

**Comment by ryantam626** [comment]
Hmm odd, could you retry with 2.2.1 pelase? I feel like this is due to the labextension being out of sync which is my fault in release process.

**Comment by aflip** [comment]
Upgrade to 2.2.1 has fixed the issue. Thank you!

**Comment by ryantam626** [comment]
Wonderful!
