### ISSUE TITLE
Is there any way to pass command line arguments to the formatter?

### ISSUE THREAD

**Issue by wiseyoungbuck** [ryantam626/jupyterlab_code_formatter#32]
I would like to be able to pass the `--skip-string-normalization` flag to the black formatter.
Or set this in the formatter configuration somehow.

**Comment by ryantam626** [comment]
Hi! Apologies for the late reply, it's currently unsupported right now.

But it's a simple addition to [here](https://github.com/ryantam626/jupyterlab_code_formatter/blob/e1f813bd6c0e1ed672dd90e6c8f2aef8d2c7a0bd/schema/settings.json#L10) - will be available soon!

**Comment by ryantam626** [comment]
Okay v0.2.3 should support this now! Let me know if it doesn't work for you somehow :+1:
