### ISSUE TITLE
Strange Formatted List 

### ISSUE THREAD

**Issue by metaboulie** [ryantam626/jupyterlab_code_formatter#320]
Initialize a list like:`X = [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10]`,
after formatted:
X = [
    1,
    1,
    1,
    2,
    2,
    2,
    3,
    3,
    3,
    4,
    4,
    4,
    5,
    5,
    5,
    6,
    6,
    6,
    7,
    7,
    7,
    8,
    8,
    8,
    9,
    9,
    9,
    10,
    10,
    10,
], which is strange

**Comment by ryantam626** [comment]
This plugin is only responsible for relaying code for formatters to work on and propagating back the results to jupyterlab, in other words I don't think that's an issue with this plugin but rather an issue with how the formatter(s) you are using are configured.

**Comment by metaboulie** [comment]
If you are using the `black` code formatter, you can temporarily prevent `black` from formatting by using comments like the ones shown below:

```python
# fmt: off
X = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,11,1,1,1,1,1,1,11,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
# fmt: on
```

Additionally, if you are formatting with `yapf` or `autopep8`, the comments mentioned above will work as well. However, `yapf` will format the list into the following structure:

```python
# yapf
X = [
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 11, 1, 1, 1, 1, 1, 1,
    11, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
]
```

and `autopep8` will format the list as follows:

```python
# autopep8
X = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 11, 1, 1, 1, 1, 1, 1, 11, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
```
