### ISSUE TITLE
add pep8 setting

### ISSUE THREAD

**Issue by reza1615** [ryantam626/jupyterlab_code_formatter#35]
Hi,
I want to add this setting in advance setting but it shows syntax error and wouldn't save. what should I do? would you please add some setting example in the README.md

```
[pep8]
ignore = E226,E302,E41
max-line-length = 160
```

**Comment by reza1615** [comment]
I found the answer.
`{
    "autopep8":{"max_line_length" : 120,
    "ignore": ["E226","E302","E41"]
               }
}
`

**Comment by ryantam626** [comment]
Ah, was just about to type something up.

Will add something to the README later :+1:

**Comment by reza1615** [comment]
I sent pull request :)
