### ISSUE TITLE
Support for Jupyterlab 1.0.0

### ISSUE THREAD

**Issue by bjtho08** [ryantam626/jupyterlab_code_formatter#37]
Now that jupyterlab 1.0.0 has been released, it would be nice to get this extension updated.

**Comment by ryantam626** [comment]
Yes good point :+1: sadly I will be AFK for quite a few days from today onwards, I will get to it ASAP though..

**Comment by NickYi1990** [comment]
> Yes good point 👍 sadly I will be AFK for quite a few days from today onwards, I will get to it ASAP though..

Awesome!

**Comment by sagarkar10** [comment]
also looking for it.

**Comment by ryantam626** [comment]
Should be support now - sorry for the wait. (also thanks @gnestor for providing the MR)
