### ISSUE TITLE
Allow custom yapf formatting options

### ISSUE THREAD

**Issue by CaselIT** [ryantam626/jupyterlab_code_formatter#38]
Currently the schema for the yapf configuration allows only one of the predefined styles.

Yapf supports custom styles by passing a custom string. From the [documentation](https://github.com/google/yapf#formatting-style):

> It's also possible to do the same on the command line with a dictionary. For example:
> ```--style='{based_on_style: chromium, indent_width: 4}'```

The schema for the yapf formatter should specify that `style_config` is a string, removing the list of allowed entry

I've changed it in my local configuration and it works correctly with something like
```"{based_on_style: google, column_limit: 150}"```

**Comment by ryantam626** [comment]
Oh excellent! Will change to that in the next release :+1:

**Comment by CaselIT** [comment]
Thanks!
I can open a pr if you prefer

**Comment by ryantam626** [comment]
That would be wonderful 👍
