### ISSUE TITLE
Disable commands when no formatter supported

### ISSUE THREAD

**Issue by jtpio** [ryantam626/jupyterlab_code_formatter#4]
Commands stay enabled for every file type / document currently open, which can be confusing.

Example with json files:

![image](https://user-images.githubusercontent.com/591645/49320682-4ec46180-f503-11e8-9b61-b4b20da288b6.png)

The idea would be disable them when they can't be used.

**Comment by ryantam626** [comment]
Ah yes, this was left as a TODO in the code and I never got around finishing it :see_no_evil:
