### ISSUE TITLE
Support "formatr" to R code block or R file

### ISSUE THREAD

**Issue by dev-wei** [ryantam626/jupyterlab_code_formatter#44]
1. Use r2py python library to interact with R language
2. Add new "formatR" formatter by following with others
3. Fix the show.hide logic to support R file

**Comment by dev-wei** [comment]
@ryantam626 

Could you grant me permission for PR?

**Comment by ryantam626** [comment]
I think you need to open PR on your fork :thinking:

**Comment by dev-wei** [comment]
@ryantam626 got you! PR #45 is created, and ready for review.

**Comment by ryantam626** [comment]
#45 merged, closing - thanks again :grin:
