### ISSUE TITLE
[Feature Request] Show a error popup window when the code sent in has syntax issue

### ISSUE THREAD

**Issue by dev-wei** [ryantam626/jupyterlab_code_formatter#46]
Currently, the plugin silently swallows the errors when the code sent in for formatting has syntax issue. It is very annoying when there is no prompt response when the command is executed.

**Comment by ryantam626** [comment]
Yeah agreed, popup window might be a little bit too aggressive but something similar is definitely needed!

**Comment by ryantam626** [comment]
#55 should somewhat resolve this, it now logs the error in the web broswer's console.
