### ISSUE TITLE
R formatting does not work

### ISSUE THREAD

**Issue by Alalalalaki** [ryantam626/jupyterlab_code_formatter#48]
I tried both conda and pip install. The extension is updated to 0.4. But the R formatter doesn't appear in command.

**Comment by ryantam626** [comment]
Hi! I need output of the following:
1. `pip freeze | grep 'jupyterlab\|rpy'`
2. `jupyter labextension list`
3. `jupyter serverextension list`
4. `python -c 'import rpy2.robjects.packages as rpackages;print(rpackages.importr("formatR", robject_translations={".env": "env"}))'`

**Comment by Alalalalaki** [comment]
@ryantam626 Under your instruction I find the problem is that I have a rpy version of 2.9.4. After I update it to 3.0.5 the formatR now works.

**Comment by ryantam626** [comment]
Ah excellent! Good to hear :grin:
