### ISSUE TITLE
Format all cells

### ISSUE THREAD

**Issue by mazzma12** [ryantam626/jupyterlab_code_formatter#53]
Hello, is it possible to have another command that format all the cells ? Or all the selected cells ? I can't find it. For example the black formater for jupyter notebook does this : 
https://github.com/drillan/jupyter-black

Thank you !

**Comment by ryantam626** [comment]
Hey! It's certainly possible, but I just haven't had the time to sit down and implement it.

**Comment by mlucool** [comment]
Did this as part of a PR: https://github.com/ryantam626/jupyterlab_code_formatter/pull/55

**Comment by ryantam626** [comment]
PR now merged :+1: Closing this now, thanks again @mlucool !
