### ISSUE TITLE
Exception: Passing list, expecting str

### ISSUE THREAD

**Issue by stefansimik** [ryantam626/jupyterlab_code_formatter#58]
Hi, this extension fails on exception
with latest JupyterLab 1.14 and latest black 19.3b0.

Exception is exactly printed into console in happens in:
- file **formatters.py**
- class **BlackFormatter**
- function:  **format_code(...)**
- line:   `code = re.sub("^%", "#%#", code, flags=re.M)`

It fails on input argument $code (that is of type **list**), but should be **string**

**Comment by ryantam626** [comment]
Could you show me output of

`pip freeze | grep 'jupyterlab\|rpy'`
`jupyter labextension list`
`jupyter serverextension list`
plase?

**Comment by stefansimik** [comment]
#### Export of `pip freeze`
(I don't have linux / mac, so there is no grep on my windows machine ;) )
<details>
```
appdirs==1.4.3
attrs==19.3.0
backcall==0.1.0
black==19.3b0
bleach==3.1.0
certifi==2019.9.11
Click==7.0
colorama==0.4.1
decorator==4.4.0
defusedxml==0.6.0
entrypoints==0.3
importlib-metadata==0.23
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
jedi==0.15.1
Jinja2==2.10.3
json5==0.8.5
jsonschema==3.1.1
jupyter-client==5.3.3
jupyter-core==4.5.0
jupyterlab==1.1.4
jupyterlab-code-formatter==0.5.2
jupyterlab-server==1.0.6
MarkupSafe==1.1.1
mistune==0.8.4
more-itertools==7.2.0
nbconvert==5.6.0
nbformat==4.4.0
notebook==6.0.1
pandocfilters==1.4.2
parso==0.5.1
pickleshare==0.7.5
prometheus-client==0.7.1
prompt-toolkit==2.0.10
Pygments==2.4.2
pyrsistent==0.15.4
python-dateutil==2.8.0
pywin32==224
pywinpty==0.5.5
pyzmq==18.1.0
Send2Trash==1.5.0
six==1.12.0
terminado==0.8.2
testpath==0.4.2
toml==0.10.0
tornado==6.0.3
traitlets==4.3.3
wcwidth==0.1.7
webencodings==0.5.1
wincertstore==0.2
zipp==0.6.0
```
</details>

#### Export of `conda env export > environment.yaml`
<details>
```
name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.3=py_1
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - black=19.3b0=py_0
  - bleach=3.1.0=py_0
  - ca-certificates=2019.9.11=hecc5488_0
  - certifi=2019.9.11=py37_0
  - click=7.0=py_0
  - colorama=0.4.1=py_0
  - decorator=4.4.0=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_1000
  - importlib_metadata=0.23=py37_0
  - ipykernel=5.1.2=py37h5ca1d4c_0
  - ipython=7.8.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - json5=0.8.5=py_0
  - jsonschema=3.1.1=py37_0
  - jupyter_client=5.3.3=py37_1
  - jupyter_core=4.5.0=py_0
  - jupyterlab=1.1.4=py_0
  - jupyterlab_code_formatter=0.5.2=py_0
  - jupyterlab_server=1.0.6=py_0
  - libsodium=1.0.17=h2fa13f4_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37hfa6e2cd_0
  - mistune=0.8.4=py37hfa6e2cd_1000
  - more-itertools=7.2.0=py_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.0=py37_1
  - nbformat=4.4.0=py_1
  - nodejs=12.11.1=0
  - notebook=6.0.1=py37_0
  - openssl=1.1.1c=hfa6e2cd_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.2.3=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - pygments=2.4.2=py_0
  - pyrsistent=0.15.4=py37hfa6e2cd_0
  - python=3.7.4=h5263a28_0
  - python-dateutil=2.8.0=py_0
  - pywin32=224=py37hfa6e2cd_1000
  - pywinpty=0.5.5=py37_1000
  - pyzmq=18.1.0=py37h16f9016_0
  - send2trash=1.5.0=py_0
  - setuptools=41.4.0=py37_0
  - six=1.12.0=py37_1000
  - sqlite=3.30.0=he774522_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - toml=0.10.0=py_0
  - tornado=6.0.3=py37hfa6e2cd_0
  - traitlets=4.3.3=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - zeromq=4.3.2=h6538335_2
  - zipp=0.6.0=py_0
```
prefix: C:\Users\stesim\Miniconda3\envs\test
</details>



#### Export of `jupyter labextension list`
<details>
```
JupyterLab v1.1.4
Known labextensions:
   app dir: C:\Users\stesim\Miniconda3\envs\test\share\jupyter\lab
        @ryantam626/jupyterlab_code_formatter v0.6.0 enabled  ok
```
</details>



#### Export of `jupyter serverextension list`
<details>
```
config dir: C:\Users\stesim\.jupyter
    jupyterlab_code_formatter enabled
    - Validating...
      jupyterlab_code_formatter  ok
config dir: C:\Users\stesim\Miniconda3\envs\test\etc\jupyter
    jupyterlab enabled
    - Validating...
      jupyterlab 1.1.4 ok
```
</details>



#### For testing, I simply created new environment using these commands
<details>
**conda create -n test python=3.7
conda install jupyterlab nodejs black**

+ 3 commands from your page
https://github.com/ryantam626/jupyterlab_code_formatter
```
jupyter labextension install @ryantam626/jupyterlab_code_formatter
conda install -c conda-forge jupyterlab_code_formatter
jupyter serverextension enable --py jupyterlab_code_formatter
```
</details>

**Comment by stefansimik** [comment]
I prepared short 2 min demonstration in video here:
https://drive.google.com/open?id=1nlwcR9f_rVqpUxk4--LL-6lkiOB-vMaf

**Comment by ryantam626** [comment]
Try upgrading the python package `jupyterlab_code_formatter`, there is a version mismatch.

**Comment by stefansimik** [comment]
How easy, that worked. Thank you very much Ryan.

**The core of the problem** is here:

Instructions on you github are logically fully correct, but they do not work in practice.
Reason is, that:
* Anaconda's conda-forge ** contains only old version of jupyterlab_code_formatter v0.5.2
* latest version jupyterlab_code_formatter v0.6.** is not yet there

That means:
* conda installation steps lead to failure (conda provides old version v0.5.2)
* pip installation steps work fine (pypi.org contains latest version v0.6.0)

**My recommendation:**
Bring a note to the conda-installation steps in your github please - that **conda** does not contain latest version v0.6.0, and until that time, **only installation is just via pip works correctly**.

**If possible**
Make strict requirent in you jupyterlab extension, that it requires v.0.6.0 and do not accept old version v0.5.2

Thank you Ryan for your great work!
You plugin makes a difference, when using JupyterLab!

**Comment by ryantam626** [comment]
Ah great to hear.

But I thought conda should have installed v0.5.2 for you instead of a fialure? The conda recipe (maintained by others) install both the julyterlab server and lab extension from source, the end result should be a working version of v0.5.2 instead of a vesion mismatch/imcomplete install.

> Make strict requirement in you jupyterlab extension, that it requires v.0.6.0 and do not accept old version v0.5.2
Yes this is a mistake on my part, will do this once I have time.
