### ISSUE TITLE
Does not work if jupyter lab started under different user

### ISSUE THREAD

**Issue by stefansimik** [ryantam626/jupyterlab_code_formatter#59]
Hi,
problem is,  that this plugin does not work, if  jupyter lab is ran under another user
(another user = other user than original one, from which jupyterlab was installed)

If jupyterlab is ran under different user, then whole Jupyterlab works correctly, but this plugin fails to work and prints HTTP 404 errors for each formatting request.

Probable reason is that different user has different home-folder and probably this plugin
(or black module itself) is dependent on some files/configs in the user folder.

(Common motivation to start jupyterlab under different user is to have access to ODBC connections of that user (and authenticate to different DBs)

**Comment by ryantam626** [comment]
Ah, that's a use case I never thought of, I will try to have a look this weekend :+1:

**Comment by ryantam626** [comment]
I think to make it work - you just need to install and enable the server extension (the `pip` installable one) with the user you are starting jupyterlab. 

Check with `jupyter serverextension list` under both users and you should see the other user to be lacking the server extension.

**Comment by ryantam626** [comment]
I am fairly sure this should fix it, reopen if you are still seeing issues :+1:
