### ISSUE TITLE
format options not shown in jupyterlab

### ISSUE THREAD

**Issue by vnijs** [ryantam626/jupyterlab_code_formatter#6]
The extension is enabled (see below) but for some reason I don't see any format commands available (see screenshot). Any idea what might be going on?

![image](https://user-images.githubusercontent.com/2998956/50946485-6e2da300-144e-11e9-9ca7-92c20905ac32.png)

```
jovyan@d3a5e2f1ecd1:~$ jupyter labextension list
JupyterLab v0.35.4
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
        @jupyterlab/git v0.5.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v0.1.5  enabled  OK
        jupyterlab-server-proxy v0.1.0-beta2  enabled  OK
```

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import black
>>> black.__version__
'18.9b0'
```

**Comment by ryantam626** [comment]
Hi! Can you confirm that you have installed the serverextension as well?
Should be visible when you run `jupyter serverextension list`.

**Comment by vnijs** [comment]
Thanks @ryantam626. I used the install commands listed in the README but you are correct that the server extension is not showing up. I just re-built the docker image just to be sure ... it builds without error and uses the commands below but for some reason the server extension is not registered. Any suggestions?

```
jovyan@mbp ~ jupyter serverextension list
config dir: /usr/local/etc/jupyter
    jupyter_server_proxy  enabled
    - Validating...
      jupyter_server_proxy  OK
    jupyterlab  enabled
    - Validating...
      jupyterlab 0.35.4 OK
    jupyterlab_git  enabled
    - Validating...
      jupyterlab_git  OK
```

From the Dockerfile:

```
  ...
  && jupyter labextension install @ryantam626/jupyterlab_code_formatter \
  && jupyter serverextension enable --py jupyterlab_code_formatter
```

Dockerfile: https://github.com/radiant-rstats/docker/blob/master/rsm-msba/Dockerfile

**Comment by ryantam626** [comment]
Hmm surprised it built successfully for you.

`jupyter serverextension enable --py jupyterlab_code_formatter` should blow up because you haven't added the requirements of `jupyterlab_code_formatter==0.1.1` in `requirements.txt`

Just tested it with your Dockerfile, seems okay to me with that added (at least it showed up in `jupyter serverextension list`)

Also it seemed like you ran `jupyter serverextension list` outside of Docker (you had `@mbp` instead of `@somehash`)?

And also you can chain the jupyter lab extension installs like `jupyter labextension install a b c`, I almost fell asleep waiting for npm to resolve dependency over and over haha :sleepy:

**Comment by vnijs** [comment]
Thanks for trying that out and for the tip on installing labextensions! I did actually have the python modules in my requirements file but hadn't pushed the updates to GitHub yet. I tried again and still no luck.

I did check the serverextension list from the container. The reason I don't have `@somehash` is that I have the container mount my home drive. That made me think that maybe the extension was installing to the docker user's homedrive and then was erased when a drive is mounted. So then I tried the below and that worked fine.

Thanks for helping to figure this out @ryantam626! The extension works great.

Q: I don't think there is a way to add the functionality to a dropdown at this point correct? If not, I'll see if I can figure out how to enable the key-board shortcut by default in the image/container.

![image](https://user-images.githubusercontent.com/2998956/50989583-a079e780-14c4-11e9-9c41-14a2d06e8a6a.png)

`  && jupyter serverextension enable --py jupyterlab_code_formatter --system`

**Comment by ryantam626** [comment]
Aha! That was a tricky one, glad you figured it out!

It should show up in the `Edit` drop down, but ideally one should use a shortcut, I didn't put in one because user might have had one conflicting with the one I had in mind.

**Comment by vnijs** [comment]
Didn't know about the Edit dropdown. Nice!

**Comment by metya** [comment]
Reopen this issue, cause I have the same problem, but my `jupyter serverextension list` is ok and I have installed `jupyter_lab_formatter`

So what may it be a problem?

```
λ jupyter serverextension list
config dir: C:\Users\metya\.jupyter
    jupyter_tensorboard enabled
    - Validating...
      jupyter_tensorboard 0.1.8 ok
    nbresuse enabled
    - Validating...
      nbresuse  ok
    jupyterlab_git enabled
    - Validating...
      jupyterlab_git  ok
    jupyterlab_code_formatter enabled
    - Validating...
      jupyterlab_code_formatter  ok
config dir: C:\ProgramData\Anaconda3\etc\jupyter
    jupyterlab enabled
    - Validating...
      jupyterlab 0.35.4 ok
    jupyterlab_github enabled
    - Validating...
      jupyterlab_github 0.7.0 ok
    nbresuse enabled
    - Validating...
      nbresuse  ok
    nbextensions disabled
    - Validating...
Error loading server extension nbextensions
      X is nbextensions importable?
```


```
λ jupyter labextension list
JupyterLab v0.35.4
Known labextensions:
   app dir: C:\ProgramData\Anaconda3\share\jupyter\lab
        @deathbeds/jupyterlab_graphviz v0.1.1 enabled  ok
        @ijmbarr/jupyterlab_spellchecker v0.1.4 enabled  ok
        @jupyter-widgets/jupyterlab-manager v0.38.1 enabled  ok
        @jupyterlab/celltags v0.1.4 enabled  ok
        @jupyterlab/geojson-extension v0.18.1 enabled  ok
        @jupyterlab/git v0.4.2 enabled  ok
        @jupyterlab/github v0.10.0 enabled  ok
        @jupyterlab/google-drive v0.16.0 enabled  ok
        @jupyterlab/katex-extension v0.20.0 enabled  ok
        @jupyterlab/latex v0.6.1 enabled  ok
        @jupyterlab/plotly-extension v0.18.1 enabled  ok
        @jupyterlab/statusbar v0.5.0 enabled  ok
        @jupyterlab/toc v0.6.0 enabled  ok
        @krassowski/jupyterlab_go_to_definition v0.1.6 enabled  ok
        @lckr/jupyterlab_variableinspector v0.1.0 enabled  ok
        @mflevine/jupyterlab_html v0.1.4 enabled  ok
        @ryantam626/jupyterlab_code_formatter v0.2.0 enabled  ok
        jupyter-gmaps v0.8.2 enabled  ok
        jupyterlab-chart-editor v1.0.0 enabled  ok
        jupyterlab-jupytext v0.1.0-dev enabled  ok
        jupyterlab_bokeh v0.6.3 enabled  ok
        jupyterlab_nbmetadata v0.1.0 enabled  ok
        jupyterlab_tensorboard v0.1.5 enabled  ok

```
