### ISSUE TITLE
format and format_all don't work

### ISSUE THREAD

**Issue by andrewtcrooks** [ryantam626/jupyterlab_code_formatter#62]
In the jupyterlab code formatter settings you should be able to add hotkeys for format and format_all. 

<img width="431" alt="Screen Shot 2019-10-22 at 11 14 30 PM" src="https://user-images.githubusercontent.com/670417/67363239-c89d7900-f521-11e9-9149-ab2e8d01d96b.png">

I added these hotkeys into the settings and they don't seem to work for the Python3 or R notebooks. I note these hotkeys work when I change "format" or "format_all" to "formatR" or "styler".

Format notebook button in notebook:

<img width="883" alt="Screen Shot 2019-10-22 at 11 02 12 PM" src="https://user-images.githubusercontent.com/670417/67363021-4b720400-f521-11e9-98fc-3e20cf507f88.png">

Pressing the button inside a Python 3 notebook works as expected as uses default python formatter.

Pressing the button inside a R notebook does nothing

Summary:

1. the format and format_all don't activate when assigned to hotkeys
2. "Format Notebook" button in R notebooks does not activate default R formatter
3. the context menu (right-click inside notebook) only shows "Format Cell" inside Python # notebook and is not in the menu inside R notebooks.

**Comment by ryantam626** [comment]
Hmm, this requires a little bit more debugging, I think there is sufficient info for now, I will try to have a look this weekend.

**Comment by ryantam626** [comment]
Found the error.. the key for the settings for default formatter has be to a capitalised "R".. 

i.e. like 
```
        "default_formatter": {
            "python": "black",
            "R": "styler"
        }
```

**Comment by ryantam626** [comment]
I am fairly sure this is it, please re-open if you are still seeing issues :+1:
