### ISSUE TITLE
styler options for scope

### ISSUE THREAD

**Issue by andrewtcrooks** [ryantam626/jupyterlab_code_formatter#63]
In the [best article on styler](https://www.tidyverse.org/articles/2017/12/styler-1.0.0/):
I see there are many more available options that could be passed.

The current available options inside jupyterlab code formatter for styler are
1. scope = boolean
2. strict = boolean

According to the docs though styler has several options and scope has more than just 2 options

1. scope = ("spaces", "indentation", "line-breaks", "tokens")
2. strict = boolean
3. math_indentation = list(...)
4. reindentation = list(...)

Would it be possible to add these additional options?

**Comment by ryantam626** [comment]
Ah, I don't personally use R that much, I will try to give it a look this weekend and expose these options :+1:
