### ISSUE TITLE
Icon for Format All in Toolbar

### ISSUE THREAD

**Issue by mlucool** [ryantam626/jupyterlab_code_formatter#65]
In my commit I never choose an icon for the toolbar because there isn't a natural one. I think we should use one as the toolbar text takes up too much space. I am opening this issue to pick one.

What about:
![image](https://user-images.githubusercontent.com/1813603/67581686-72455b80-f716-11e9-9739-457f4341edb3.png) ([ref](https://fontawesome.com/icons/align-justify?style=solid))

![image](https://user-images.githubusercontent.com/1813603/67581798-a3be2700-f716-11e9-9f19-1f99a3deda09.png)
([ref](https://fontawesome.com/icons/remove-format?style=solid))

**Comment by ryantam626** [comment]
Hey! The `remove-format` icon seems weird because of the diagonal line, and the `align-justify` is a bit vague by itself, do you see any other good ones? I realise most icon probably is commonly assicoated with something else already and this is quite a hard task haha

**Comment by mlucool** [comment]
https://fontawesome.com/icons?d=gallery&c=design,editors,files&m=free

[Pecil ruler?](https://fontawesome.com/icons/pencil-ruler?style=solid)

[Magic?](https://fontawesome.com/icons/magic?style=solid) (although magic has a clear meaning in ipython)

**Comment by ryantam626** [comment]
I think pencil ruler is probably fine :smile:

**Comment by mlucool** [comment]
Turns out that's in font awesome 5.x. https://fontawesome.com/v4.7.0/cheatsheet/ is the list of icons we can choose from trivially. We can make pencil ruler work if we want another version of font awesome brought in

What about fa-wrench?  fa-pencil-square-o?  fa-columns? fa-code? fa-superpowers?

**Comment by mlucool** [comment]
@ryantam626 any thoughts?

**Comment by ryantam626** [comment]
Sorry was a bit busy with other stuff. I quite like `fa-superpowers` :grin:
