### ISSUE TITLE
Compatability error with black 19.10b0

### ISSUE THREAD

**Issue by agoose77** [ryantam626/jupyterlab_code_formatter#69]
This line performs string comparison, and so reverts to the old API for black 19.10b0
https://github.com/ryantam626/jupyterlab_code_formatter/blob/a32e56ac9ce3943b46e4a9fc794dfb19450432f3/jupyterlab_code_formatter/formatters.py#L41

One solution is to use the `packaging` module, which is used by setuptools (but it might be vendorised and therefore we should add as a dependency).

This would be added to the module header
```python
from packaging import version

VERSION_BLACK_LEGACY = version.parse("19.3b0")
```

and the `format_code` function body
```python
        if version.parse(black.__version__) >= VERSION_BLACK_LEGACY:
            code = black.format_str(code, mode=black.FileMode(**options))[:-1]
```

**Comment by ryantam626** [comment]
Ah, you are right :man_facepalming: , thanks for the suggested fix :+1:
