### ISSUE TITLE
Use compiled pattern 

### ISSUE THREAD

**Issue by agoose77** [ryantam626/jupyterlab_code_formatter#70]
The regex replacement here https://github.com/ryantam626/jupyterlab_code_formatter/blob/a32e56ac9ce3943b46e4a9fc794dfb19450432f3/jupyterlab_code_formatter/formatters.py#L39 is using an un-compiled pattern. Perhaps we should look at pre-compiling? It's not a massive overhead given the size of the pattern, however.

**Comment by ryantam626** [comment]
You are right, will get that fixed :+1:

**Comment by ryantam626** [comment]
Actually the docs says don't worry about it https://docs.python.org/3.7/library/re.html#re.compile but I already made the change, oh wells ¯\_(ツ)_/¯

**Comment by agoose77** [comment]
Oh, I learned something new! Thanks!
