### ISSUE TITLE
format does not work

### ISSUE THREAD

**Issue by qitianliang** [ryantam626/jupyterlab_code_formatter#78]
setup as readme, and format button shown in jupyterlab, However it does not work

env:

![图片](https://user-images.githubusercontent.com/14808110/68080255-a0bbe880-fe32-11e9-8155-b32f3b639370.png)

**Comment by ryantam626** [comment]
You are missing the server extension, every single step in the setup is needed.

```
pip install jupyterlab_code_formatter
jupyter serverextension enable --py jupyterlab_code_formatter
```

**Comment by qitianliang** [comment]
I tried your scripts, however, it still not work...
![图片](https://user-images.githubusercontent.com/14808110/68265187-5a5ec780-0086-11ea-9829-b2b72d5b0209.png)

![图片](https://user-images.githubusercontent.com/14808110/68265149-33a09100-0086-11ea-8e7f-f8b6ba938283.png)

**Comment by qitianliang** [comment]
> 
> 
> I tried your scripts, however, it still not work...
> ![图片](https://user-images.githubusercontent.com/14808110/68265187-5a5ec780-0086-11ea-9829-b2b72d5b0209.png)
> 
> ![图片](https://user-images.githubusercontent.com/14808110/68265149-33a09100-0086-11ea-8e7f-f8b6ba938283.png)

I degrade jupyterlab to 1.0.0 ,and it works very well, may be this extension not fit in the latest version of jupyterlab..

**Comment by qitianliang** [comment]
just a restart of jupyterlab will solve this problem, the latest version also works... sorry for my mistakes...
