### ISSUE TITLE
how to use extra styler options?

### ISSUE THREAD

**Issue by andrewtcrooks** [ryantam626/jupyterlab_code_formatter#79]
> Reference used: https://www.tidyverse.org/articles/2017/12/styler-1.0.0/
> 
> scope option is a string, fix schema;
> Support math_token_spacing by transforming to R list, add to schema;
> Support reindention by transforming to R list, add to schema;
> Fixes: #63 

After updating to the new 0.7.0 version, the new scope option seems to work.

However, I'm trying to figure out how to use the math_token_spacing and reindentation options without much luck.

I see in the schema that they are supposed to be objects though, which I think means I would have to define a class to use them. 

How it's input in R:

> math_token_spacing = list(one = c("'+'", "'-'"), zero = c("'/'", "'*'", "'^'"))
> 
> reindention = list(regex_pattern = "^###", indention = 0, comments_only = TRUE)

Given that the code formatter options file has the below format, how to I get the options above into the "???" portions shown below?

>     "styler": {
>         "scope": "token",
>         "strict": false,
>         "math_token_spacing": ???,
>         "reindentation": ???
>     },

**Comment by andrewtcrooks** [comment]
OMG I'm silly. This isn't Python, its javascript.

JSON objects are surrounded by curly braces {}.

Example
{ "name":"John", "age":30, "car":null }

I also put reindentation when it's actually "reindention"

I think it's supposed to look like below but now when I run "format cell", it doesn't do anything

>     "styler": {
>         "scope": "token",
>         "strict": false,
>         "math_token_spacing": { 
>             "zero":["'^'"],
>             "one":["'+'", "'-'", "'*'","'/'"]
>         },
>         "reindention": {
>             "regex_pattern" : "^###", 
>             "indention" : 0, 
>             "comments_only" : true}
>     },

**Comment by andrewtcrooks** [comment]
I was using "token" when I should have been using "tokens"

**Comment by andrewtcrooks** [comment]
Ok, so the first two options run fine. Enabling either of the last two makes it not run though. 

"styler": {
    "scope": "tokens",
    "strict": false,
    "math_token_spacing": { 
        "zero":["'^'"],
        "one":["'+'", "'-'", "'*'","'/'"]
    },
    "reindention": {
        "regex_pattern" : "^###", 
        "indention" : 0, 
        "comments_only" : true}
},

**Comment by ryantam626** [comment]
Huh, it worked for me when I tested it, it was probably a simpler case though, will try it again and document this properly when I have time.

**Comment by ryantam626** [comment]
Hey apologies for not replying sooner :sweat: got really busy with other stuff..

I had a look again, looks like there was an import error that I introduced between testing it locally and publish it... Needless to say I fixed it now, the latest version should work with the config you posted now (there are serval tests that asserts that now). Let me know if it still doesn't work somehow :pray:
