### ISSUE TITLE
Additional styler options

### ISSUE THREAD

**Issue by andrewtcrooks** [ryantam626/jupyterlab_code_formatter#80]
If you check of the CRAN [documentation for styler](https://cran.r-project.org/web/packages/styler/styler.pdf), it defaults to tidyverse_style which starts on page 14

there are two more options that are available

example:
indent_by = 2,
start_comments_with_one_space = FALSE

could we have the following in the schema?

>         "styler": {
>             "properties": {
>                 "scope": {
>                     "type": "string"
>                 },
>                 "strict": {
>                     "type": "boolean"
>                 },
>                 "indent_by": {
>                     "type": "number"
>                 },
>                 "start_comments_with_one_space": {
>                     "type": "boolean"
>                 },
>                 "math_token_spacing": {
>                     "type": "object"
>                 },
>                 "reindention": {
>                     "type": "object"
>                 }
>             },
>             "additionalProperties": false,
>             "type": "object"
>         }

**Comment by ryantam626** [comment]
Again forgot to close this :sweat:  implemented in v1.0.3 - let me know if it doesn't work somehow :+1:
