### ISSUE TITLE
Add a "string" option to the styler schema for math_token_spacing and reindention

### ISSUE THREAD

**Issue by andrewtcrooks** [ryantam626/jupyterlab_code_formatter#81]
According to the [documentation](https://cran.r-project.org/web/packages/styler/styler.pdf), both math_token spacing and reindention can take a string input if the string is "tidyverse_math_token_spacing()" or " tidyverse_reindention()" respectively.

could the schema have the following?

    "styler": {
        "properties": {
            "scope": {
                "type": "string"
            },
            "strict": {
                "type": "boolean"
            },
            "indent_by": {
                "type": "number"
            },
            "start_comments_with_one_space": {
                "type": "boolean"
            },
            "math_token_spacing": {
                "type": "object" or "string"
            },
            "reindention": {
                "type": "object" or "string"
            }
        },
        "additionalProperties": false,
        "type": "object"
    }

**Comment by ryantam626** [comment]
Hmm need to make changes to the server extension to reflect this change as well, because it's assuming that math_token_spacing or reindention will be passed as dict parsed from JSON object

**Comment by ryantam626** [comment]
Ah, forgot to close this, implemented in v1.0.3 - let me know if it doesn't work somehow :+1:
