### ISSUE TITLE
Fix formatting for cells that include magic commands

### ISSUE THREAD

**Issue by thoralf-gutierrez** [ryantam626/jupyterlab_code_formatter#84]
I noticed that cells with magic commands (that start with `%`) don't get formatted as they are not valid python. This was [fixed for black formatting](https://github.com/ryantam626/jupyterlab_code_formatter/pull/18). Should we apply a similar fix to all code formatters?

**Comment by ryantam626** [comment]
Hello :wave: , yes that should have been implemented, I am working towards a `1.0.0` version with better docs, some code refactoring and tests, this issue should be resolved as part of that.

**Comment by ryantam626** [comment]
Forgot to close this, this should be fixed already
