### ISSUE TITLE
Release 0.7.1?

### ISSUE THREAD

**Issue by jtpio** [ryantam626/jupyterlab_code_formatter#86]
Hi,

The new icon added in the last merged PR looks great:

![image](https://user-images.githubusercontent.com/591645/69718837-8dd5c480-110f-11ea-8976-9cce67546e22.png)

Are there any plans to release a new version that would ship the new icon?

Thanks!

**Comment by ryantam626** [comment]
Hey! I am hoping to bundle in the changes with release 1.0.0, but writing typescript tests is taking more time than expected (more so when I don't do TS for a living). Seeing as this is not a massive improvement of the functionality of this plugin, I want to hold off until 1.0.0 lands (hopefully this weekend) if that's alright :grimacing:

**Comment by jtpio** [comment]
Alright, thanks for the heads-up!
