### ISSUE TITLE
Pluggable custom formatters

### ISSUE THREAD

**Issue by jtpio** [ryantam626/jupyterlab_code_formatter#87]
For now the different formatters run in process by importing the Python modules directly. For example:

https://github.com/ryantam626/jupyterlab_code_formatter/blob/ca74872e842ac20e4c9086eb8d008243942e824c/jupyterlab_code_formatter/formatters.py#L75-L78

It would be interesting if we could have them also be pluggable using the notebook server config:

```python
c.JupyterLabCodeFormatter.extra_formatters = {
     "custom": CustomFormatter(),
}
```

That could be also useful for #24, so users could provide their own formatters if they are not available by default.

**Comment by ryantam626** [comment]
Ooo, yes indeed. I will try to pick this up some other time if you aren't already looking :)

**Comment by jtpio** [comment]
Nope, this is free for pick up :)

**Comment by marctorsoc** [comment]
Hi, I'm interested in this. In my company we have our own version of black https://github.com/globality-corp/globality-black and I would like to run this instead. Happy to help, if someone can tell me what changes are needed (high-level)

The first thing I see is that we should add CustomFormatter into https://github.com/ryantam626/jupyterlab_code_formatter/blob/master/jupyterlab_code_formatter/formatters.py. This seems easy. What other things we need to do?

**Comment by ryantam626** [comment]
Hi @marctorsoc, sorry for the late reply, this got buried in my inbox.

I need some time to think about this

**Comment by ryantam626** [comment]
Much easier than I thought, I documented how to add one in https://jupyterlab-code-formatter.readthedocs.io/en/latest/how-to-use.html#custom-formatter

**Comment by marctorsoc** [comment]
wow, this looks amazing @ryantam626 . I'm gonna try it this weekend and let you know. thanks!

**Comment by marctorsoc** [comment]
could you explain what the `notebook` parameter is for /means ?

**Comment by ryantam626** [comment]
Sure, Jupyter Lab supports editing text file in a non-notebook environment (think editing a regular `*.py` file e.g.) as well as that in an interactive notebook environment (i.e. good old `*.ipynb`), people wanted the formatting behaviour in these two environment different and the `notebook` param is exactly for that.

**Comment by marctorsoc** [comment]
Hi @ryantam626 , I  changed the settings to

```
{
    "preferences": {
        "default_formatter": {
            "python": [
                "isort",
                "gblack",
            ],
            "r": "formatR"
        }
    },
}
```

 and added 
```
from jupyterlab_code_formatter.formatters import BaseFormatter, handle_line_ending_and_magic, SERVER_FORMATTERS

class GblackFormatter(BaseFormatter):

    label = "Apply Gblack Formatter"

    @property
    def importable(self) -> bool:
        try:
            print("importing")
            from globality_black.black_handler import get_black_mode
            from globality_black.reformat_text import reformat_text
            return True
        except:
            return False

    @handle_line_ending_and_magic
    def format_code(self, code: str, notebook: bool, **options) -> str:
        print("applying black...")
        black_mode = get_black_mode(None)
        return reformat_text(code, black_mode)

SERVER_FORMATTERS['gblack'] = GblackFormatter()

print("helloooo")
```

to jupyter_notebook_config.py. I can see the print for "hello" and "importing" when I run `jupyter lab`, but when I try to use the extension I see 

```
[E 2021-04-03 17:29:30.531 ServerApp] Uncaught exception POST /jupyterlab_code_formatter/format?1617467370526 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/jupyterlab_code_formatter/format?1617467370526', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/marctorrellassocastro/miniconda3/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/marctorrellassocastro/miniconda3/lib/python3.8/site-packages/jupyterlab_code_formatter/handlers.py", line 99, in post
        options = data["options"] or {}
    KeyError: 'options'
```

any ideas?

**Comment by ryantam626** [comment]
Doh, I forgot to mention you need to upgrade the plugin which fixes that exact issue.

**Comment by marctorsoc** [comment]
ok, great. I made it work at the end! It's a bit strange that I need to import twice: one in `importable` and one in `format_code`. Maybe this is something to improve in the docs. Thanks a lot for your help :)

**Comment by marctorsoc** [comment]
Hi @ryantam626, how can I pass options to my custom formatter?

**Comment by ryantam626** [comment]
Just doing some house cleaning - given there is a way to plug custom formatters in, I think this could be closed for now.
