### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by mlucool** [ryantam626/jupyterlab_code_formatter#90]
Hi,

It seems when you are publishing to npm, it's not also pushing a tag to github. The last release on Nov 2nd was v0.7.0 [according to github](https://github.com/ryantam626/jupyterlab_code_formatter/releases), while [npmjs says](https://www.npmjs.com/package/@ryantam626/jupyterlab_code_formatter) 1.0.2 was published on 12/1. Can we add automation around this to prevent this mismatch?

**Comment by ryantam626** [comment]
Ah, knew I forgot something.. I have pushed the tag now, also included it in the Makefile.
