### ISSUE TITLE
Bug when opening a workspace

### ISSUE THREAD

**Issue by mlucool** [ryantam626/jupyterlab_code_formatter#91]
I opened my workspace and it looked like this:
![image](https://user-images.githubusercontent.com/1813603/70102928-a0686600-1607-11ea-9d63-a2b8653ee0d9.png)

I clicked format and it formats the wrong notebook (untitled.ipynb instead of untitled5.ipynb). Switching back and forth fixes it. I tested against an older version before the refactor, and this was not a problem previously. This seems to only happen when the selected notebook is not the leftmost one.

Version: 1.0.2

**Comment by ryantam626** [comment]
Hmm weird.. I assume you clicked the format notebook button to format all cells?
I will have a look this weekend, must have accidentally changed something in the refactoring.

**Comment by mlucool** [comment]
It's actually a little more subtle. You have to click in a cell seems to trigger it. See this gif (the white is a page refresh):
![formatError](https://user-images.githubusercontent.com/1813603/70146306-e9540500-166f-11ea-8945-1955412e5ff6.gif)

**Comment by ryantam626** [comment]
Had a look just now, this is very weird, code that gets the code cells to format is mostly left alone in the refactoring..

And tapping into `INotebookTracker.currentChanged` (and just console log whatever it spits out) shows that jupyter lab thinks the current notebook is Untitled6.ipynb in your example for some reason, and when moving over to Untitled6.ipynb, that signal doesn't fire at all..

More invetigation needed..

**Comment by mlucool** [comment]
I just retested and it seems it is there also in the previous version. I must have done something slightly differently when I tested....

**Comment by ryantam626** [comment]
Aha! Guess we need to file an inssue over at the jupyterlab repo :man_shrugging:

**Comment by mlucool** [comment]
This is actually a more serious bug that is easy to reproduce:
![formatBug](https://user-images.githubusercontent.com/1813603/70726079-80056f00-1ccb-11ea-80c9-60cf2e9b1648.gif)

It's due to using the current widget instead of extending the document. I won't have time to get to this for a while, but this is an outline of an approach to fix it:

1. Fix how when the extension is called:
```
  activate: (
    app: JupyterFrontEnd,
    palette: ICommandPalette,
    tracker: INotebookTracker,
    settingRegistry: ISettingRegistry,
    menu: IMainMenu,
    editorTracker: IEditorTracker
  ) => {
    app.docRegistry.addWidgetExtension(
        'Notebook',
        new JupyterLabCodeFormatter(
            app,
            tracker,
            palette,
            settingRegistry,
            menu,
            editorTracker
        )
    );
````
2. Move all formatting functions to take notebook, client as args instead of class based.
3. When `createNew` is called, create a new button similar [to this](https://github.com/jupyterlab/jupyterlab/blob/8dc587729e5f2b2fa6087e854f0f988c0232802e/packages/notebook/src/default-toolbar.tsx#L175). This will ensure the correct notebook is always passed. For actions in the action menu, we can continue to use the current notebook logic in place.
4. Similar things may need to be done for fileEditors

**Comment by mlucool** [comment]
@ryantam626 any thoughts on this?

**Comment by ryantam626** [comment]
Hey! Sorry for going AFK for a while.

Thanks for the pointers, I will have a look these few days :smile:

**Comment by ryantam626** [comment]
Had a look, 1,2 (and probably 4) are probably irrelevant.

3 was really useful though thanks! I have a fix now, I will bundle it with some other changes and release soon.

**Comment by mlucool** [comment]
I'm happy to review the changes if you'd like

**Comment by ryantam626** [comment]
Sure :grinning: . [Here](https://github.com/ryantam626/jupyterlab_code_formatter/pull/100/commits/6d8ade7411113940b9ab39f549a9df870066fee6) it is. Thanks!
