### ISSUE TITLE
No newline at end of file when formatting files

### ISSUE THREAD

**Issue by StevenLaan** [ryantam626/jupyterlab_code_formatter#92]
When applying the formatter to a file (as opposed to a notebook) it removes the final newline. 
This is intended for notebook cells, but for code-files I would like to have parity with command line `black`.

This line is the cause (for black formatter):
https://github.com/ryantam626/jupyterlab_code_formatter/blob/6c1e3c8bb1aaf2599e4d1cefbec0151d668d6e59/serverextension/jupyterlab_code_formatter/formatters.py#L63

Every (python) formatter has a line like the one above.

**Proposal for a proper solution**
Do not cut off the last character on the server-extension, but rather make this decision in the lab-extension based on whether you format a notebook or a file.

**Quick fix**
The simplest quick and dirty fix is to always append a newline in the `JupyterlabFileEditorCodeFormatter` on this line https://github.com/ryantam626/jupyterlab_code_formatter/blob/6c1e3c8bb1aaf2599e4d1cefbec0151d668d6e59/labextension/src/formatter.ts#L170-L171

**Comment by ryantam626** [comment]
Yep indeed, will change this this weekend. :+1:

**Comment by ryantam626** [comment]
Sorry for the delay :sweat: ... This has been implemented and published in v1.1.0, let me know if it doesn't work somehow :+1:
