### ISSUE TITLE
Improve packaging

### ISSUE THREAD

**Issue by fcollonval** [ryantam626/jupyterlab_code_formatter#93]
You could improve the packaging of the extension to dis/enable automatically the server extension when installing the package and to put the frontend extension at a place JupyterLab is looking for them.

I describe the process in that draft example:
https://github.com/jtpio/jupyterlab-extension-examples/tree/serverextension-example/advanced/myserverextension#packaging-the-extension

It will be a bit more complicated for you to ship the frontend within the Python package due to the source code structure and the use of poetry (?). But it will ease the user experience.

**Comment by ryantam626** [comment]
Ah yes, I think I saw something like this a while back but totally forgot about it. Using poetry does seem to make a tad bit more difficult :thinking:

**Comment by fcollonval** [comment]
Follow-up

For JLab 3, the recommended way of shipping an extension is a single Python package. So you will benefit of organizing this extension as proposed in the [cookiecutter for extension](https://github.com/jupyterlab/extension-cookiecutter-ts) - it now can initiates extension with a server extension.

My best guess to do so is to run the cookiecutter from scratch and move your code in the appropriate places.

**Comment by ryantam626** [comment]
Gotcha, when is it safe to do so? I want to hold off working on this until JLab 3 is more or lese finalised, lest any upstream changes cause breakages in the ported code.

**Comment by fcollonval** [comment]
It should be safe to do so as JLab 3 has enter release candidate cycle (meaning no breaking change expected). But there are still some corrections on the new way of handling JS dependencies. So I understand you holding off. And I don't know when the release will be done.
