### ISSUE TITLE
404 POST

### ISSUE THREAD

**Issue by Daya-Jin** [ryantam626/jupyterlab_code_formatter#99]
I have installed jupyterlab extension and code_formatter, and I can see it in the extension manager. But I can't use it. The err info is show below:

```
[W 09:39:24.773 LabApp] 404 POST /jupyterlab_code_formatter/format?1576460364557 (127.0.0.1) 2.29ms referer=http://localhost:8910/lab?
```

![image](https://user-images.githubusercontent.com/26544610/70873325-493f9980-1fe8-11ea-8936-a3f71c330e5a.png)

I installed another extension TOC and it is normal.

![image](https://user-images.githubusercontent.com/26544610/70873361-70966680-1fe8-11ea-86c9-bb482b7504af.png)

**Comment by ryantam626** [comment]
This plugin is a little more complicated than the TOC plugin.

Make sure you have followed the setup steps as documented in [here](https://jupyterlab-code-formatter.readthedocs.io/en/latest/installation.html).

(It looked like the `pip install jupyterlab_code_formatter` and `jupyter serverextension enable --py jupyterlab_code_formatter` part are missing)

**Comment by Daya-Jin** [comment]
> This plugin is a little more complicated than the TOC plugin.
> 
> Make sure you have followed the setup steps as documented in [here](https://jupyterlab-code-formatter.readthedocs.io/en/latest/installation.html).
> 
> (It looked like the `pip install jupyterlab_code_formatter` and `jupyter serverextension enable --py jupyterlab_code_formatter` part are missing)

I‘m sure I totally followed the doc's instruction. I don'r know why it's not work for me. And it's the first extension I installed after I installed jupyterlab.

**Comment by ryantam626** [comment]
Could you show me output of

pip freeze | grep 'jupyterlab\|rpy'
jupyter labextension list
jupyter serverextension list
please?

**Comment by Daya-Jin** [comment]
Here, I marked some personal info.
![2019-12-17_19-25-21](https://user-images.githubusercontent.com/26544610/70991828-471e2d80-2103-11ea-9b5b-c7c1cacea2ae.jpg)

**Comment by ryantam626** [comment]
Hmm.. seems alright to me.

Can you show me the complete output of `pip freeze`?

I am thinking you might not have a formatter installed :thinking:

**Comment by mmoutenot** [comment]
I'm running into the same problem. I ran the following commands, restarted jupyter and see `404 POST` upon formatting.

```
jupyter labextension install @ryantam626/jupyterlab_code_formatter
pip install jupyterlab_code_formatter
jupyter serverextension enable --py jupyterlab_code_formatter
pip install yapf
```
[pip-freeze.txt](https://github.com/ryantam626/jupyterlab_code_formatter/files/3998464/pip-freeze.txt)


`404 POST /jupyterlab_code_formatter/format?1577192810719 (192.168.1.245) 1.27ms referer=http://marshbox.local:8888/lab/workspaces/auto-R`

`pip freeze` attached, but also sort of a lot.

**Comment by mlucool** [comment]
@ryantam626 you can tell jupyterlab to auto-install this too. This commit gives an outline of what to do (among bunch of other code, but it mostly comes down to [this](https://github.com/jupyterlab/jupyterlab-git/blob/master/jupyter-config/jupyter_notebook_config.d/jupyterlab_git.json)): https://github.com/jupyterlab/jupyterlab-git/pull/415

**Comment by ryantam626** [comment]
Yep, I am already aware, I don't use `setup.py` directly, so it's a lot of work to get it right, which I don't have the time for right now sadly.

**Comment by ryantam626** [comment]
@Daya-Jin @mmoutenot I can't replicate this on my end :disappointed: (tried with conda on my machine and even a bare ubuntu docker image) I need a little bit more info if possible.

Could you try visiting `http://localhost:8888/jupyterlab_code_formatter/formatters` and see what's the response?

Also could you open web console and try the format commands once more? The error should also show up there, I am hoping those will be a little bit more specific.

**Comment by ryantam626** [comment]
@Daya-Jin @mmoutenot I can't replicate this on my end :disappointed: (tried with conda on my machine and even a bare ubuntu docker image) I need a little bit more info if possible.

Could you try visiting `http://localhost:8888/jupyterlab_code_formatter/formatters` (might need to change the host/port depending on your setup) and see what's the response?

Also could you open web console and try the format commands once more? The error should also show up there, I am hoping those will be a little bit more specific.

**Comment by mmoutenot** [comment]
this is the output from the address:

```json
{
  "formatters": {
    "black": {
      "enabled": false,
      "label": "Apply Black Formatter"
    },
    "autopep8": {
      "enabled": false,
      "label": "Apply Autopep8 Formatter"
    },
    "yapf": {
      "enabled": true,
      "label": "Apply YAPF Formatter"
    },
    "isort": {
      "enabled": false,
      "label": "Apply Isort Formatter"
    },
    "formatR": {
      "enabled": false,
      "label": "Apply FormatR Formatter"
    },
    "styler": {
      "enabled": false,
      "label": "Apply Styler Formatter"
    }
  }
}
```

Attempting the web console right now. Thanks for the help, and I apologize if this is a holiday for ya.

**Comment by mmoutenot** [comment]
From the web console, I see this being thrown:

```
Something went wrong :(
Error: Invalid response: 404 Formatter not found!
    at client.js:12
```

in this method:

```js
class JupyterlabCodeFormatterClient {
    request(path, method, body, settings) {
        const fullUrl = coreutils_1.URLExt.join(settings.baseUrl, constants_1.Constants.SHORT_PLUGIN_NAME, path);
        return services_1.ServerConnection.makeRequest(fullUrl, { body, method }, settings).then(response => {
            if (response.status !== 200) {
                return response.text().then(data => {
                    // here
                    throw new services_1.ServerConnection.ResponseError(response, data);
                });
            }
            return response.text();
        });
    }
    getAvailableFormatters() {
        return this.request('formatters', 'GET', null, services_1.ServerConnection.defaultSettings);
    }
}
```

**Comment by mmoutenot** [comment]
One difference pointed out is pip in a virtual environment versus conda?

**Comment by mmoutenot** [comment]
Ah, sorry for so many messages. I should have collected all the data and _then_ sent the messages.

I do see this assigned to `fullUrl` when stepping through the above method.
```
message: "s is not defined"
stack: "ReferenceError: s is not defined↵    at eval (eval at <anonymous> (http://marshbox.local:8888/static/lab/vendors~main.19dae45b4e03d36467cc.js:1:900128), <anonymous>:1:1)↵    at http://marshbox.local:8888/static/lab/vendors~main.19dae45b4e03d36467cc.js:1:900128"
__proto__: Error
```

**Comment by ryantam626** [comment]
Aha! That's a good lead! How are you invoking the formatter?

Do you search for the command in the command palette (Ctrl+Shift+C opens it), or do you right click -> format cell in the context menu / click the weird icon on the notebook toolbar?

**Comment by mmoutenot** [comment]
That's it! Command palette works, context menu does not.

**Comment by ryantam626** [comment]
I have added a small section in the docs so that the default formatters configuration step is a little bit more prominent, [in here](https://jupyterlab-code-formatter.readthedocs.io/en/latest/installation.html#installation-step-4-configuring-the-plugin).

**Comment by ryantam626** [comment]
Closing this now due to inactivity.

**Comment by endremborza** [comment]
this is currently happening to me, I can't really work out a solution based on this discussion, and the link posted is dead.

also, the possibility of disabling or uninstalling from within the jupyterlab GUI also went away, everything is 404 and the console instantly greets me with this:

404 - http://localhost:8888/jupyterlab_code_formatter/formatters?1706700070864

everything seems to be 404 under /jupyterlab_code_formatter and it is very difficult to tell why

**Comment by luomomo83** [comment]
hi,i also came with 404 problem for hours, but when i closed vpn, the function is ok except the jupyterlab_code_formatter items in the left toolbar is with a pink line.
and when i use: jupyter labextension list,
it shows:
jupyterlab_code_formatter v2.2.1 enabled  X (python, jupyterlab_code_formatter)
